// Code generated by `cargo xtask codegen` from databricks-sdk-go v0.182.0 (OpenAPI 4648d66fa37e7683468dc92cc043c6aa7a34f301). DO NOT EDIT.

//! Databricks `dataclassification` API: models and services.
//!
//! Generated from databricks-sdk-go v0.182.0; use it through the
//! [`community-databricks-sdk`](https://docs.rs/community-databricks-sdk) clients
//! (`community_databricks_sdk::service::dataclassification`).

#![allow(
    clippy::all,
    clippy::pedantic,
    rustdoc::broken_intra_doc_links,
    rustdoc::invalid_html_tags,
    rustdoc::bare_urls,
    unused_imports
)]

use community_databricks_core::http::{Call, Method, path_param};
use community_databricks_core::paging::{self, Paged};
use community_databricks_core::{ApiClient, query, wait};

/// Auto-tagging configuration for a classification tag. When enabled, detected
/// columns are automatically tagged with Unity Catalog tags.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct AutoTaggingConfig {
    /// Whether auto-tagging is enabled or disabled for this classification tag.
    #[serde(default)]
    pub auto_tagging_mode: AutoTaggingConfigAutoTaggingMode,
    /// The Classification Tag. For built-in classes this is a system tag (e.g.,
    /// "class.name", "class.location"); for custom classes it is a user-defined
    /// governance tag key.
    #[serde(default)]
    pub classification_tag: String,
}

impl AutoTaggingConfig {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(
        auto_tagging_mode: impl Into<AutoTaggingConfigAutoTaggingMode>,
        classification_tag: impl Into<String>,
    ) -> Self {
        Self {
            auto_tagging_mode: auto_tagging_mode.into(),
            classification_tag: classification_tag.into(),
            ..Default::default()
        }
    }

    /// Set `auto_tagging_mode`.
    #[must_use]
    pub fn with_auto_tagging_mode(
        mut self,
        value: impl Into<AutoTaggingConfigAutoTaggingMode>,
    ) -> Self {
        self.auto_tagging_mode = value.into();
        self
    }

    /// Set `classification_tag`.
    #[must_use]
    pub fn with_classification_tag(mut self, value: impl Into<String>) -> Self {
        self.classification_tag = value.into();
        self
    }
}

::community_databricks_core::open_enum! {
    /// Auto-tagging mode.
    pub enum AutoTaggingConfigAutoTaggingMode {
        /// `AUTO_TAGGING_DISABLED`
        AutoTaggingDisabled => "AUTO_TAGGING_DISABLED",
        /// `AUTO_TAGGING_ENABLED`
        AutoTaggingEnabled => "AUTO_TAGGING_ENABLED",
    }
}

/// Data Classification configuration for a Unity Catalog catalog. This message
/// follows the "At Most One Resource" pattern: at most one CatalogConfig exists
/// per catalog. - Full CRUD operations are supported: Create enables Data
/// Classification, Delete disables it - It has no unique identifier of its own
/// and uses its parent catalog's identifier (catalog_name)
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct CatalogConfig {
    /// List of auto-tagging configurations for this catalog. Empty list means no
    /// auto-tagging is enabled.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub auto_tag_configs: Vec<AutoTaggingConfig>,
    /// Schemas to exclude from the scan, each named relative to the parent
    /// catalog. If specified, all schemas except the specified ones will be
    /// scanned. Mutually exclusive with `included_schemas`: only one may be set
    /// per request. If neither `included_schemas` nor `excluded_schemas` is set,
    /// all schemas are scanned.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub excluded_schemas: Option<CatalogConfigSchemaNames>,
    /// Schemas to include in the scan, each named relative to the parent
    /// catalog. If specified, only listed schemas will be scanned. Mutually
    /// exclusive with `excluded_schemas`: only one may be set per request. If
    /// neither `included_schemas` nor `excluded_schemas` is set, all schemas are
    /// scanned.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub included_schemas: Option<CatalogConfigSchemaNames>,
    /// Resource name in the format: catalogs/{catalog_name}/config.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl CatalogConfig {
    /// Set `auto_tag_configs`.
    #[must_use]
    pub fn with_auto_tag_configs(mut self, value: impl Into<Vec<AutoTaggingConfig>>) -> Self {
        self.auto_tag_configs = value.into();
        self
    }

    /// Set `excluded_schemas`.
    #[must_use]
    pub fn with_excluded_schemas(mut self, value: impl Into<CatalogConfigSchemaNames>) -> Self {
        self.excluded_schemas = Some(value.into());
        self
    }

    /// Set `included_schemas`.
    #[must_use]
    pub fn with_included_schemas(mut self, value: impl Into<CatalogConfigSchemaNames>) -> Self {
        self.included_schemas = Some(value.into());
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = Some(value.into());
        self
    }
}

/// Wrapper message for a list of schema names.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct CatalogConfigSchemaNames {
    /// Schema names, each relative to the parent catalog. Must not be empty.
    #[serde(default)]
    pub names: Vec<String>,
}

impl CatalogConfigSchemaNames {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(names: impl Into<Vec<String>>) -> Self {
        Self {
            names: names.into(),
            ..Default::default()
        }
    }

    /// Set `names`.
    #[must_use]
    pub fn with_names(mut self, value: impl Into<Vec<String>>) -> Self {
        self.names = value.into();
        self
    }
}

/// `CreateCatalogConfigRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct CreateCatalogConfigRequest {
    /// The configuration to create.
    #[serde(default)]
    pub catalog_config: CatalogConfig,
    /// Parent resource in the format: catalogs/{catalog_name}
    #[serde(skip)]
    pub parent: String,
}

impl CreateCatalogConfigRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(catalog_config: impl Into<CatalogConfig>, parent: impl Into<String>) -> Self {
        Self {
            catalog_config: catalog_config.into(),
            parent: parent.into(),
            ..Default::default()
        }
    }

    /// Set `catalog_config`.
    #[must_use]
    pub fn with_catalog_config(mut self, value: impl Into<CatalogConfig>) -> Self {
        self.catalog_config = value.into();
        self
    }

    /// Set `parent`.
    #[must_use]
    pub fn with_parent(mut self, value: impl Into<String>) -> Self {
        self.parent = value.into();
        self
    }
}

/// `DeleteCatalogConfigRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct DeleteCatalogConfigRequest {
    /// Resource name in the format: catalogs/{catalog_name}/config
    #[serde(skip)]
    pub name: String,
}

impl DeleteCatalogConfigRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// `GetCatalogConfigRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GetCatalogConfigRequest {
    /// Resource name in the format: catalogs/{catalog_name}/config
    #[serde(skip)]
    pub name: String,
}

impl GetCatalogConfigRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// `UpdateCatalogConfigRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct UpdateCatalogConfigRequest {
    /// The configuration to apply to the catalog. The name field in
    /// catalog_config identifies which resource to update.
    #[serde(default)]
    pub catalog_config: CatalogConfig,
    /// Resource name in the format: catalogs/{catalog_name}/config.
    #[serde(skip)]
    pub name: String,
    /// Field mask specifying which fields to update.
    #[serde(skip)]
    pub update_mask: String,
}

impl UpdateCatalogConfigRequest {
    /// Set `catalog_config`.
    #[must_use]
    pub fn with_catalog_config(mut self, value: impl Into<CatalogConfig>) -> Self {
        self.catalog_config = value.into();
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }

    /// Set `update_mask`.
    #[must_use]
    pub fn with_update_mask(mut self, value: impl Into<String>) -> Self {
        self.update_mask = value.into();
        self
    }
}

/// Manage data classification for Unity Catalog catalogs. Data
/// classification automatically identifies and tags sensitive data (PII) in
/// Unity Catalog tables. Each catalog can have at most one configuration
/// resource that controls scanning behavior and auto-tagging rules.
#[derive(Debug, Clone)]
pub struct DataClassificationApi {
    api: ApiClient,
}

impl DataClassificationApi {
    /// Wrap an [`ApiClient`].
    #[must_use]
    pub fn new(api: ApiClient) -> Self {
        Self { api }
    }

    /// Create Data Classification configuration for a catalog.
    ///
    /// Creates a new config resource, which enables Data Classification for the
    /// specified catalog. - The config must not already exist for the catalog.
    ///
    /// `POST /api/data-classification/v1/{parent}/config`
    pub async fn create_catalog_config(
        &self,
        request: CreateCatalogConfigRequest,
    ) -> ::community_databricks_core::Result<CatalogConfig> {
        let path = format!(
            "/api/data-classification/v1/{}/config",
            path_param(&request.parent.to_string(), true)
        );
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request.catalog_config)?;
        self.api.send::<CatalogConfig>(call).await
    }

    /// Delete Data Classification configuration for a catalog.
    ///
    /// `DELETE /api/data-classification/v1/{name}`
    pub async fn delete_catalog_config(
        &self,
        request: DeleteCatalogConfigRequest,
    ) -> ::community_databricks_core::Result<()> {
        let path = format!(
            "/api/data-classification/v1/{}",
            path_param(&request.name.to_string(), true)
        );
        let call = Call::new(Method::DELETE, path).workspace();
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Get the Data Classification configuration for a catalog.
    ///
    /// `GET /api/data-classification/v1/{name}`
    pub async fn get_catalog_config(
        &self,
        request: GetCatalogConfigRequest,
    ) -> ::community_databricks_core::Result<CatalogConfig> {
        let path = format!(
            "/api/data-classification/v1/{}",
            path_param(&request.name.to_string(), true)
        );
        let call = Call::new(Method::GET, path).workspace();
        self.api.send::<CatalogConfig>(call).await
    }

    /// Update the Data Classification configuration for a catalog. - The config must
    /// already exist for the catalog. - Updates fields specified in the update_mask.
    /// Use update_mask field to perform partial updates of the configuration.
    ///
    /// `PATCH /api/data-classification/v1/{name}`
    pub async fn update_catalog_config(
        &self,
        request: UpdateCatalogConfigRequest,
    ) -> ::community_databricks_core::Result<CatalogConfig> {
        let path = format!(
            "/api/data-classification/v1/{}",
            path_param(&request.name.to_string(), true)
        );
        let mut call = Call::new(Method::PATCH, path).workspace();
        call = call.query(query::field("update_mask", &request.update_mask)?);
        call = call.json(&request.catalog_config)?;
        self.api.send::<CatalogConfig>(call).await
    }
}
