// Code generated by `cargo xtask codegen` from databricks-sdk-go v0.182.0 (OpenAPI 4648d66fa37e7683468dc92cc043c6aa7a34f301). DO NOT EDIT.

//! Databricks `aifunctions` API: models and services.
//!
//! Generated from databricks-sdk-go v0.182.0; use it through the
//! [`community-databricks-sdk`](https://docs.rs/community-databricks-sdk) clients
//! (`community_databricks_sdk::service::aifunctions`).

#![allow(
    clippy::all,
    clippy::pedantic,
    rustdoc::broken_intra_doc_links,
    rustdoc::invalid_html_tags,
    rustdoc::bare_urls,
    unused_imports
)]

use community_databricks_core::http::{Call, Method, path_param};
use community_databricks_core::paging::{self, Paged};
use community_databricks_core::{ApiClient, query, wait};

/// ai_classify
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct AiClassifyOptions {
    /// When true, includes a per-label confidence score in the response.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enable_confidence_scores: Option<bool>,
    /// When true, includes a rationale explaining each classification in the
    /// response.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enable_rationales: Option<bool>,
    /// Natural-language guidance that steers how the text is classified (up to
    /// 20,000 characters).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub instructions: Option<String>,
    /// When true, allows more than one label to be returned per input.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub multilabel: Option<bool>,
    /// The function version to invoke. Defaults to the latest version. Supported
    /// versions: ["2.1"].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request: in the JSON body, or in the query string for GET/DELETE
    /// and for requests whose body is a single field (that field's own
    /// `other` carries unknown body fields).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl AiClassifyOptions {
    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `enable_confidence_scores`.
    #[must_use]
    pub fn with_enable_confidence_scores(mut self, value: bool) -> Self {
        self.enable_confidence_scores = Some(value);
        self
    }

    /// Set `enable_rationales`.
    #[must_use]
    pub fn with_enable_rationales(mut self, value: bool) -> Self {
        self.enable_rationales = Some(value);
        self
    }

    /// Set `instructions`.
    #[must_use]
    pub fn with_instructions(mut self, value: impl Into<String>) -> Self {
        self.instructions = Some(value.into());
        self
    }

    /// Set `multilabel`.
    #[must_use]
    pub fn with_multilabel(mut self, value: bool) -> Self {
        self.multilabel = Some(value);
        self
    }

    /// Set `version`.
    #[must_use]
    pub fn with_version(mut self, value: impl Into<String>) -> Self {
        self.version = Some(value.into());
        self
    }
}

/// `AiClassifyRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct AiClassifyRequest {
    /// The content to classify. It accepts a plain string or the response object
    /// of [ai_parse_document](:method:AiFunctions/AiParseDocument).
    #[serde(default)]
    pub content: ::serde_json::Value,
    /// The label set to classify as. Either a JSON array of label strings (e.g.
    /// ["spam", "not_spam"]), or a JSON object mapping each label to a
    /// description (e.g. {"spam": "unsolicited bulk message", "not_spam": "a
    /// legitimate message"}). Accepts 2 to 500 labels, each 1 to 100 characters.
    #[serde(default)]
    pub labels: ::serde_json::Value,
    /// Function options. Omitted fields fall back to their documented defaults.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub options: Option<AiClassifyOptions>,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request: in the JSON body, or in the query string for GET/DELETE
    /// and for requests whose body is a single field (that field's own
    /// `other` carries unknown body fields).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl AiClassifyRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(
        content: impl Into<::serde_json::Value>,
        labels: impl Into<::serde_json::Value>,
    ) -> Self {
        Self {
            content: content.into(),
            labels: labels.into(),
            ..Default::default()
        }
    }

    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `content`.
    #[must_use]
    pub fn with_content(mut self, value: impl Into<::serde_json::Value>) -> Self {
        self.content = value.into();
        self
    }

    /// Set `labels`.
    #[must_use]
    pub fn with_labels(mut self, value: impl Into<::serde_json::Value>) -> Self {
        self.labels = value.into();
        self
    }

    /// Set `options`.
    #[must_use]
    pub fn with_options(mut self, value: impl Into<AiClassifyOptions>) -> Self {
        self.options = Some(value.into());
        self
    }
}

/// `AiClassifyResponse`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct AiClassifyResponse {
    /// Additional metadata returned by AI Classify.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<AiClassifyResponseMetadata>,
    /// The function result as a JSON value. An array of per-label objects: one
    /// element in single-label mode (the default), or multiple elements when
    /// `multilabel` is true. When `enable_confidence_scores` and
    /// `enable_rationales` are true, `confidence_score` and `rationale` are
    /// included in each response value, respectively.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub response: Option<::serde_json::Value>,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request: in the JSON body, or in the query string for GET/DELETE
    /// and for requests whose body is a single field (that field's own
    /// `other` carries unknown body fields).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl AiClassifyResponse {
    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `metadata`.
    #[must_use]
    pub fn with_metadata(mut self, value: impl Into<AiClassifyResponseMetadata>) -> Self {
        self.metadata = Some(value.into());
        self
    }

    /// Set `response`.
    #[must_use]
    pub fn with_response(mut self, value: impl Into<::serde_json::Value>) -> Self {
        self.response = Some(value.into());
        self
    }
}

/// `AiClassifyResponseMetadata`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct AiClassifyResponseMetadata {
    /// The resolved function version.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request: in the JSON body, or in the query string for GET/DELETE
    /// and for requests whose body is a single field (that field's own
    /// `other` carries unknown body fields).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl AiClassifyResponseMetadata {
    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `version`.
    #[must_use]
    pub fn with_version(mut self, value: impl Into<String>) -> Self {
        self.version = Some(value.into());
        self
    }
}

/// A bounding box on a source page; used by bbox-input citations.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct AiExtractBbox {
    /// Pixel coordinates on the page image as [x0, y0, x1, y1].
    #[serde(
        deserialize_with = "::community_databricks_core::serde_num::vec_i64",
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub coord: Vec<i64>,
    /// 0-based page index the box is on.
    #[serde(
        deserialize_with = "::community_databricks_core::serde_num::opt_i64",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub page_id: Option<i64>,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request: in the JSON body, or in the query string for GET/DELETE
    /// and for requests whose body is a single field (that field's own
    /// `other` carries unknown body fields).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl AiExtractBbox {
    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `coord`.
    #[must_use]
    pub fn with_coord(mut self, value: impl Into<Vec<i64>>) -> Self {
        self.coord = value.into();
        self
    }

    /// Set `page_id`.
    #[must_use]
    pub fn with_page_id(mut self, value: i64) -> Self {
        self.page_id = Some(value);
        self
    }
}

/// A citation locating an extracted value in the source. start/stop are set for
/// span (STRING input) citations, bbox for bbox (parsed-document input)
/// citations.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct AiExtractCitation {
    /// Bounding boxes locating the citation on the source pages; set for bbox
    /// citations.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub bbox: Vec<AiExtractBbox>,
    /// Integer matching a citation_ids entry on an extracted field.
    #[serde(
        deserialize_with = "::community_databricks_core::serde_num::opt_i64",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub id: Option<i64>,
    /// Inclusive 0-based character offset into the input string; set for span
    /// citations.
    #[serde(
        deserialize_with = "::community_databricks_core::serde_num::opt_i64",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub start: Option<i64>,
    /// Exclusive 0-based character offset into the input string; set for span
    /// citations.
    #[serde(
        deserialize_with = "::community_databricks_core::serde_num::opt_i64",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub stop: Option<i64>,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request: in the JSON body, or in the query string for GET/DELETE
    /// and for requests whose body is a single field (that field's own
    /// `other` carries unknown body fields).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl AiExtractCitation {
    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `bbox`.
    #[must_use]
    pub fn with_bbox(mut self, value: impl Into<Vec<AiExtractBbox>>) -> Self {
        self.bbox = value.into();
        self
    }

    /// Set `id`.
    #[must_use]
    pub fn with_id(mut self, value: i64) -> Self {
        self.id = Some(value);
        self
    }

    /// Set `start`.
    #[must_use]
    pub fn with_start(mut self, value: i64) -> Self {
        self.start = Some(value);
        self
    }

    /// Set `stop`.
    #[must_use]
    pub fn with_stop(mut self, value: i64) -> Self {
        self.stop = Some(value);
        self
    }
}

/// ai_extract
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct AiExtractOptions {
    /// When true, includes citation metadata locating each extracted value in
    /// the source. Depending on the type of input, citations can be one of two
    /// types:
    ///
    /// For raw text (STRING) inputs, a citation is a span of text in the
    /// original input. Each object in `metadata.citations` has an `id` (integer
    /// matching a `citation_ids` entry on a field), a `start` (inclusive 0-based
    /// character offset into the input string), and a `stop` (exclusive 0-based
    /// character offset into the input string).
    ///
    /// For PDF documents and images (when using ai_extract downstream of
    /// ai_parse_document), a citation is a bounding box in the original input.
    /// Each object in `metadata.citations` has an `id` (integer matching a
    /// `citation_ids` entry on a field) and a `bbox` (array of {coord, page_id}
    /// objects, identical in shape to element.bbox in ai_parse_document output;
    /// coord is pixel coordinates on the page image as [x0, y0, x1, y1], and
    /// page_id is a 0-based page index).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enable_citations: Option<bool>,
    /// When true, includes a per-field confidence score in the response.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enable_confidence_scores: Option<bool>,
    /// Natural-language guidance that steers how data is extracted (up to 20,000
    /// characters).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub instructions: Option<String>,
    /// Extraction mode. Supported modes: "precision" — more powerful
    /// extraction for complex schemas, long documents, and reasoning-heavy
    /// extractions. Defaults to none (standard extraction).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    /// The function version to invoke. Defaults to the latest version. Supported
    /// versions: ["2.1"].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request: in the JSON body, or in the query string for GET/DELETE
    /// and for requests whose body is a single field (that field's own
    /// `other` carries unknown body fields).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl AiExtractOptions {
    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `enable_citations`.
    #[must_use]
    pub fn with_enable_citations(mut self, value: bool) -> Self {
        self.enable_citations = Some(value);
        self
    }

    /// Set `enable_confidence_scores`.
    #[must_use]
    pub fn with_enable_confidence_scores(mut self, value: bool) -> Self {
        self.enable_confidence_scores = Some(value);
        self
    }

    /// Set `instructions`.
    #[must_use]
    pub fn with_instructions(mut self, value: impl Into<String>) -> Self {
        self.instructions = Some(value.into());
        self
    }

    /// Set `mode`.
    #[must_use]
    pub fn with_mode(mut self, value: impl Into<String>) -> Self {
        self.mode = Some(value.into());
        self
    }

    /// Set `version`.
    #[must_use]
    pub fn with_version(mut self, value: impl Into<String>) -> Self {
        self.version = Some(value.into());
        self
    }
}

/// `AiExtractRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct AiExtractRequest {
    /// The text to extract from. It accepts a plain string or the response
    /// object of [ai_parse_document](:method:AiFunctions/AiParseDocument).
    #[serde(default)]
    pub content: ::serde_json::Value,
    /// Function options. Omitted fields fall back to their documented defaults.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub options: Option<AiExtractOptions>,
    /// The extraction schema defining the fields to extract. Either a JSON array
    /// of field names, assumed to be strings (e.g. ["company", "valuation"]), or
    /// a JSON object mapping each field to its type/description/nullability
    /// (e.g. {"company": {"type": "string", "description": "the company
    /// name"}}). Accepts up to 256 fields, 12 levels of nesting, and 500 enum
    /// values. Supported field types are string, integer, number, boolean, and
    /// enum.
    #[serde(default)]
    pub schema: ::serde_json::Value,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request: in the JSON body, or in the query string for GET/DELETE
    /// and for requests whose body is a single field (that field's own
    /// `other` carries unknown body fields).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl AiExtractRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(
        content: impl Into<::serde_json::Value>,
        schema: impl Into<::serde_json::Value>,
    ) -> Self {
        Self {
            content: content.into(),
            schema: schema.into(),
            ..Default::default()
        }
    }

    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `content`.
    #[must_use]
    pub fn with_content(mut self, value: impl Into<::serde_json::Value>) -> Self {
        self.content = value.into();
        self
    }

    /// Set `options`.
    #[must_use]
    pub fn with_options(mut self, value: impl Into<AiExtractOptions>) -> Self {
        self.options = Some(value.into());
        self
    }

    /// Set `schema`.
    #[must_use]
    pub fn with_schema(mut self, value: impl Into<::serde_json::Value>) -> Self {
        self.schema = value.into();
        self
    }
}

/// `AiExtractResponse`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct AiExtractResponse {
    /// Additional metadata returned by AI Extract.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<AiExtractResponseMetadata>,
    /// The function result as a JSON value. When `enable_confidence_scores` and
    /// `enable_citations` are true, `confidence` and `citation_ids` are included
    /// in each response field, respectively.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub response: Option<::serde_json::Value>,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request: in the JSON body, or in the query string for GET/DELETE
    /// and for requests whose body is a single field (that field's own
    /// `other` carries unknown body fields).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl AiExtractResponse {
    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `metadata`.
    #[must_use]
    pub fn with_metadata(mut self, value: impl Into<AiExtractResponseMetadata>) -> Self {
        self.metadata = Some(value.into());
        self
    }

    /// Set `response`.
    #[must_use]
    pub fn with_response(mut self, value: impl Into<::serde_json::Value>) -> Self {
        self.response = Some(value.into());
        self
    }
}

/// `AiExtractResponseMetadata`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct AiExtractResponseMetadata {
    /// How the source was chunked for citation offsets (span for text input,
    /// bbox for parsed-document input); present when citations are enabled.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub chunk_type: Option<String>,
    /// Citation objects locating each result in the source; present when
    /// citations are enabled.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub citations: Vec<AiExtractCitation>,
    /// The resolved extraction mode; present when a non-default mode was used.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    /// The resolved function version.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request: in the JSON body, or in the query string for GET/DELETE
    /// and for requests whose body is a single field (that field's own
    /// `other` carries unknown body fields).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl AiExtractResponseMetadata {
    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `chunk_type`.
    #[must_use]
    pub fn with_chunk_type(mut self, value: impl Into<String>) -> Self {
        self.chunk_type = Some(value.into());
        self
    }

    /// Set `citations`.
    #[must_use]
    pub fn with_citations(mut self, value: impl Into<Vec<AiExtractCitation>>) -> Self {
        self.citations = value.into();
        self
    }

    /// Set `mode`.
    #[must_use]
    pub fn with_mode(mut self, value: impl Into<String>) -> Self {
        self.mode = Some(value.into());
        self
    }

    /// Set `version`.
    #[must_use]
    pub fn with_version(mut self, value: impl Into<String>) -> Self {
        self.version = Some(value.into());
        self
    }
}

/// Metadata about the source file; present only for file-path input.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct AiParseDocumentFileMetadata {
    /// Last-modified timestamp of the source file, as an HTTP date string.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_modification_time: Option<String>,
    /// Base name of the source file.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_name: Option<String>,
    /// Unity Catalog volume path of the source file.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_path: Option<String>,
    /// Size of the source file in bytes.
    #[serde(
        deserialize_with = "::community_databricks_core::serde_num::opt_i64",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub file_size: Option<i64>,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request: in the JSON body, or in the query string for GET/DELETE
    /// and for requests whose body is a single field (that field's own
    /// `other` carries unknown body fields).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl AiParseDocumentFileMetadata {
    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `file_modification_time`.
    #[must_use]
    pub fn with_file_modification_time(mut self, value: impl Into<String>) -> Self {
        self.file_modification_time = Some(value.into());
        self
    }

    /// Set `file_name`.
    #[must_use]
    pub fn with_file_name(mut self, value: impl Into<String>) -> Self {
        self.file_name = Some(value.into());
        self
    }

    /// Set `file_path`.
    #[must_use]
    pub fn with_file_path(mut self, value: impl Into<String>) -> Self {
        self.file_path = Some(value.into());
        self
    }

    /// Set `file_size`.
    #[must_use]
    pub fn with_file_size(mut self, value: i64) -> Self {
        self.file_size = Some(value);
        self
    }
}

/// ai_parse_document
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct AiParseDocumentOptions {
    /// Element types for which an AI-generated description is produced. Use "*"
    /// (default) to generate descriptions for all supported element types,
    /// "figure" to generate them for figures only, or "" (empty string) to
    /// generate none. Only figure descriptions are supported for version "2.0",
    /// so "*" and "figure" produce the same behavior.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description_element_types: Option<String>,
    /// Unity Catalog volume path where rendered page and element images are
    /// written.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image_output_path: Option<String>,
    /// Pages to parse (1-indexed), as a comma-separated list of page numbers or
    /// ranges (e.g. "1,3,5-10").
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub page_range: Option<String>,
    /// The ai_parse_document output schema version. Supported value: "2.0".
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request: in the JSON body, or in the query string for GET/DELETE
    /// and for requests whose body is a single field (that field's own
    /// `other` carries unknown body fields).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl AiParseDocumentOptions {
    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `description_element_types`.
    #[must_use]
    pub fn with_description_element_types(mut self, value: impl Into<String>) -> Self {
        self.description_element_types = Some(value.into());
        self
    }

    /// Set `image_output_path`.
    #[must_use]
    pub fn with_image_output_path(mut self, value: impl Into<String>) -> Self {
        self.image_output_path = Some(value.into());
        self
    }

    /// Set `page_range`.
    #[must_use]
    pub fn with_page_range(mut self, value: impl Into<String>) -> Self {
        self.page_range = Some(value.into());
        self
    }

    /// Set `version`.
    #[must_use]
    pub fn with_version(mut self, value: impl Into<String>) -> Self {
        self.version = Some(value.into());
        self
    }
}

/// A single page that failed to parse while the overall request succeeded.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct AiParseDocumentPageError {
    /// Message describing why the page failed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    /// 0-based index of the page that failed.
    #[serde(
        deserialize_with = "::community_databricks_core::serde_num::opt_i64",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub page_id: Option<i64>,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request: in the JSON body, or in the query string for GET/DELETE
    /// and for requests whose body is a single field (that field's own
    /// `other` carries unknown body fields).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl AiParseDocumentPageError {
    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `error_message`.
    #[must_use]
    pub fn with_error_message(mut self, value: impl Into<String>) -> Self {
        self.error_message = Some(value.into());
        self
    }

    /// Set `page_id`.
    #[must_use]
    pub fn with_page_id(mut self, value: i64) -> Self {
        self.page_id = Some(value);
        self
    }
}

/// `AiParseDocumentRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct AiParseDocumentRequest {
    /// The document to parse, given as a Unity Catalog volume path to the source
    /// file (the REST API accepts only a UC volume path, not inline binary
    /// data). Supported formats: PDF, DOCX, DOC, PPTX, PPT, JPG, JPEG, PNG,
    /// TIFF. Accepts up to 100 pages and 100 MB per document.
    #[serde(default)]
    pub content: String,
    /// Function options. Omitted fields fall back to their documented defaults.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub options: Option<AiParseDocumentOptions>,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request: in the JSON body, or in the query string for GET/DELETE
    /// and for requests whose body is a single field (that field's own
    /// `other` carries unknown body fields).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl AiParseDocumentRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(content: impl Into<String>) -> Self {
        Self {
            content: content.into(),
            ..Default::default()
        }
    }

    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `content`.
    #[must_use]
    pub fn with_content(mut self, value: impl Into<String>) -> Self {
        self.content = value.into();
        self
    }

    /// Set `options`.
    #[must_use]
    pub fn with_options(mut self, value: impl Into<AiParseDocumentOptions>) -> Self {
        self.options = Some(value.into());
        self
    }
}

/// `AiParseDocumentResponse`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct AiParseDocumentResponse {
    /// The parsed document as a JSON value, containing the extracted pages and
    /// elements.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub document: Option<::serde_json::Value>,
    /// Per-page partial-failure details; present when the request succeeds (2xx)
    /// but individual pages fail.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub error_status: Vec<AiParseDocumentPageError>,
    /// Additional metadata returned by AI Parse Document.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<AiParseDocumentResponseMetadata>,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request: in the JSON body, or in the query string for GET/DELETE
    /// and for requests whose body is a single field (that field's own
    /// `other` carries unknown body fields).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl AiParseDocumentResponse {
    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `document`.
    #[must_use]
    pub fn with_document(mut self, value: impl Into<::serde_json::Value>) -> Self {
        self.document = Some(value.into());
        self
    }

    /// Set `error_status`.
    #[must_use]
    pub fn with_error_status(mut self, value: impl Into<Vec<AiParseDocumentPageError>>) -> Self {
        self.error_status = value.into();
        self
    }

    /// Set `metadata`.
    #[must_use]
    pub fn with_metadata(mut self, value: impl Into<AiParseDocumentResponseMetadata>) -> Self {
        self.metadata = Some(value.into());
        self
    }
}

/// `AiParseDocumentResponseMetadata`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct AiParseDocumentResponseMetadata {
    /// Describes the source file; present only for file-path input.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_metadata: Option<AiParseDocumentFileMetadata>,
    /// Unique identifier for the parse request.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The resolved function version.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request: in the JSON body, or in the query string for GET/DELETE
    /// and for requests whose body is a single field (that field's own
    /// `other` carries unknown body fields).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl AiParseDocumentResponseMetadata {
    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `file_metadata`.
    #[must_use]
    pub fn with_file_metadata(mut self, value: impl Into<AiParseDocumentFileMetadata>) -> Self {
        self.file_metadata = Some(value.into());
        self
    }

    /// Set `id`.
    #[must_use]
    pub fn with_id(mut self, value: impl Into<String>) -> Self {
        self.id = Some(value.into());
        self
    }

    /// Set `version`.
    #[must_use]
    pub fn with_version(mut self, value: impl Into<String>) -> Self {
        self.version = Some(value.into());
        self
    }
}

/// Transform and enrich data with AI on Databricks.
#[derive(Debug, Clone)]
pub struct AiFunctionsApi {
    api: ApiClient,
}

impl AiFunctionsApi {
    /// Wrap an [`ApiClient`].
    #[must_use]
    pub fn new(api: ApiClient) -> Self {
        Self { api }
    }

    /// Classifies content according to a set of provided labels. For REST API
    /// requests, the default rate limit is 1,200 requests per minute per workspace.
    /// Contact your Databricks account team to request a higher limit.
    ///
    /// `POST /api/2.0/ai-functions/ai-classify`
    pub async fn ai_classify(
        &self,
        request: AiClassifyRequest,
    ) -> ::community_databricks_core::Result<AiClassifyResponse> {
        let path = String::from("/api/2.0/ai-functions/ai-classify");
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request)?;
        self.api.send::<AiClassifyResponse>(call).await
    }

    /// Extracts structured data from text and documents according to a provided
    /// schema. For REST API requests, the default rate limit is 120 requests per
    /// minute per workspace. Contact your Databricks account team to request a
    /// higher limit.
    ///
    /// `POST /api/2.0/ai-functions/ai-extract`
    pub async fn ai_extract(
        &self,
        request: AiExtractRequest,
    ) -> ::community_databricks_core::Result<AiExtractResponse> {
        let path = String::from("/api/2.0/ai-functions/ai-extract");
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request)?;
        self.api.send::<AiExtractResponse>(call).await
    }

    /// Parse structured content from unstructured documents.
    ///
    /// `POST /api/2.0/ai-functions/ai-parse-document`
    pub async fn ai_parse_document(
        &self,
        request: AiParseDocumentRequest,
    ) -> ::community_databricks_core::Result<AiParseDocumentResponse> {
        let path = String::from("/api/2.0/ai-functions/ai-parse-document");
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request)?;
        self.api.send::<AiParseDocumentResponse>(call).await
    }
}
