// Code generated by `cargo xtask codegen` from databricks-sdk-go v0.182.0 (OpenAPI 4648d66fa37e7683468dc92cc043c6aa7a34f301). DO NOT EDIT.

//! Databricks `domains` API: models and services.
//!
//! Generated from databricks-sdk-go v0.182.0; use it through the
//! [`databricks-sdk`](https://docs.rs/databricks-sdk) clients
//! (`databricks_sdk::service::domains`).

#![allow(
    clippy::all,
    clippy::pedantic,
    rustdoc::broken_intra_doc_links,
    rustdoc::invalid_html_tags,
    rustdoc::bare_urls,
    unused_imports
)]

use databricks_core::http::{Call, Method, path_param};
use databricks_core::paging::{self, Paged};
use databricks_core::{ApiClient, query, wait};

/// `CreateDomainRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct CreateDomainRequest {
    /// `domain`
    #[serde(default)]
    pub domain: Domain,
    /// Client-supplied resource ID for the new domain. If omitted, the server
    /// generates one.
    #[serde(skip)]
    pub domain_id: Option<String>,
}

impl CreateDomainRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(domain: impl Into<Domain>) -> Self {
        Self {
            domain: domain.into(),
            ..Default::default()
        }
    }

    /// Set `domain`.
    #[must_use]
    pub fn with_domain(mut self, value: impl Into<Domain>) -> Self {
        self.domain = value.into();
        self
    }

    /// Set `domain_id`.
    #[must_use]
    pub fn with_domain_id(mut self, value: impl Into<String>) -> Self {
        self.domain_id = Some(value.into());
        self
    }
}

/// `DeleteDomainRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct DeleteDomainRequest {
    /// When false (default), DeleteDomain is rejected with FAILED_PRECONDITION
    /// if the domain still has Glossary pages. When true, those pages are
    /// deleted first and then the domain is removed.
    #[serde(skip)]
    pub force: Option<bool>,
    /// Full resource name of the domain to delete. Format: `domains/{domain_id}`
    #[serde(skip)]
    pub name: String,
}

impl DeleteDomainRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `force`.
    #[must_use]
    pub fn with_force(mut self, value: bool) -> Self {
        self.force = Some(value);
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// `Domain`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct Domain {
    /// Principal IDs of the business owners (users, groups, or service
    /// principals).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub business_owner_ids: Vec<i64>,
    /// Timestamp when the domain was created.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub create_time: Option<String>,
    /// Full description (max 4096 chars)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Unique identifier for the domain. If omitted at Create, the server
    /// generates one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub domain_id: Option<String>,
    /// Whether to mark the domain as a draft. If omitted on Create, the server
    /// applies a default; the resolved value is returned in `effective_draft`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub draft: Option<bool>,
    /// Resolved draft state of the domain.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effective_draft: Option<bool>,
    /// Icon to display for the domain.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub icon: Option<DomainIcon>,
    /// Full resource name of the domain. The primary identifier for this
    /// resource. Format: `domains/{domain_id}` Identifies the domain on get,
    /// update, and delete. Not an input on create — to choose the id, set
    /// `CreateDomainRequest.domain_id`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Domain ID of the parent. If absent, this is a top-level domain. If
    /// present, this domain is a subdomain of the specified parent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_domain_id: Option<String>,
    /// Short description (max 280 chars)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subtitle: Option<String>,
    /// Governed tag key associated with this domain.
    #[serde(default)]
    pub tag_key: String,
    /// Principal IDs of the technical owners (users, groups, or service
    /// principals).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub technical_owner_ids: Vec<i64>,
    /// Timestamp when the domain was last updated.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub update_time: Option<String>,
}

impl Domain {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(tag_key: impl Into<String>) -> Self {
        Self {
            tag_key: tag_key.into(),
            ..Default::default()
        }
    }

    /// Set `business_owner_ids`.
    #[must_use]
    pub fn with_business_owner_ids(mut self, value: impl Into<Vec<i64>>) -> Self {
        self.business_owner_ids = value.into();
        self
    }

    /// Set `create_time`.
    #[must_use]
    pub fn with_create_time(mut self, value: impl Into<String>) -> Self {
        self.create_time = Some(value.into());
        self
    }

    /// Set `description`.
    #[must_use]
    pub fn with_description(mut self, value: impl Into<String>) -> Self {
        self.description = Some(value.into());
        self
    }

    /// Set `domain_id`.
    #[must_use]
    pub fn with_domain_id(mut self, value: impl Into<String>) -> Self {
        self.domain_id = Some(value.into());
        self
    }

    /// Set `draft`.
    #[must_use]
    pub fn with_draft(mut self, value: bool) -> Self {
        self.draft = Some(value);
        self
    }

    /// Set `effective_draft`.
    #[must_use]
    pub fn with_effective_draft(mut self, value: bool) -> Self {
        self.effective_draft = Some(value);
        self
    }

    /// Set `icon`.
    #[must_use]
    pub fn with_icon(mut self, value: impl Into<DomainIcon>) -> Self {
        self.icon = Some(value.into());
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = Some(value.into());
        self
    }

    /// Set `parent_domain_id`.
    #[must_use]
    pub fn with_parent_domain_id(mut self, value: impl Into<String>) -> Self {
        self.parent_domain_id = Some(value.into());
        self
    }

    /// Set `subtitle`.
    #[must_use]
    pub fn with_subtitle(mut self, value: impl Into<String>) -> Self {
        self.subtitle = Some(value.into());
        self
    }

    /// Set `tag_key`.
    #[must_use]
    pub fn with_tag_key(mut self, value: impl Into<String>) -> Self {
        self.tag_key = value.into();
        self
    }

    /// Set `technical_owner_ids`.
    #[must_use]
    pub fn with_technical_owner_ids(mut self, value: impl Into<Vec<i64>>) -> Self {
        self.technical_owner_ids = value.into();
        self
    }

    /// Set `update_time`.
    #[must_use]
    pub fn with_update_time(mut self, value: impl Into<String>) -> Self {
        self.update_time = Some(value.into());
        self
    }
}

/// Icon configuration for a domain.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct DomainIcon {
    /// Hex color code with # prefix (e.g., "#FF5733").
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    /// `name`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<DomainIconName>,
}

impl DomainIcon {
    /// Set `color`.
    #[must_use]
    pub fn with_color(mut self, value: impl Into<String>) -> Self {
        self.color = Some(value.into());
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<DomainIconName>) -> Self {
        self.name = Some(value.into());
        self
    }
}

::databricks_core::open_enum! {
    /// Available icon names for a domain.
    pub enum DomainIconName {
        /// `ADDRESS_BOOK`
        AddressBook => "ADDRESS_BOOK",
        /// `ALARM`
        Alarm => "ALARM",
        /// `ARROWS_IN`
        ArrowsIn => "ARROWS_IN",
        /// `ATOM`
        Atom => "ATOM",
        /// `BALLOON`
        Balloon => "BALLOON",
        /// `BANK`
        Bank => "BANK",
        /// `BARRICADE`
        Barricade => "BARRICADE",
        /// `BASKET`
        Basket => "BASKET",
        /// `BRIDGE`
        Bridge => "BRIDGE",
        /// `CACTUS`
        Cactus => "CACTUS",
        /// `CALL_BELL`
        CallBell => "CALL_BELL",
        /// `CARROT`
        Carrot => "CARROT",
        /// `CHART_PIE_SLICE`
        ChartPieSlice => "CHART_PIE_SLICE",
        /// `CITY`
        City => "CITY",
        /// `CLOUD`
        Cloud => "CLOUD",
        /// `COINS`
        Coins => "COINS",
        /// `COMPASS_ROSE`
        CompassRose => "COMPASS_ROSE",
        /// `CRANE_TOWER`
        CraneTower => "CRANE_TOWER",
        /// `CROWN`
        Crown => "CROWN",
        /// `CUBE_TRANSPARENT`
        CubeTransparent => "CUBE_TRANSPARENT",
        /// `FADERS`
        Faders => "FADERS",
        /// `FLAG_BANNER_FOLD`
        FlagBannerFold => "FLAG_BANNER_FOLD",
        /// `FLAG_CHECKERED`
        FlagCheckered => "FLAG_CHECKERED",
        /// `GAVEL`
        Gavel => "GAVEL",
        /// `HAMBURGER`
        Hamburger => "HAMBURGER",
        /// `HEAD_CIRCUIT`
        HeadCircuit => "HEAD_CIRCUIT",
        /// `HOURGLASS_HIGH`
        HourglassHigh => "HOURGLASS_HIGH",
        /// `INTERSECT_THREE`
        IntersectThree => "INTERSECT_THREE",
        /// `MICROSCOPE`
        Microscope => "MICROSCOPE",
        /// `MOON_STARS`
        MoonStars => "MOON_STARS",
        /// `PACKAGE`
        Package => "PACKAGE",
        /// `PARACHUTE`
        Parachute => "PARACHUTE",
        /// `PEPPER`
        Pepper => "PEPPER",
        /// `PIGGY_BANK`
        PiggyBank => "PIGGY_BANK",
        /// `PILL`
        Pill => "PILL",
        /// `PLANET`
        Planet => "PLANET",
        /// `PLANT`
        Plant => "PLANT",
        /// `PLUGS_CONNECTED`
        PlugsConnected => "PLUGS_CONNECTED",
        /// `POPCORN`
        Popcorn => "POPCORN",
        /// `PRESENTATION_CHART`
        PresentationChart => "PRESENTATION_CHART",
        /// `PUZZLE_PIECE`
        PuzzlePiece => "PUZZLE_PIECE",
        /// `RAINBOW`
        Rainbow => "RAINBOW",
        /// `RANKING`
        Ranking => "RANKING",
        /// `RECEIPT`
        Receipt => "RECEIPT",
        /// `ROCKET`
        Rocket => "ROCKET",
        /// `RULER`
        Ruler => "RULER",
        /// `SAILBOAT`
        Sailboat => "SAILBOAT",
        /// `SCALES`
        Scales => "SCALES",
        /// `SCAN_SMILEY`
        ScanSmiley => "SCAN_SMILEY",
        /// `SCROLL`
        Scroll => "SCROLL",
        /// `SHIELD_CHECKERED`
        ShieldCheckered => "SHIELD_CHECKERED",
        /// `SNEAKER`
        Sneaker => "SNEAKER",
        /// `SNOWFLAKE`
        Snowflake => "SNOWFLAKE",
        /// `SOLAR_ROOF`
        SolarRoof => "SOLAR_ROOF",
        /// `SPEEDOMETER`
        Speedometer => "SPEEDOMETER",
        /// `STAMP`
        Stamp => "STAMP",
        /// `STEPS`
        Steps => "STEPS",
        /// `STRATEGY`
        Strategy => "STRATEGY",
        /// `SWORD`
        Sword => "SWORD",
        /// `TELEVISION_SIMPLE`
        TelevisionSimple => "TELEVISION_SIMPLE",
        /// `TENT`
        Tent => "TENT",
        /// `TICKET`
        Ticket => "TICKET",
        /// `TRACTOR`
        Tractor => "TRACTOR",
        /// `TRAFFIC_CONE`
        TrafficCone => "TRAFFIC_CONE",
        /// `TRAIN`
        Train => "TRAIN",
        /// `TREE_EVERGREEN`
        TreeEvergreen => "TREE_EVERGREEN",
        /// `TREE_STRUCTURE`
        TreeStructure => "TREE_STRUCTURE",
        /// `TROLLEY_SUITCASE`
        TrolleySuitcase => "TROLLEY_SUITCASE",
        /// `TROPHY`
        Trophy => "TROPHY",
        /// `TRUCK_TRAILER`
        TruckTrailer => "TRUCK_TRAILER",
        /// `USERS_THREE`
        UsersThree => "USERS_THREE",
        /// `VECTOR_THREE`
        VectorThree => "VECTOR_THREE",
    }
}

/// `GetDomainRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GetDomainRequest {
    /// Full resource name of the domain to retrieve. Format:
    /// `domains/{domain_id}`
    #[serde(skip)]
    pub name: String,
}

impl GetDomainRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// `ListDomainsRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListDomainsRequest {
    /// `page_size`
    #[serde(skip)]
    pub page_size: Option<i64>,
    /// `page_token`
    #[serde(skip)]
    pub page_token: Option<String>,
    /// Filter by parent domain. - Absent: return all domains regardless of
    /// hierarchy. - Present: return only direct children of the specified
    /// domain.
    #[serde(skip)]
    pub parent_domain_id: Option<String>,
}

impl ListDomainsRequest {
    /// Set `page_size`.
    #[must_use]
    pub fn with_page_size(mut self, value: i64) -> Self {
        self.page_size = Some(value);
        self
    }

    /// Set `page_token`.
    #[must_use]
    pub fn with_page_token(mut self, value: impl Into<String>) -> Self {
        self.page_token = Some(value.into());
        self
    }

    /// Set `parent_domain_id`.
    #[must_use]
    pub fn with_parent_domain_id(mut self, value: impl Into<String>) -> Self {
        self.parent_domain_id = Some(value.into());
        self
    }
}

/// `ListDomainsResponse`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListDomainsResponse {
    /// `domains`
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub domains: Vec<Domain>,
    /// `next_page_token`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
}

impl ListDomainsResponse {
    /// Set `domains`.
    #[must_use]
    pub fn with_domains(mut self, value: impl Into<Vec<Domain>>) -> Self {
        self.domains = value.into();
        self
    }

    /// Set `next_page_token`.
    #[must_use]
    pub fn with_next_page_token(mut self, value: impl Into<String>) -> Self {
        self.next_page_token = Some(value.into());
        self
    }
}

/// `UpdateDomainRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct UpdateDomainRequest {
    /// `domain`
    #[serde(default)]
    pub domain: Domain,
    /// Full resource name of the domain. The primary identifier for this
    /// resource. Format: `domains/{domain_id}` Identifies the domain on get,
    /// update, and delete. Not an input on create — to choose the id, set
    /// `CreateDomainRequest.domain_id`.
    #[serde(skip)]
    pub name: String,
    /// The field mask must be a single string, with multiple fields separated by
    /// commas (no spaces). The field path is relative to the resource object,
    /// using a dot (`.`) to navigate sub-fields (e.g., `author.given_name`).
    /// Specification of elements in sequence or map fields is not allowed, as
    /// only the entire collection field can be specified. Field names must
    /// exactly match the resource field names.
    ///
    /// A field mask of `*` indicates full replacement. It’s recommended to
    /// always explicitly list the fields being updated and avoid using `*`
    /// wildcards, as it can lead to unintended results if the API changes in the
    /// future.
    #[serde(skip)]
    pub update_mask: String,
}

impl UpdateDomainRequest {
    /// Set `domain`.
    #[must_use]
    pub fn with_domain(mut self, value: impl Into<Domain>) -> Self {
        self.domain = value.into();
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }

    /// Set `update_mask`.
    #[must_use]
    pub fn with_update_mask(mut self, value: impl Into<String>) -> Self {
        self.update_mask = value.into();
        self
    }
}

/// Manage domains for organizing and discovering data assets.
#[derive(Debug, Clone)]
pub struct DomainsApi {
    api: ApiClient,
}

impl DomainsApi {
    /// Wrap an [`ApiClient`].
    #[must_use]
    pub fn new(api: ApiClient) -> Self {
        Self { api }
    }

    /// Create a domain. If `domain_id` is omitted, the server generates one.
    ///
    /// `POST /api/2.0/domains`
    pub async fn create_domain(
        &self,
        request: CreateDomainRequest,
    ) -> ::databricks_core::Result<Domain> {
        let path = String::from("/api/2.0/domains");
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.query(query::field("domain_id", &request.domain_id)?);
        call = call.json(&request.domain)?;
        self.api.send::<Domain>(call).await
    }

    /// Delete a domain. By default the request fails if the domain still has
    /// Glossary pages; set `force` to delete those pages along with the domain.
    ///
    /// `DELETE /api/2.0/{name}`
    pub async fn delete_domain(
        &self,
        request: DeleteDomainRequest,
    ) -> ::databricks_core::Result<()> {
        let path = format!("/api/2.0/{}", path_param(&request.name.to_string(), false));
        let mut call = Call::new(Method::DELETE, path).workspace();
        call = call.query(query::field("force", &request.force)?);
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Get a domain by resource name.
    ///
    /// Authorization: external callers must have the `MANAGE DISCOVERY` permission.
    ///
    /// `GET /api/2.0/{name}`
    pub async fn get_domain(&self, request: GetDomainRequest) -> ::databricks_core::Result<Domain> {
        let path = format!("/api/2.0/{}", path_param(&request.name.to_string(), false));
        let call = Call::new(Method::GET, path).workspace();
        self.api.send::<Domain>(call).await
    }

    /// One page of [`list_domains`](Self::list_domains).
    ///
    /// `GET /api/2.0/domains`
    pub async fn list_domains_page(
        &self,
        request: ListDomainsRequest,
    ) -> ::databricks_core::Result<ListDomainsResponse> {
        let path = String::from("/api/2.0/domains");
        let mut call = Call::new(Method::GET, path).workspace();
        call = call.query(query::field("page_size", &request.page_size)?);
        call = call.query(query::field("page_token", &request.page_token)?);
        call = call.query(query::field("parent_domain_id", &request.parent_domain_id)?);
        self.api.send::<ListDomainsResponse>(call).await
    }

    /// List domains in the account. Set `parent_domain_id` to return only the direct
    /// subdomains of a given domain.
    ///
    /// Authorization: external callers must have the `MANAGE DISCOVERY` permission;
    /// only domains the caller is authorized to read are returned.
    ///
    /// This method is generated by Databricks SDK Code Generator.
    ///
    /// `GET /api/2.0/domains`
    ///
    /// Returns a lazily paginated stream.
    #[must_use]
    pub fn list_domains(&self, request: ListDomainsRequest) -> Paged<'static, Domain> {
        let this = Clone::clone(self);
        paging::paginate(
            request,
            move |req: &ListDomainsRequest| {
                let this = Clone::clone(&this);
                let req = req.clone();
                async move { this.list_domains_page(req).await }
            },
            |req, resp| {
                let items = resp.domains;
                let more = paging::next_token(resp.next_page_token, |t| req.page_token = Some(t));
                (items, more)
            },
        )
    }

    /// Every page of [`list_domains`](Self::list_domains), collected.
    pub async fn list_domains_all(
        &self,
        request: ListDomainsRequest,
    ) -> ::databricks_core::Result<Vec<Domain>> {
        paging::collect(self.list_domains(request)).await
    }

    /// Update a domain. `update_mask` selects which fields to modify; the domain is
    /// identified by its resource `name`.
    ///
    /// `PATCH /api/2.0/{name}`
    pub async fn update_domain(
        &self,
        request: UpdateDomainRequest,
    ) -> ::databricks_core::Result<Domain> {
        let path = format!("/api/2.0/{}", path_param(&request.name.to_string(), false));
        let mut call = Call::new(Method::PATCH, path).workspace();
        call = call.query(query::field("update_mask", &request.update_mask)?);
        call = call.json(&request.domain)?;
        self.api.send::<Domain>(call).await
    }
}
