// Code generated by `cargo xtask codegen` from databricks-sdk-go v0.182.0 (OpenAPI 4648d66fa37e7683468dc92cc043c6aa7a34f301). DO NOT EDIT.

//! Databricks `knowledgeassistants` API: models and services.
//!
//! Generated from databricks-sdk-go v0.182.0; use it through the
//! [`databricks-sdk`](https://docs.rs/databricks-sdk) clients
//! (`databricks_sdk::service::knowledgeassistants`).

#![allow(
    clippy::all,
    clippy::pedantic,
    rustdoc::broken_intra_doc_links,
    rustdoc::invalid_html_tags,
    rustdoc::bare_urls,
    unused_imports
)]

use databricks_core::http::{Call, Method, path_param};
use databricks_core::paging::{self, Paged};
use databricks_core::{ApiClient, query, wait};

/// `CreateExampleRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct CreateExampleRequest {
    /// The example to create under the parent Knowledge Assistant.
    #[serde(default)]
    pub example: Example,
    /// Parent resource where this example will be created. Format:
    /// knowledge-assistants/{knowledge_assistant_id}
    #[serde(skip)]
    pub parent: String,
}

impl CreateExampleRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(example: impl Into<Example>, parent: impl Into<String>) -> Self {
        Self {
            example: example.into(),
            parent: parent.into(),
            ..Default::default()
        }
    }

    /// Set `example`.
    #[must_use]
    pub fn with_example(mut self, value: impl Into<Example>) -> Self {
        self.example = value.into();
        self
    }

    /// Set `parent`.
    #[must_use]
    pub fn with_parent(mut self, value: impl Into<String>) -> Self {
        self.parent = value.into();
        self
    }
}

/// `CreateKnowledgeAssistantRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct CreateKnowledgeAssistantRequest {
    /// The Knowledge Assistant to create.
    #[serde(default)]
    pub knowledge_assistant: KnowledgeAssistant,
}

impl CreateKnowledgeAssistantRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(knowledge_assistant: impl Into<KnowledgeAssistant>) -> Self {
        Self {
            knowledge_assistant: knowledge_assistant.into(),
            ..Default::default()
        }
    }

    /// Set `knowledge_assistant`.
    #[must_use]
    pub fn with_knowledge_assistant(mut self, value: impl Into<KnowledgeAssistant>) -> Self {
        self.knowledge_assistant = value.into();
        self
    }
}

/// `CreateKnowledgeSourceRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct CreateKnowledgeSourceRequest {
    /// `knowledge_source`
    #[serde(default)]
    pub knowledge_source: KnowledgeSource,
    /// Parent resource where this source will be created. Format:
    /// knowledge-assistants/{knowledge_assistant_id}
    #[serde(skip)]
    pub parent: String,
}

impl CreateKnowledgeSourceRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(knowledge_source: impl Into<KnowledgeSource>, parent: impl Into<String>) -> Self {
        Self {
            knowledge_source: knowledge_source.into(),
            parent: parent.into(),
            ..Default::default()
        }
    }

    /// Set `knowledge_source`.
    #[must_use]
    pub fn with_knowledge_source(mut self, value: impl Into<KnowledgeSource>) -> Self {
        self.knowledge_source = value.into();
        self
    }

    /// Set `parent`.
    #[must_use]
    pub fn with_parent(mut self, value: impl Into<String>) -> Self {
        self.parent = value.into();
        self
    }
}

/// `DeleteExampleRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct DeleteExampleRequest {
    /// The resource name of the example to delete. Format:
    /// knowledge-assistants/{knowledge_assistant_id}/examples/{example_id}
    #[serde(skip)]
    pub name: String,
}

impl DeleteExampleRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// `DeleteKnowledgeAssistantRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct DeleteKnowledgeAssistantRequest {
    /// The resource name of the knowledge assistant to be deleted. Format:
    /// knowledge-assistants/{knowledge_assistant_id}
    #[serde(skip)]
    pub name: String,
}

impl DeleteKnowledgeAssistantRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// `DeleteKnowledgeSourceRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct DeleteKnowledgeSourceRequest {
    /// The resource name of the Knowledge Source to delete. Format:
    /// knowledge-assistants/{knowledge_assistant_id}/knowledge-sources/{knowledge_source_id}
    #[serde(skip)]
    pub name: String,
}

impl DeleteKnowledgeSourceRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// An example associated with a Knowledge Assistant. Contains a question and
/// guidelines for how the assistant should respond.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct Example {
    /// Timestamp when this example was created.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub create_time: Option<String>,
    /// The universally unique identifier (UUID) of the example.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub example_id: Option<String>,
    /// Guidelines for answering the question. Optional — examples may be
    /// created with just a question; the front-end form does not require
    /// guidelines.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub guidelines: Vec<String>,
    /// Full resource name:
    /// knowledge-assistants/{knowledge_assistant_id}/examples/{example_id}
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The example question.
    #[serde(default)]
    pub question: String,
    /// Timestamp when this example was last updated.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub update_time: Option<String>,
}

impl Example {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(question: impl Into<String>) -> Self {
        Self {
            question: question.into(),
            ..Default::default()
        }
    }

    /// Set `create_time`.
    #[must_use]
    pub fn with_create_time(mut self, value: impl Into<String>) -> Self {
        self.create_time = Some(value.into());
        self
    }

    /// Set `example_id`.
    #[must_use]
    pub fn with_example_id(mut self, value: impl Into<String>) -> Self {
        self.example_id = Some(value.into());
        self
    }

    /// Set `guidelines`.
    #[must_use]
    pub fn with_guidelines(mut self, value: impl Into<Vec<String>>) -> Self {
        self.guidelines = value.into();
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = Some(value.into());
        self
    }

    /// Set `question`.
    #[must_use]
    pub fn with_question(mut self, value: impl Into<String>) -> Self {
        self.question = value.into();
        self
    }

    /// Set `update_time`.
    #[must_use]
    pub fn with_update_time(mut self, value: impl Into<String>) -> Self {
        self.update_time = Some(value.into());
        self
    }
}

/// FileTableSpec specifies a file table source configuration.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct FileTableSpec {
    /// The name of the column containing BINARY file content to be indexed.
    #[serde(default)]
    pub file_col: String,
    /// Full UC name of the table, in the format of
    /// {CATALOG}.{SCHEMA}.{TABLE_NAME}.
    #[serde(default)]
    pub table_name: String,
}

impl FileTableSpec {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(file_col: impl Into<String>, table_name: impl Into<String>) -> Self {
        Self {
            file_col: file_col.into(),
            table_name: table_name.into(),
            ..Default::default()
        }
    }

    /// Set `file_col`.
    #[must_use]
    pub fn with_file_col(mut self, value: impl Into<String>) -> Self {
        self.file_col = value.into();
        self
    }

    /// Set `table_name`.
    #[must_use]
    pub fn with_table_name(mut self, value: impl Into<String>) -> Self {
        self.table_name = value.into();
        self
    }
}

/// FilesSpec specifies a files source configuration.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct FilesSpec {
    /// A UC volume path that includes a list of files.
    #[serde(default)]
    pub path: String,
}

impl FilesSpec {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(path: impl Into<String>) -> Self {
        Self {
            path: path.into(),
            ..Default::default()
        }
    }

    /// Set `path`.
    #[must_use]
    pub fn with_path(mut self, value: impl Into<String>) -> Self {
        self.path = value.into();
        self
    }
}

/// `GetExampleRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GetExampleRequest {
    /// The resource name of the example. Format:
    /// knowledge-assistants/{knowledge_assistant_id}/examples/{example_id}
    #[serde(skip)]
    pub name: String,
}

impl GetExampleRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// `GetKnowledgeAssistantPermissionLevelsRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GetKnowledgeAssistantPermissionLevelsRequest {
    /// The knowledge assistant for which to get or manage permissions.
    #[serde(skip)]
    pub knowledge_assistant_id: String,
}

impl GetKnowledgeAssistantPermissionLevelsRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(knowledge_assistant_id: impl Into<String>) -> Self {
        Self {
            knowledge_assistant_id: knowledge_assistant_id.into(),
            ..Default::default()
        }
    }

    /// Set `knowledge_assistant_id`.
    #[must_use]
    pub fn with_knowledge_assistant_id(mut self, value: impl Into<String>) -> Self {
        self.knowledge_assistant_id = value.into();
        self
    }
}

/// `GetKnowledgeAssistantPermissionLevelsResponse`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GetKnowledgeAssistantPermissionLevelsResponse {
    /// Specific permission levels
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub permission_levels: Vec<KnowledgeAssistantPermissionsDescription>,
}

impl GetKnowledgeAssistantPermissionLevelsResponse {
    /// Set `permission_levels`.
    #[must_use]
    pub fn with_permission_levels(
        mut self,
        value: impl Into<Vec<KnowledgeAssistantPermissionsDescription>>,
    ) -> Self {
        self.permission_levels = value.into();
        self
    }
}

/// `GetKnowledgeAssistantPermissionsRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GetKnowledgeAssistantPermissionsRequest {
    /// The knowledge assistant for which to get or manage permissions.
    #[serde(skip)]
    pub knowledge_assistant_id: String,
}

impl GetKnowledgeAssistantPermissionsRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(knowledge_assistant_id: impl Into<String>) -> Self {
        Self {
            knowledge_assistant_id: knowledge_assistant_id.into(),
            ..Default::default()
        }
    }

    /// Set `knowledge_assistant_id`.
    #[must_use]
    pub fn with_knowledge_assistant_id(mut self, value: impl Into<String>) -> Self {
        self.knowledge_assistant_id = value.into();
        self
    }
}

/// `GetKnowledgeAssistantRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GetKnowledgeAssistantRequest {
    /// The resource name of the knowledge assistant. Format:
    /// knowledge-assistants/{knowledge_assistant_id}
    #[serde(skip)]
    pub name: String,
}

impl GetKnowledgeAssistantRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// `GetKnowledgeSourceRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GetKnowledgeSourceRequest {
    /// The resource name of the Knowledge Source. Format:
    /// knowledge-assistants/{knowledge_assistant_id}/knowledge-sources/{knowledge_source_id}
    #[serde(skip)]
    pub name: String,
}

impl GetKnowledgeSourceRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// IndexSpec specifies a vector search index source configuration.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct IndexSpec {
    /// The column that specifies a link or reference to where the information
    /// came from.
    #[serde(default)]
    pub doc_uri_col: String,
    /// Full UC name of the vector search index, in the format of
    /// {CATALOG}.{SCHEMA}.{INDEX_NAME}.
    #[serde(default)]
    pub index_name: String,
    /// The column that includes the document text for retrieval.
    #[serde(default)]
    pub text_col: String,
}

impl IndexSpec {
    /// Set `doc_uri_col`.
    #[must_use]
    pub fn with_doc_uri_col(mut self, value: impl Into<String>) -> Self {
        self.doc_uri_col = value.into();
        self
    }

    /// Set `index_name`.
    #[must_use]
    pub fn with_index_name(mut self, value: impl Into<String>) -> Self {
        self.index_name = value.into();
        self
    }

    /// Set `text_col`.
    #[must_use]
    pub fn with_text_col(mut self, value: impl Into<String>) -> Self {
        self.text_col = value.into();
        self
    }
}

/// Entity message that represents a knowledge assistant. Note: REQUIRED
/// annotations below represent create-time requirements. For updates, required
/// fields are determined by the update mask.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct KnowledgeAssistant {
    /// Creation timestamp.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub create_time: Option<String>,
    /// The creator of the Knowledge Assistant.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub creator: Option<String>,
    /// Description of what this agent can do (user-facing). Required when
    /// creating a Knowledge Assistant. When updating a Knowledge Assistant,
    /// optional unless included in update_mask.
    #[serde(default)]
    pub description: String,
    /// The display name of the Knowledge Assistant, unique at workspace level.
    /// Required when creating a Knowledge Assistant. When updating a Knowledge
    /// Assistant, optional unless included in update_mask.
    #[serde(default)]
    pub display_name: String,
    /// The name of the knowledge assistant agent endpoint.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub endpoint_name: Option<String>,
    /// Error details when the Knowledge Assistant is in FAILED state.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error_info: Option<String>,
    /// The MLflow experiment ID.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub experiment_id: Option<String>,
    /// Deprecated: use knowledge_assistant_id instead.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Additional global instructions on how the agent should generate answers.
    /// Optional on create and update. When updating a Knowledge Assistant,
    /// include this field in update_mask to modify it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub instructions: Option<String>,
    /// The resource name of the Knowledge Assistant. Format:
    /// knowledge-assistants/{knowledge_assistant_id}
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// State of the Knowledge Assistant. Not returned in List responses.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<KnowledgeAssistantState>,
}

impl KnowledgeAssistant {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(description: impl Into<String>, display_name: impl Into<String>) -> Self {
        Self {
            description: description.into(),
            display_name: display_name.into(),
            ..Default::default()
        }
    }

    /// Set `create_time`.
    #[must_use]
    pub fn with_create_time(mut self, value: impl Into<String>) -> Self {
        self.create_time = Some(value.into());
        self
    }

    /// Set `creator`.
    #[must_use]
    pub fn with_creator(mut self, value: impl Into<String>) -> Self {
        self.creator = Some(value.into());
        self
    }

    /// Set `description`.
    #[must_use]
    pub fn with_description(mut self, value: impl Into<String>) -> Self {
        self.description = value.into();
        self
    }

    /// Set `display_name`.
    #[must_use]
    pub fn with_display_name(mut self, value: impl Into<String>) -> Self {
        self.display_name = value.into();
        self
    }

    /// Set `endpoint_name`.
    #[must_use]
    pub fn with_endpoint_name(mut self, value: impl Into<String>) -> Self {
        self.endpoint_name = Some(value.into());
        self
    }

    /// Set `error_info`.
    #[must_use]
    pub fn with_error_info(mut self, value: impl Into<String>) -> Self {
        self.error_info = Some(value.into());
        self
    }

    /// Set `experiment_id`.
    #[must_use]
    pub fn with_experiment_id(mut self, value: impl Into<String>) -> Self {
        self.experiment_id = Some(value.into());
        self
    }

    /// Set `id`.
    #[must_use]
    pub fn with_id(mut self, value: impl Into<String>) -> Self {
        self.id = Some(value.into());
        self
    }

    /// Set `instructions`.
    #[must_use]
    pub fn with_instructions(mut self, value: impl Into<String>) -> Self {
        self.instructions = Some(value.into());
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = Some(value.into());
        self
    }

    /// Set `state`.
    #[must_use]
    pub fn with_state(mut self, value: impl Into<KnowledgeAssistantState>) -> Self {
        self.state = Some(value.into());
        self
    }
}

/// `KnowledgeAssistantAccessControlRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct KnowledgeAssistantAccessControlRequest {
    /// name of the group
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_name: Option<String>,
    /// `permission_level`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub permission_level: Option<KnowledgeAssistantPermissionLevel>,
    /// application ID of a service principal
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_principal_name: Option<String>,
    /// name of the user
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_name: Option<String>,
}

impl KnowledgeAssistantAccessControlRequest {
    /// Set `group_name`.
    #[must_use]
    pub fn with_group_name(mut self, value: impl Into<String>) -> Self {
        self.group_name = Some(value.into());
        self
    }

    /// Set `permission_level`.
    #[must_use]
    pub fn with_permission_level(
        mut self,
        value: impl Into<KnowledgeAssistantPermissionLevel>,
    ) -> Self {
        self.permission_level = Some(value.into());
        self
    }

    /// Set `service_principal_name`.
    #[must_use]
    pub fn with_service_principal_name(mut self, value: impl Into<String>) -> Self {
        self.service_principal_name = Some(value.into());
        self
    }

    /// Set `user_name`.
    #[must_use]
    pub fn with_user_name(mut self, value: impl Into<String>) -> Self {
        self.user_name = Some(value.into());
        self
    }
}

/// `KnowledgeAssistantAccessControlResponse`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct KnowledgeAssistantAccessControlResponse {
    /// All permissions.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub all_permissions: Vec<KnowledgeAssistantPermission>,
    /// Display name of the user or service principal.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// name of the group
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_name: Option<String>,
    /// Name of the service principal.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_principal_name: Option<String>,
    /// name of the user
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_name: Option<String>,
}

impl KnowledgeAssistantAccessControlResponse {
    /// Set `all_permissions`.
    #[must_use]
    pub fn with_all_permissions(
        mut self,
        value: impl Into<Vec<KnowledgeAssistantPermission>>,
    ) -> Self {
        self.all_permissions = value.into();
        self
    }

    /// Set `display_name`.
    #[must_use]
    pub fn with_display_name(mut self, value: impl Into<String>) -> Self {
        self.display_name = Some(value.into());
        self
    }

    /// Set `group_name`.
    #[must_use]
    pub fn with_group_name(mut self, value: impl Into<String>) -> Self {
        self.group_name = Some(value.into());
        self
    }

    /// Set `service_principal_name`.
    #[must_use]
    pub fn with_service_principal_name(mut self, value: impl Into<String>) -> Self {
        self.service_principal_name = Some(value.into());
        self
    }

    /// Set `user_name`.
    #[must_use]
    pub fn with_user_name(mut self, value: impl Into<String>) -> Self {
        self.user_name = Some(value.into());
        self
    }
}

/// `KnowledgeAssistantPermission`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct KnowledgeAssistantPermission {
    /// `inherited`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub inherited: Option<bool>,
    /// `inherited_from_object`
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub inherited_from_object: Vec<String>,
    /// `permission_level`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub permission_level: Option<KnowledgeAssistantPermissionLevel>,
}

impl KnowledgeAssistantPermission {
    /// Set `inherited`.
    #[must_use]
    pub fn with_inherited(mut self, value: bool) -> Self {
        self.inherited = Some(value);
        self
    }

    /// Set `inherited_from_object`.
    #[must_use]
    pub fn with_inherited_from_object(mut self, value: impl Into<Vec<String>>) -> Self {
        self.inherited_from_object = value.into();
        self
    }

    /// Set `permission_level`.
    #[must_use]
    pub fn with_permission_level(
        mut self,
        value: impl Into<KnowledgeAssistantPermissionLevel>,
    ) -> Self {
        self.permission_level = Some(value.into());
        self
    }
}

::databricks_core::open_enum! {
    /// Permission level
    pub enum KnowledgeAssistantPermissionLevel {
        /// `CAN_MANAGE`
        CanManage => "CAN_MANAGE",
        /// `CAN_QUERY`
        CanQuery => "CAN_QUERY",
    }
}

/// `KnowledgeAssistantPermissions`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct KnowledgeAssistantPermissions {
    /// `access_control_list`
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub access_control_list: Vec<KnowledgeAssistantAccessControlResponse>,
    /// `object_id`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object_id: Option<String>,
    /// `object_type`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object_type: Option<String>,
}

impl KnowledgeAssistantPermissions {
    /// Set `access_control_list`.
    #[must_use]
    pub fn with_access_control_list(
        mut self,
        value: impl Into<Vec<KnowledgeAssistantAccessControlResponse>>,
    ) -> Self {
        self.access_control_list = value.into();
        self
    }

    /// Set `object_id`.
    #[must_use]
    pub fn with_object_id(mut self, value: impl Into<String>) -> Self {
        self.object_id = Some(value.into());
        self
    }

    /// Set `object_type`.
    #[must_use]
    pub fn with_object_type(mut self, value: impl Into<String>) -> Self {
        self.object_type = Some(value.into());
        self
    }
}

/// `KnowledgeAssistantPermissionsDescription`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct KnowledgeAssistantPermissionsDescription {
    /// `description`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// `permission_level`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub permission_level: Option<KnowledgeAssistantPermissionLevel>,
}

impl KnowledgeAssistantPermissionsDescription {
    /// Set `description`.
    #[must_use]
    pub fn with_description(mut self, value: impl Into<String>) -> Self {
        self.description = Some(value.into());
        self
    }

    /// Set `permission_level`.
    #[must_use]
    pub fn with_permission_level(
        mut self,
        value: impl Into<KnowledgeAssistantPermissionLevel>,
    ) -> Self {
        self.permission_level = Some(value.into());
        self
    }
}

/// `KnowledgeAssistantPermissionsRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct KnowledgeAssistantPermissionsRequest {
    /// `access_control_list`
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub access_control_list: Vec<KnowledgeAssistantAccessControlRequest>,
    /// The knowledge assistant for which to get or manage permissions.
    #[serde(skip)]
    pub knowledge_assistant_id: String,
}

impl KnowledgeAssistantPermissionsRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(knowledge_assistant_id: impl Into<String>) -> Self {
        Self {
            knowledge_assistant_id: knowledge_assistant_id.into(),
            ..Default::default()
        }
    }

    /// Set `access_control_list`.
    #[must_use]
    pub fn with_access_control_list(
        mut self,
        value: impl Into<Vec<KnowledgeAssistantAccessControlRequest>>,
    ) -> Self {
        self.access_control_list = value.into();
        self
    }

    /// Set `knowledge_assistant_id`.
    #[must_use]
    pub fn with_knowledge_assistant_id(mut self, value: impl Into<String>) -> Self {
        self.knowledge_assistant_id = value.into();
        self
    }
}

::databricks_core::open_enum! {
    /// `KnowledgeAssistantState` values.
    pub enum KnowledgeAssistantState {
        /// `ACTIVE`
        Active => "ACTIVE",
        /// `CREATING`
        Creating => "CREATING",
        /// `FAILED`
        Failed => "FAILED",
    }
}

/// KnowledgeSource represents a source of knowledge for the KnowledgeAssistant.
/// Used in create/update requests and returned in Get/List responses. Note:
/// REQUIRED annotations below represent create-time requirements. For updates,
/// required fields are determined by the update mask.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct KnowledgeSource {
    /// Timestamp when this knowledge source was created.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub create_time: Option<String>,
    /// Description of the knowledge source. Required when creating a Knowledge
    /// Source. When updating a Knowledge Source, optional unless included in
    /// update_mask.
    #[serde(default)]
    pub description: String,
    /// Human-readable display name of the knowledge source. Required when
    /// creating a Knowledge Source. When updating a Knowledge Source, optional
    /// unless included in update_mask.
    #[serde(default)]
    pub display_name: String,
    /// `file_table`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_table: Option<FileTableSpec>,
    /// `files`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub files: Option<FilesSpec>,
    /// `id`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// `index`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub index: Option<IndexSpec>,
    /// Timestamp representing the cutoff before which content in this knowledge
    /// source is being ingested.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub knowledge_cutoff_time: Option<String>,
    /// Full resource name:
    /// knowledge-assistants/{knowledge_assistant_id}/knowledge-sources/{knowledge_source_id}
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The type of the source: "index", "files", or "file_table". Required when
    /// creating a Knowledge Source. When updating a Knowledge Source, this field
    /// is ignored.
    #[serde(default)]
    pub source_type: String,
    /// `state`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<KnowledgeSourceState>,
}

impl KnowledgeSource {
    /// Set `create_time`.
    #[must_use]
    pub fn with_create_time(mut self, value: impl Into<String>) -> Self {
        self.create_time = Some(value.into());
        self
    }

    /// Set `description`.
    #[must_use]
    pub fn with_description(mut self, value: impl Into<String>) -> Self {
        self.description = value.into();
        self
    }

    /// Set `display_name`.
    #[must_use]
    pub fn with_display_name(mut self, value: impl Into<String>) -> Self {
        self.display_name = value.into();
        self
    }

    /// Set `file_table`.
    #[must_use]
    pub fn with_file_table(mut self, value: impl Into<FileTableSpec>) -> Self {
        self.file_table = Some(value.into());
        self
    }

    /// Set `files`.
    #[must_use]
    pub fn with_files(mut self, value: impl Into<FilesSpec>) -> Self {
        self.files = Some(value.into());
        self
    }

    /// Set `id`.
    #[must_use]
    pub fn with_id(mut self, value: impl Into<String>) -> Self {
        self.id = Some(value.into());
        self
    }

    /// Set `index`.
    #[must_use]
    pub fn with_index(mut self, value: impl Into<IndexSpec>) -> Self {
        self.index = Some(value.into());
        self
    }

    /// Set `knowledge_cutoff_time`.
    #[must_use]
    pub fn with_knowledge_cutoff_time(mut self, value: impl Into<String>) -> Self {
        self.knowledge_cutoff_time = Some(value.into());
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = Some(value.into());
        self
    }

    /// Set `source_type`.
    #[must_use]
    pub fn with_source_type(mut self, value: impl Into<String>) -> Self {
        self.source_type = value.into();
        self
    }

    /// Set `state`.
    #[must_use]
    pub fn with_state(mut self, value: impl Into<KnowledgeSourceState>) -> Self {
        self.state = Some(value.into());
        self
    }
}

::databricks_core::open_enum! {
    /// `KnowledgeSourceState` values.
    pub enum KnowledgeSourceState {
        /// `FAILED_UPDATE`
        FailedUpdate => "FAILED_UPDATE",
        /// `UPDATED`
        Updated => "UPDATED",
        /// `UPDATING`
        Updating => "UPDATING",
    }
}

/// `ListExamplesRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListExamplesRequest {
    /// The maximum number of examples to return. If unspecified, at most 100
    /// examples will be returned. The maximum value is 100; values above 100
    /// will be coerced to 100.
    #[serde(skip)]
    pub page_size: Option<i64>,
    /// A page token, received from a previous `ListExamples` call. Provide this
    /// to retrieve the subsequent page. If unspecified, the first page will be
    /// returned.
    #[serde(skip)]
    pub page_token: Option<String>,
    /// Parent resource to list from. Format:
    /// knowledge-assistants/{knowledge_assistant_id}
    #[serde(skip)]
    pub parent: String,
}

impl ListExamplesRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(parent: impl Into<String>) -> Self {
        Self {
            parent: parent.into(),
            ..Default::default()
        }
    }

    /// Set `page_size`.
    #[must_use]
    pub fn with_page_size(mut self, value: i64) -> Self {
        self.page_size = Some(value);
        self
    }

    /// Set `page_token`.
    #[must_use]
    pub fn with_page_token(mut self, value: impl Into<String>) -> Self {
        self.page_token = Some(value.into());
        self
    }

    /// Set `parent`.
    #[must_use]
    pub fn with_parent(mut self, value: impl Into<String>) -> Self {
        self.parent = value.into();
        self
    }
}

/// A list of Knowledge Assistant examples.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListExamplesResponse {
    /// `examples`
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub examples: Vec<Example>,
    /// `next_page_token`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
}

impl ListExamplesResponse {
    /// Set `examples`.
    #[must_use]
    pub fn with_examples(mut self, value: impl Into<Vec<Example>>) -> Self {
        self.examples = value.into();
        self
    }

    /// Set `next_page_token`.
    #[must_use]
    pub fn with_next_page_token(mut self, value: impl Into<String>) -> Self {
        self.next_page_token = Some(value.into());
        self
    }
}

/// `ListKnowledgeAssistantsRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListKnowledgeAssistantsRequest {
    /// The maximum number of knowledge assistants to return. If unspecified, at
    /// most 100 knowledge assistants will be returned. The maximum value is 100;
    /// values above 100 will be coerced to 100.
    #[serde(skip)]
    pub page_size: Option<i64>,
    /// A page token, received from a previous `ListKnowledgeAssistants` call.
    /// Provide this to retrieve the subsequent page. If unspecified, the first
    /// page will be returned.
    #[serde(skip)]
    pub page_token: Option<String>,
}

impl ListKnowledgeAssistantsRequest {
    /// Set `page_size`.
    #[must_use]
    pub fn with_page_size(mut self, value: i64) -> Self {
        self.page_size = Some(value);
        self
    }

    /// Set `page_token`.
    #[must_use]
    pub fn with_page_token(mut self, value: impl Into<String>) -> Self {
        self.page_token = Some(value.into());
        self
    }
}

/// A list of Knowledge Assistants.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListKnowledgeAssistantsResponse {
    /// `knowledge_assistants`
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub knowledge_assistants: Vec<KnowledgeAssistant>,
    /// A token that can be sent as `page_token` to retrieve the next page. If
    /// this field is omitted, there are no subsequent pages.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
}

impl ListKnowledgeAssistantsResponse {
    /// Set `knowledge_assistants`.
    #[must_use]
    pub fn with_knowledge_assistants(mut self, value: impl Into<Vec<KnowledgeAssistant>>) -> Self {
        self.knowledge_assistants = value.into();
        self
    }

    /// Set `next_page_token`.
    #[must_use]
    pub fn with_next_page_token(mut self, value: impl Into<String>) -> Self {
        self.next_page_token = Some(value.into());
        self
    }
}

/// `ListKnowledgeSourcesRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListKnowledgeSourcesRequest {
    /// `page_size`
    #[serde(skip)]
    pub page_size: Option<i64>,
    /// `page_token`
    #[serde(skip)]
    pub page_token: Option<String>,
    /// Parent resource to list from. Format:
    /// knowledge-assistants/{knowledge_assistant_id}
    #[serde(skip)]
    pub parent: String,
}

impl ListKnowledgeSourcesRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(parent: impl Into<String>) -> Self {
        Self {
            parent: parent.into(),
            ..Default::default()
        }
    }

    /// Set `page_size`.
    #[must_use]
    pub fn with_page_size(mut self, value: i64) -> Self {
        self.page_size = Some(value);
        self
    }

    /// Set `page_token`.
    #[must_use]
    pub fn with_page_token(mut self, value: impl Into<String>) -> Self {
        self.page_token = Some(value.into());
        self
    }

    /// Set `parent`.
    #[must_use]
    pub fn with_parent(mut self, value: impl Into<String>) -> Self {
        self.parent = value.into();
        self
    }
}

/// `ListKnowledgeSourcesResponse`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListKnowledgeSourcesResponse {
    /// `knowledge_sources`
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub knowledge_sources: Vec<KnowledgeSource>,
    /// `next_page_token`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
}

impl ListKnowledgeSourcesResponse {
    /// Set `knowledge_sources`.
    #[must_use]
    pub fn with_knowledge_sources(mut self, value: impl Into<Vec<KnowledgeSource>>) -> Self {
        self.knowledge_sources = value.into();
        self
    }

    /// Set `next_page_token`.
    #[must_use]
    pub fn with_next_page_token(mut self, value: impl Into<String>) -> Self {
        self.next_page_token = Some(value.into());
        self
    }
}

/// `SyncKnowledgeSourcesRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct SyncKnowledgeSourcesRequest {
    /// The resource name of the Knowledge Assistant. Format:
    /// knowledge-assistants/{knowledge_assistant_id}
    #[serde(skip)]
    pub name: String,
}

impl SyncKnowledgeSourcesRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// `UpdateExampleRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct UpdateExampleRequest {
    /// `example`
    #[serde(default)]
    pub example: Example,
    /// The resource name of the example to update. Format:
    /// knowledge-assistants/{knowledge_assistant_id}/examples/{example_id}
    #[serde(skip)]
    pub name: String,
    /// Comma-delimited list of fields to update on the example. Allowed values:
    /// `question`, `guidelines`. Examples: - `question` - `question,guidelines`
    #[serde(skip)]
    pub update_mask: String,
}

impl UpdateExampleRequest {
    /// Set `example`.
    #[must_use]
    pub fn with_example(mut self, value: impl Into<Example>) -> Self {
        self.example = value.into();
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }

    /// Set `update_mask`.
    #[must_use]
    pub fn with_update_mask(mut self, value: impl Into<String>) -> Self {
        self.update_mask = value.into();
        self
    }
}

/// `UpdateKnowledgeAssistantRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct UpdateKnowledgeAssistantRequest {
    /// The Knowledge Assistant update payload. Only fields listed in update_mask
    /// are updated. REQUIRED annotations on Knowledge Assistant fields describe
    /// create-time requirements and do not mean all those fields are required
    /// for update.
    #[serde(default)]
    pub knowledge_assistant: KnowledgeAssistant,
    /// The resource name of the Knowledge Assistant. Format:
    /// knowledge-assistants/{knowledge_assistant_id}
    #[serde(skip)]
    pub name: String,
    /// Comma-delimited list of fields to update on the Knowledge Assistant.
    /// Allowed values: `display_name`, `description`, `instructions`. Examples:
    /// - `display_name` - `description,instructions`
    #[serde(skip)]
    pub update_mask: String,
}

impl UpdateKnowledgeAssistantRequest {
    /// Set `knowledge_assistant`.
    #[must_use]
    pub fn with_knowledge_assistant(mut self, value: impl Into<KnowledgeAssistant>) -> Self {
        self.knowledge_assistant = value.into();
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }

    /// Set `update_mask`.
    #[must_use]
    pub fn with_update_mask(mut self, value: impl Into<String>) -> Self {
        self.update_mask = value.into();
        self
    }
}

/// `UpdateKnowledgeSourceRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct UpdateKnowledgeSourceRequest {
    /// The Knowledge Source update payload. Only fields listed in update_mask
    /// are updated. REQUIRED annotations on Knowledge Source fields describe
    /// create-time requirements and do not mean all those fields are required
    /// for update.
    #[serde(default)]
    pub knowledge_source: KnowledgeSource,
    /// The resource name of the Knowledge Source to update. Format:
    /// knowledge-assistants/{knowledge_assistant_id}/knowledge-sources/{knowledge_source_id}
    #[serde(skip)]
    pub name: String,
    /// Comma-delimited list of fields to update on the Knowledge Source. Allowed
    /// values: `display_name`, `description`. Examples: - `display_name` -
    /// `display_name,description`
    #[serde(skip)]
    pub update_mask: String,
}

impl UpdateKnowledgeSourceRequest {
    /// Set `knowledge_source`.
    #[must_use]
    pub fn with_knowledge_source(mut self, value: impl Into<KnowledgeSource>) -> Self {
        self.knowledge_source = value.into();
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }

    /// Set `update_mask`.
    #[must_use]
    pub fn with_update_mask(mut self, value: impl Into<String>) -> Self {
        self.update_mask = value.into();
        self
    }
}

/// Manage Knowledge Assistants and related resources.
#[derive(Debug, Clone)]
pub struct KnowledgeAssistantsApi {
    api: ApiClient,
}

impl KnowledgeAssistantsApi {
    /// Wrap an [`ApiClient`].
    #[must_use]
    pub fn new(api: ApiClient) -> Self {
        Self { api }
    }

    /// Creates an example for a Knowledge Assistant.
    ///
    /// `POST /api/2.1/{parent}/examples`
    pub async fn create_example(
        &self,
        request: CreateExampleRequest,
    ) -> ::databricks_core::Result<Example> {
        let path = format!(
            "/api/2.1/{}/examples",
            path_param(&request.parent.to_string(), true)
        );
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request.example)?;
        self.api.send::<Example>(call).await
    }

    /// Creates a Knowledge Assistant.
    ///
    /// `POST /api/2.1/knowledge-assistants`
    pub async fn create_knowledge_assistant(
        &self,
        request: CreateKnowledgeAssistantRequest,
    ) -> ::databricks_core::Result<KnowledgeAssistant> {
        let path = String::from("/api/2.1/knowledge-assistants");
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request.knowledge_assistant)?;
        self.api.send::<KnowledgeAssistant>(call).await
    }

    /// Creates a Knowledge Source under a Knowledge Assistant.
    ///
    /// `POST /api/2.1/{parent}/knowledge-sources`
    pub async fn create_knowledge_source(
        &self,
        request: CreateKnowledgeSourceRequest,
    ) -> ::databricks_core::Result<KnowledgeSource> {
        let path = format!(
            "/api/2.1/{}/knowledge-sources",
            path_param(&request.parent.to_string(), true)
        );
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request.knowledge_source)?;
        self.api.send::<KnowledgeSource>(call).await
    }

    /// Deletes an example from a Knowledge Assistant.
    ///
    /// `DELETE /api/2.1/{name}`
    pub async fn delete_example(
        &self,
        request: DeleteExampleRequest,
    ) -> ::databricks_core::Result<()> {
        let path = format!("/api/2.1/{}", path_param(&request.name.to_string(), true));
        let call = Call::new(Method::DELETE, path).workspace();
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Deletes a Knowledge Assistant.
    ///
    /// `DELETE /api/2.1/{name}`
    pub async fn delete_knowledge_assistant(
        &self,
        request: DeleteKnowledgeAssistantRequest,
    ) -> ::databricks_core::Result<()> {
        let path = format!("/api/2.1/{}", path_param(&request.name.to_string(), true));
        let call = Call::new(Method::DELETE, path).workspace();
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Deletes a Knowledge Source.
    ///
    /// `DELETE /api/2.1/{name}`
    pub async fn delete_knowledge_source(
        &self,
        request: DeleteKnowledgeSourceRequest,
    ) -> ::databricks_core::Result<()> {
        let path = format!("/api/2.1/{}", path_param(&request.name.to_string(), true));
        let call = Call::new(Method::DELETE, path).workspace();
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Gets an example from a Knowledge Assistant.
    ///
    /// `GET /api/2.1/{name}`
    pub async fn get_example(
        &self,
        request: GetExampleRequest,
    ) -> ::databricks_core::Result<Example> {
        let path = format!("/api/2.1/{}", path_param(&request.name.to_string(), true));
        let call = Call::new(Method::GET, path).workspace();
        self.api.send::<Example>(call).await
    }

    /// Gets a Knowledge Assistant.
    ///
    /// `GET /api/2.1/{name}`
    pub async fn get_knowledge_assistant(
        &self,
        request: GetKnowledgeAssistantRequest,
    ) -> ::databricks_core::Result<KnowledgeAssistant> {
        let path = format!("/api/2.1/{}", path_param(&request.name.to_string(), true));
        let call = Call::new(Method::GET, path).workspace();
        self.api.send::<KnowledgeAssistant>(call).await
    }

    /// Gets a Knowledge Source.
    ///
    /// `GET /api/2.1/{name}`
    pub async fn get_knowledge_source(
        &self,
        request: GetKnowledgeSourceRequest,
    ) -> ::databricks_core::Result<KnowledgeSource> {
        let path = format!("/api/2.1/{}", path_param(&request.name.to_string(), true));
        let call = Call::new(Method::GET, path).workspace();
        self.api.send::<KnowledgeSource>(call).await
    }

    /// Gets the permission levels that a user can have on an object.
    ///
    /// `GET /api/2.0/permissions/knowledge-assistants/{knowledge_assistant_id}/permissionLevels`
    pub async fn get_permission_levels(
        &self,
        request: GetKnowledgeAssistantPermissionLevelsRequest,
    ) -> ::databricks_core::Result<GetKnowledgeAssistantPermissionLevelsResponse> {
        let path = format!(
            "/api/2.0/permissions/knowledge-assistants/{}/permissionLevels",
            path_param(&request.knowledge_assistant_id.to_string(), false)
        );
        let call = Call::new(Method::GET, path).workspace();
        self.api
            .send::<GetKnowledgeAssistantPermissionLevelsResponse>(call)
            .await
    }

    /// Gets the permissions of a knowledge assistant. Knowledge assistants can
    /// inherit permissions from their root object.
    ///
    /// `GET /api/2.0/permissions/knowledge-assistants/{knowledge_assistant_id}`
    pub async fn get_permissions(
        &self,
        request: GetKnowledgeAssistantPermissionsRequest,
    ) -> ::databricks_core::Result<KnowledgeAssistantPermissions> {
        let path = format!(
            "/api/2.0/permissions/knowledge-assistants/{}",
            path_param(&request.knowledge_assistant_id.to_string(), false)
        );
        let call = Call::new(Method::GET, path).workspace();
        self.api.send::<KnowledgeAssistantPermissions>(call).await
    }

    /// One page of [`list_examples`](Self::list_examples).
    ///
    /// `GET /api/2.1/{parent}/examples`
    pub async fn list_examples_page(
        &self,
        request: ListExamplesRequest,
    ) -> ::databricks_core::Result<ListExamplesResponse> {
        let path = format!(
            "/api/2.1/{}/examples",
            path_param(&request.parent.to_string(), true)
        );
        let mut call = Call::new(Method::GET, path).workspace();
        call = call.query(query::field("page_size", &request.page_size)?);
        call = call.query(query::field("page_token", &request.page_token)?);
        self.api.send::<ListExamplesResponse>(call).await
    }

    /// Lists examples under a Knowledge Assistant.
    ///
    /// This method is generated by Databricks SDK Code Generator.
    ///
    /// `GET /api/2.1/{parent}/examples`
    ///
    /// Returns a lazily paginated stream.
    #[must_use]
    pub fn list_examples(&self, request: ListExamplesRequest) -> Paged<'static, Example> {
        let this = Clone::clone(self);
        paging::paginate(
            request,
            move |req: &ListExamplesRequest| {
                let this = Clone::clone(&this);
                let req = req.clone();
                async move { this.list_examples_page(req).await }
            },
            |req, resp| {
                let items = resp.examples;
                let more = paging::next_token(resp.next_page_token, |t| req.page_token = Some(t));
                (items, more)
            },
        )
    }

    /// Every page of [`list_examples`](Self::list_examples), collected.
    pub async fn list_examples_all(
        &self,
        request: ListExamplesRequest,
    ) -> ::databricks_core::Result<Vec<Example>> {
        paging::collect(self.list_examples(request)).await
    }

    /// One page of [`list_knowledge_assistants`](Self::list_knowledge_assistants).
    ///
    /// `GET /api/2.1/knowledge-assistants`
    pub async fn list_knowledge_assistants_page(
        &self,
        request: ListKnowledgeAssistantsRequest,
    ) -> ::databricks_core::Result<ListKnowledgeAssistantsResponse> {
        let path = String::from("/api/2.1/knowledge-assistants");
        let mut call = Call::new(Method::GET, path).workspace();
        call = call.query(query::field("page_size", &request.page_size)?);
        call = call.query(query::field("page_token", &request.page_token)?);
        self.api.send::<ListKnowledgeAssistantsResponse>(call).await
    }

    /// List Knowledge Assistants
    ///
    /// This method is generated by Databricks SDK Code Generator.
    ///
    /// `GET /api/2.1/knowledge-assistants`
    ///
    /// Returns a lazily paginated stream.
    #[must_use]
    pub fn list_knowledge_assistants(
        &self,
        request: ListKnowledgeAssistantsRequest,
    ) -> Paged<'static, KnowledgeAssistant> {
        let this = Clone::clone(self);
        paging::paginate(
            request,
            move |req: &ListKnowledgeAssistantsRequest| {
                let this = Clone::clone(&this);
                let req = req.clone();
                async move { this.list_knowledge_assistants_page(req).await }
            },
            |req, resp| {
                let items = resp.knowledge_assistants;
                let more = paging::next_token(resp.next_page_token, |t| req.page_token = Some(t));
                (items, more)
            },
        )
    }

    /// Every page of [`list_knowledge_assistants`](Self::list_knowledge_assistants), collected.
    pub async fn list_knowledge_assistants_all(
        &self,
        request: ListKnowledgeAssistantsRequest,
    ) -> ::databricks_core::Result<Vec<KnowledgeAssistant>> {
        paging::collect(self.list_knowledge_assistants(request)).await
    }

    /// One page of [`list_knowledge_sources`](Self::list_knowledge_sources).
    ///
    /// `GET /api/2.1/{parent}/knowledge-sources`
    pub async fn list_knowledge_sources_page(
        &self,
        request: ListKnowledgeSourcesRequest,
    ) -> ::databricks_core::Result<ListKnowledgeSourcesResponse> {
        let path = format!(
            "/api/2.1/{}/knowledge-sources",
            path_param(&request.parent.to_string(), true)
        );
        let mut call = Call::new(Method::GET, path).workspace();
        call = call.query(query::field("page_size", &request.page_size)?);
        call = call.query(query::field("page_token", &request.page_token)?);
        self.api.send::<ListKnowledgeSourcesResponse>(call).await
    }

    /// Lists Knowledge Sources under a Knowledge Assistant.
    ///
    /// This method is generated by Databricks SDK Code Generator.
    ///
    /// `GET /api/2.1/{parent}/knowledge-sources`
    ///
    /// Returns a lazily paginated stream.
    #[must_use]
    pub fn list_knowledge_sources(
        &self,
        request: ListKnowledgeSourcesRequest,
    ) -> Paged<'static, KnowledgeSource> {
        let this = Clone::clone(self);
        paging::paginate(
            request,
            move |req: &ListKnowledgeSourcesRequest| {
                let this = Clone::clone(&this);
                let req = req.clone();
                async move { this.list_knowledge_sources_page(req).await }
            },
            |req, resp| {
                let items = resp.knowledge_sources;
                let more = paging::next_token(resp.next_page_token, |t| req.page_token = Some(t));
                (items, more)
            },
        )
    }

    /// Every page of [`list_knowledge_sources`](Self::list_knowledge_sources), collected.
    pub async fn list_knowledge_sources_all(
        &self,
        request: ListKnowledgeSourcesRequest,
    ) -> ::databricks_core::Result<Vec<KnowledgeSource>> {
        paging::collect(self.list_knowledge_sources(request)).await
    }

    /// Sets permissions on an object, replacing existing permissions if they exist.
    /// Deletes all direct permissions if none are specified. Objects can inherit
    /// permissions from their root object.
    ///
    /// `PUT /api/2.0/permissions/knowledge-assistants/{knowledge_assistant_id}`
    pub async fn set_permissions(
        &self,
        request: KnowledgeAssistantPermissionsRequest,
    ) -> ::databricks_core::Result<KnowledgeAssistantPermissions> {
        let path = format!(
            "/api/2.0/permissions/knowledge-assistants/{}",
            path_param(&request.knowledge_assistant_id.to_string(), false)
        );
        let mut call = Call::new(Method::PUT, path).workspace();
        call = call.json(&request)?;
        self.api.send::<KnowledgeAssistantPermissions>(call).await
    }

    /// Sync all non-index Knowledge Sources for a Knowledge Assistant (index sources
    /// do not require sync)
    ///
    /// `POST /api/2.1/{name}/knowledge-sources:sync`
    pub async fn sync_knowledge_sources(
        &self,
        request: SyncKnowledgeSourcesRequest,
    ) -> ::databricks_core::Result<()> {
        let path = format!(
            "/api/2.1/{}/knowledge-sources:sync",
            path_param(&request.name.to_string(), true)
        );
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request)?;
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Updates an example in a Knowledge Assistant.
    ///
    /// `PATCH /api/2.1/{name}`
    pub async fn update_example(
        &self,
        request: UpdateExampleRequest,
    ) -> ::databricks_core::Result<Example> {
        let path = format!("/api/2.1/{}", path_param(&request.name.to_string(), true));
        let mut call = Call::new(Method::PATCH, path).workspace();
        call = call.query(query::field("update_mask", &request.update_mask)?);
        call = call.json(&request.example)?;
        self.api.send::<Example>(call).await
    }

    /// Updates a Knowledge Assistant.
    ///
    /// `PATCH /api/2.1/{name}`
    pub async fn update_knowledge_assistant(
        &self,
        request: UpdateKnowledgeAssistantRequest,
    ) -> ::databricks_core::Result<KnowledgeAssistant> {
        let path = format!("/api/2.1/{}", path_param(&request.name.to_string(), true));
        let mut call = Call::new(Method::PATCH, path).workspace();
        call = call.query(query::field("update_mask", &request.update_mask)?);
        call = call.json(&request.knowledge_assistant)?;
        self.api.send::<KnowledgeAssistant>(call).await
    }

    /// Updates a Knowledge Source.
    ///
    /// `PATCH /api/2.1/{name}`
    pub async fn update_knowledge_source(
        &self,
        request: UpdateKnowledgeSourceRequest,
    ) -> ::databricks_core::Result<KnowledgeSource> {
        let path = format!("/api/2.1/{}", path_param(&request.name.to_string(), true));
        let mut call = Call::new(Method::PATCH, path).workspace();
        call = call.query(query::field("update_mask", &request.update_mask)?);
        call = call.json(&request.knowledge_source)?;
        self.api.send::<KnowledgeSource>(call).await
    }

    /// Updates the permissions on a knowledge assistant. Knowledge assistants can
    /// inherit permissions from their root object.
    ///
    /// `PATCH /api/2.0/permissions/knowledge-assistants/{knowledge_assistant_id}`
    pub async fn update_permissions(
        &self,
        request: KnowledgeAssistantPermissionsRequest,
    ) -> ::databricks_core::Result<KnowledgeAssistantPermissions> {
        let path = format!(
            "/api/2.0/permissions/knowledge-assistants/{}",
            path_param(&request.knowledge_assistant_id.to_string(), false)
        );
        let mut call = Call::new(Method::PATCH, path).workspace();
        call = call.json(&request)?;
        self.api.send::<KnowledgeAssistantPermissions>(call).await
    }
}
