[package]
name = "databricks-sdk"
description = "Unofficial Rust SDK for the Databricks Account and Workspace REST APIs"
readme = "../../README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["compute", "jobs", "provisioning"]
compute = []
jobs = []
provisioning = []

[dependencies]
bon.workspace = true
databricks-core.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
futures-util.workspace = true
pretty_assertions.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing-subscriber.workspace = true
wiremock.workspace = true

[lints]
workspace = true

[[example]]
name = "list_clusters"
required-features = ["compute"]

[[example]]
name = "run_job"
required-features = ["jobs"]

[[example]]
name = "list_workspaces"
required-features = ["provisioning"]
