//! `cargo xtask codegen` — generate `databricks-sdk` service modules from
//! `spec/ir.json`.
//!
//! `cargo xtask codegen --check` fails if the committed output is stale.

#![allow(clippy::too_many_lines)] // emitters are long, linear templates

mod docs;
mod emit_model;
mod emit_openapi;
mod emit_service;
mod ir;
mod model;
mod names;

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode};

use ir::{Ir, Service};

/// Identifiers generated modules import; a model type with one of these
/// names would shadow them.
const RESERVED: &[&str] = &["ApiClient", "Call", "Method", "Paged"];

/// Packages enabled by default.
const DEFAULT_FEATURES: &[&str] = &["catalog", "compute", "jobs", "provisioning"];

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    if let Some("codegen") = args.first().map(String::as_str) {
        let check = args.iter().any(|a| a == "--check");
        match codegen(&root(), check) {
            Ok(()) => ExitCode::SUCCESS,
            Err(e) => {
                eprintln!("codegen: {e}");
                ExitCode::FAILURE
            }
        }
    } else {
        eprintln!("usage: cargo xtask codegen [--check]");
        ExitCode::FAILURE
    }
}

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("workspace root")
        .to_path_buf()
}

fn codegen(root: &Path, check: bool) -> Result<(), String> {
    let ir: Ir = serde_json::from_slice(
        &std::fs::read(root.join("spec/ir.json")).map_err(|e| format!("spec/ir.json: {e}"))?,
    )
    .map_err(|e| format!("spec/ir.json: {e}"))?;
    let overrides: emit_service::Overrides = serde_json::from_slice(
        &std::fs::read(root.join("codegen/overrides.json"))
            .map_err(|e| format!("codegen/overrides.json: {e}"))?,
    )
    .map_err(|e| format!("codegen/overrides.json: {e}"))?;

    for (pkg, p) in &ir.packages {
        for t in &p.types {
            if RESERVED.contains(&t.name.as_str()) {
                return Err(format!("{pkg}.{} shadows a generated import", t.name));
            }
        }
    }

    let types = model::Types::new(&ir);
    let sdk = root.join("crates/databricks-sdk");
    let mut files: BTreeMap<PathBuf, String> = BTreeMap::new();
    let mut unsupported = Vec::new();
    let header = format!(
        "// Code generated by `cargo xtask codegen` from databricks-sdk-go {} (OpenAPI {}). DO NOT EDIT.\n",
        ir.source.go_sdk_version, ir.source.openapi_sha
    );

    // Services grouped by package; children by parent name.
    let mut by_pkg: BTreeMap<&str, Vec<&Service>> = BTreeMap::new();
    for s in &ir.services {
        by_pkg.entry(s.package.as_str()).or_default().push(s);
    }
    let deps = package_deps(&ir);
    let version = workspace_version(root)?;
    for (pkg, p) in &ir.packages {
        let dir = root.join("crates").join(model::crate_name(pkg));
        let has_ext = dir.join("src/ext.rs").exists();
        let mut out = String::new();
        out.push_str(&header);
        let _ = writeln!(
            out,
            "\n//! Databricks `{pkg}` API: models and services.\n//!\n//! Generated from databricks-sdk-go {}; use it through the\n//! [`databricks-sdk`](https://docs.rs/databricks-sdk) clients\n//! (`databricks_sdk::service::{pkg}`).\n\n#![allow(\n    clippy::all,\n    clippy::pedantic,\n    rustdoc::broken_intra_doc_links,\n    rustdoc::invalid_html_tags,\n    rustdoc::bare_urls,\n    unused_imports\n)]\n\nuse databricks_core::http::{{Call, Method, path_param}};\nuse databricks_core::paging::{{self, Paged}};\nuse databricks_core::{{ApiClient, query, wait}};\n",
            ir.source.go_sdk_version
        );
        if has_ext {
            out.push_str("\nmod ext;\n");
        }
        out.push_str(&emit_model::emit(&types, p));
        for s in by_pkg.get(pkg.as_str()).into_iter().flatten() {
            let children: Vec<&Service> = ir
                .services
                .iter()
                .filter(|c| c.parent == s.name && c.package == s.package && c.client == s.client)
                .collect();
            out.push_str(&emit_service::emit(
                &types,
                s,
                &children,
                &overrides,
                &mut unsupported,
            ));
        }
        files.insert(dir.join("src/lib.rs"), out);
        files.insert(
            dir.join("Cargo.toml"),
            package_manifest(pkg, &deps[pkg.as_str()], &version),
        );
    }

    // Umbrella: service re-exports, accessors, features and optional deps.
    let mut m = header.clone();
    m.push_str("\n//! Service packages, each a separate `databricks-sdk-<package>` crate\n//! enabled by the feature of the same name.\n\n");
    for pkg in ir.packages.keys() {
        let _ = writeln!(
            m,
            "#[cfg(feature = {pkg:?})]\n#[doc(inline)]\npub use {} as {pkg};",
            model::crate_ident(pkg)
        );
    }
    files.insert(sdk.join("src/service/mod.rs"), m);
    files.insert(sdk.join("src/accessors.rs"), accessors(&ir, &header));
    let cargo_path = sdk.join("Cargo.toml");
    let cargo = std::fs::read_to_string(&cargo_path).map_err(|e| e.to_string())?;
    files.insert(cargo_path, umbrella_manifest(&ir, &cargo, &version)?);

    // OpenAPI documents.
    let specs = emit_openapi::emit(&ir, &types);
    for (name, doc) in [("account", &specs.account), ("workspace", &specs.workspace)] {
        let mut text = serde_json::to_string_pretty(doc).map_err(|e| e.to_string())?;
        text.push('\n');
        files.insert(root.join(format!("spec/openapi/{name}.json")), text);
    }

    // Report.
    let mut report = String::from(
        "# Generated surface\n\nProduced by `cargo xtask codegen` from `spec/ir.json`. DO NOT EDIT.\n\n",
    );
    let _ = writeln!(
        report,
        "Source: databricks-sdk-go {} (OpenAPI `{}`).\n",
        ir.source.go_sdk_version, ir.source.openapi_sha
    );
    let nmeth: usize = ir
        .services
        .iter()
        .map(|s| s.methods.as_deref().unwrap_or_default().len())
        .sum();
    let ntypes: usize = ir.packages.values().map(|p| p.types.len()).sum();
    let _ = writeln!(
        report,
        "- {} packages, {} services, {} operations ({} generated), {} types.\n",
        ir.packages.len(),
        ir.services.len(),
        nmeth,
        nmeth - unsupported.len(),
        ntypes
    );
    report.push_str("## Not generated (binary or streaming payloads)\n\n");
    for u in &unsupported {
        let _ = writeln!(report, "- `{u}`");
    }
    report.push_str(
        "\n## OpenAPI path collisions (moved to `x-databricks-shared-path-operations`)\n\n",
    );
    for d in &specs.duplicates {
        let _ = writeln!(report, "- {d}");
    }
    report.push_str("\n## Skipped services\n\n");
    for s in &ir.skipped {
        let _ = writeln!(report, "- {s}");
    }
    report.push_str("\n## Hand-written overrides\n\n");
    for (k, v) in &overrides {
        let _ = writeln!(
            report,
            "- `{k}` is generated as `{v}`; see `src/ext.rs` in the package crate."
        );
    }
    files.insert(root.join("spec/GENERATED.md"), report);

    // rustfmt the Rust files in memory, then write or compare.
    let mut stale = Vec::new();
    for (path, content) in &files {
        let content = if path.extension().is_some_and(|e| e == "rs") {
            rustfmt(content)?
        } else {
            content.clone()
        };
        let current = std::fs::read_to_string(path).unwrap_or_default();
        if current == content {
            continue;
        }
        if check {
            stale.push(path.display().to_string());
        } else {
            std::fs::create_dir_all(path.parent().expect("parent")).map_err(|e| e.to_string())?;
            std::fs::write(path, content).map_err(|e| format!("{}: {e}", path.display()))?;
        }
    }
    // Remove crates for packages that no longer exist.
    let keep: BTreeSet<String> = ir.packages.keys().map(|p| model::crate_name(p)).collect();
    if let Ok(entries) = std::fs::read_dir(root.join("crates")) {
        for e in entries.flatten() {
            let name = e.file_name().to_string_lossy().to_string();
            let generated = std::fs::read_to_string(e.path().join("Cargo.toml"))
                .is_ok_and(|c| c.starts_with(GENERATED_MANIFEST));
            if generated && !keep.contains(&name) {
                if check {
                    stale.push(e.path().display().to_string());
                } else {
                    std::fs::remove_dir_all(e.path()).map_err(|e| e.to_string())?;
                }
            }
        }
    }
    if check && !stale.is_empty() {
        return Err(format!(
            "generated code is stale; run `cargo xtask codegen`:\n  {}",
            stale.join("\n  ")
        ));
    }
    eprintln!(
        "codegen: {} packages, {} services, {} operations, {} unsupported",
        ir.packages.len(),
        ir.services.len(),
        nmeth,
        unsupported.len()
    );
    Ok(())
}

fn accessors(ir: &Ir, header: &str) -> String {
    let mut out = String::from(header);
    out.push_str("\n//! Service accessors on the clients.\n\n#![allow(\n    clippy::doc_markdown,\n    clippy::too_many_lines,\n    rustdoc::broken_intra_doc_links,\n    rustdoc::invalid_html_tags,\n    rustdoc::bare_urls\n)]\n\nuse crate::{AccountClient, WorkspaceClient};\n\n");
    for (client, ty) in [
        ("workspace", "WorkspaceClient"),
        ("account", "AccountClient"),
    ] {
        let _ = writeln!(out, "impl {ty} {{");
        for s in ir
            .services
            .iter()
            .filter(|s| s.client == client && s.parent.is_empty())
        {
            let summary = docs::summary(&s.doc);
            let doc = if summary.is_empty() {
                format!("{} API.", s.name)
            } else {
                summary
            };
            out.push_str(&docs::render(&doc, "    "));
            let _ = writeln!(
                out,
                "    #[cfg(feature = {:?})]\n    #[must_use]\n    pub fn {}(&self) -> crate::service::{}::{} {{\n        crate::service::{}::{}::new(self.api_client().clone())\n    }}\n",
                s.package,
                names::method_ident(&s.accessor),
                s.package,
                emit_service::struct_name(s),
                s.package,
                emit_service::struct_name(s)
            );
        }
        out.push_str("}\n\n");
    }
    out
}

const GENERATED_MANIFEST: &str = "# Generated by `cargo xtask codegen`. DO NOT EDIT.";

/// Packages each package's types reference.
fn package_deps(ir: &Ir) -> BTreeMap<&str, BTreeSet<&str>> {
    let mut deps: BTreeMap<&str, BTreeSet<&str>> = BTreeMap::new();
    for (pkg, p) in &ir.packages {
        let set = deps.entry(pkg).or_default();
        for t in &p.types {
            let refs = t
                .fields
                .as_deref()
                .unwrap_or_default()
                .iter()
                .map(|f| &f.ty)
                .chain(t.alias.as_ref());
            for ty in refs {
                let mut r = Some(ty);
                while let Some(x) = r {
                    if x.kind == "ref" && x.pkg != *pkg && !x.pkg.is_empty() {
                        set.insert(x.pkg.as_str());
                    }
                    r = x.elem.as_deref();
                }
            }
        }
    }
    deps
}

/// `[workspace.package] version`, so path dependencies track release-plz
/// bumps.
fn workspace_version(root: &Path) -> Result<String, String> {
    let toml = std::fs::read_to_string(root.join("Cargo.toml")).map_err(|e| e.to_string())?;
    let section = toml
        .split("[workspace.package]")
        .nth(1)
        .ok_or("Cargo.toml has no [workspace.package]")?;
    section
        .lines()
        .take_while(|l| !l.starts_with('['))
        .find_map(|l| {
            let l = l.trim();
            l.strip_prefix("version")
                .map(str::trim_start)
                .and_then(|r| r.strip_prefix('='))
                .map(|r| r.trim().trim_matches('"').to_owned())
        })
        .ok_or_else(|| "no version in [workspace.package]".to_owned())
}

fn package_manifest(pkg: &str, deps: &BTreeSet<&str>, version: &str) -> String {
    let mut out = format!(
        "{GENERATED_MANIFEST}\n\n[package]\nname = {:?}\ndescription = \"Databricks `{pkg}` API models and services (generated; use via databricks-sdk)\"\nreadme = \"../../README.md\"\nversion.workspace = true\nedition.workspace = true\nrust-version.workspace = true\nlicense.workspace = true\nrepository.workspace = true\nauthors.workspace = true\nkeywords.workspace = true\ncategories.workspace = true\n\n[dependencies]\ndatabricks-core.workspace = true\nserde.workspace = true\nserde_json.workspace = true\n",
        model::crate_name(pkg)
    );
    for d in deps {
        let _ = writeln!(
            out,
            "{} = {{ path = \"../{}\", version = \"{version}\" }}",
            model::crate_name(d),
            model::crate_name(d)
        );
    }
    out.push_str("\n[lints]\nworkspace = true\n");
    out
}

/// Replace the generated feature and dependency blocks in the umbrella
/// Cargo.toml.
fn umbrella_manifest(ir: &Ir, cargo: &str, version: &str) -> Result<String, String> {
    fn replace(src: &str, name: &str, body: &str) -> Result<String, String> {
        let begin = format!("# BEGIN GENERATED {name}");
        let end = format!("# END GENERATED {name}");
        let (Some(b), Some(e)) = (src.find(&begin), src.find(&end)) else {
            return Err(format!(
                "crates/databricks-sdk/Cargo.toml lacks `{begin}`/`{end}`"
            ));
        };
        Ok(format!("{}{begin}\n{body}{}", &src[..b], &src[e..]))
    }
    let mut features = String::new();
    let defaults: Vec<String> = DEFAULT_FEATURES.iter().map(|f| format!("{f:?}")).collect();
    let _ = writeln!(features, "default = [{}]", defaults.join(", "));
    let all: Vec<String> = ir.packages.keys().map(|k| format!("{k:?}")).collect();
    let _ = writeln!(features, "full = [{}]", all.join(", "));
    let mut deps = String::new();
    for pkg in ir.packages.keys() {
        let _ = writeln!(features, "{pkg} = [\"dep:{}\"]", model::crate_name(pkg));
        let _ = writeln!(
            deps,
            "{} = {{ path = \"../{}\", version = \"{version}\", optional = true }}",
            model::crate_name(pkg),
            model::crate_name(pkg)
        );
    }
    let cargo = replace(cargo, "FEATURES", &features)?;
    replace(&cargo, "DEPENDENCIES", &deps)
}

fn rustfmt(src: &str) -> Result<String, String> {
    use std::io::Write as _;
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2024", "--emit", "stdout"])
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .map_err(|e| format!("rustfmt: {e}"))?;
    child
        .stdin
        .take()
        .expect("stdin")
        .write_all(src.as_bytes())
        .map_err(|e| e.to_string())?;
    let out = child.wait_with_output().map_err(|e| e.to_string())?;
    if !out.status.success() {
        let dump = std::env::temp_dir().join("xtask-rustfmt-failed.rs");
        let _ = std::fs::write(&dump, src);
        return Err(format!(
            "rustfmt failed (input saved to {}):\n{}",
            dump.display(),
            String::from_utf8_lossy(&out.stderr)
        ));
    }
    String::from_utf8(out.stdout).map_err(|e| e.to_string())
}
