// Code generated by `cargo xtask codegen` from databricks-sdk-go v0.182.0 (OpenAPI 4648d66fa37e7683468dc92cc043c6aa7a34f301). DO NOT EDIT.

//! Databricks `agentbricks` API: models and services.
//!
//! Generated from databricks-sdk-go v0.182.0; use it through the
//! [`databricks-sdk`](https://docs.rs/databricks-sdk) clients
//! (`databricks_sdk::service::agentbricks`).

#![allow(
    clippy::all,
    clippy::pedantic,
    rustdoc::broken_intra_doc_links,
    rustdoc::invalid_html_tags,
    rustdoc::bare_urls,
    unused_imports
)]

use databricks_core::http::{Call, Method, path_param};
use databricks_core::paging::{self, Paged};
use databricks_core::{ApiClient, query, wait};

/// `CancelCustomLlmOptimizationRunRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct CancelCustomLlmOptimizationRunRequest {
    /// `id`
    #[serde(skip)]
    pub id: String,
}

impl CancelCustomLlmOptimizationRunRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            ..Default::default()
        }
    }

    /// Set `id`.
    #[must_use]
    pub fn with_id(mut self, value: impl Into<String>) -> Self {
        self.id = value.into();
        self
    }
}

/// `CreateCustomLlmRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct CreateCustomLlmRequest {
    /// This will soon be deprecated!! Optional: UC path for agent artifacts. If
    /// you are using a dataset that you only have read permissions, please
    /// provide a destination path where you have write permissions. Please
    /// provide this in catalog.schema format.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_artifact_path: Option<String>,
    /// Datasets used for training and evaluating the model, not for inference.
    /// Currently, only 1 dataset is accepted.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub datasets: Vec<Dataset>,
    /// Guidelines for the custom LLM to adhere to
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub guidelines: Vec<String>,
    /// Instructions for the custom LLM to follow
    #[serde(default)]
    pub instructions: String,
    /// Name of the custom LLM. Only alphanumeric characters and dashes allowed.
    #[serde(default)]
    pub name: String,
}

impl CreateCustomLlmRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(instructions: impl Into<String>, name: impl Into<String>) -> Self {
        Self {
            instructions: instructions.into(),
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `agent_artifact_path`.
    #[must_use]
    pub fn with_agent_artifact_path(mut self, value: impl Into<String>) -> Self {
        self.agent_artifact_path = Some(value.into());
        self
    }

    /// Set `datasets`.
    #[must_use]
    pub fn with_datasets(mut self, value: impl Into<Vec<Dataset>>) -> Self {
        self.datasets = value.into();
        self
    }

    /// Set `guidelines`.
    #[must_use]
    pub fn with_guidelines(mut self, value: impl Into<Vec<String>>) -> Self {
        self.guidelines = value.into();
        self
    }

    /// Set `instructions`.
    #[must_use]
    pub fn with_instructions(mut self, value: impl Into<String>) -> Self {
        self.instructions = value.into();
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// `CustomLlm`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct CustomLlm {
    /// `agent_artifact_path`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_artifact_path: Option<String>,
    /// Creation timestamp of the custom LLM
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub creation_time: Option<String>,
    /// Creator of the custom LLM
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub creator: Option<String>,
    /// Datasets used for training and evaluating the model, not for inference
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub datasets: Vec<Dataset>,
    /// Name of the endpoint that will be used to serve the custom LLM
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub endpoint_name: Option<String>,
    /// Guidelines for the custom LLM to adhere to
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub guidelines: Vec<String>,
    /// `id`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Instructions for the custom LLM to follow
    #[serde(default)]
    pub instructions: String,
    /// Name of the custom LLM
    #[serde(default)]
    pub name: String,
    /// If optimization is kicked off, tracks the state of the custom LLM
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub optimization_state: Option<State>,
}

impl CustomLlm {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(instructions: impl Into<String>, name: impl Into<String>) -> Self {
        Self {
            instructions: instructions.into(),
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `agent_artifact_path`.
    #[must_use]
    pub fn with_agent_artifact_path(mut self, value: impl Into<String>) -> Self {
        self.agent_artifact_path = Some(value.into());
        self
    }

    /// Set `creation_time`.
    #[must_use]
    pub fn with_creation_time(mut self, value: impl Into<String>) -> Self {
        self.creation_time = Some(value.into());
        self
    }

    /// Set `creator`.
    #[must_use]
    pub fn with_creator(mut self, value: impl Into<String>) -> Self {
        self.creator = Some(value.into());
        self
    }

    /// Set `datasets`.
    #[must_use]
    pub fn with_datasets(mut self, value: impl Into<Vec<Dataset>>) -> Self {
        self.datasets = value.into();
        self
    }

    /// Set `endpoint_name`.
    #[must_use]
    pub fn with_endpoint_name(mut self, value: impl Into<String>) -> Self {
        self.endpoint_name = Some(value.into());
        self
    }

    /// Set `guidelines`.
    #[must_use]
    pub fn with_guidelines(mut self, value: impl Into<Vec<String>>) -> Self {
        self.guidelines = value.into();
        self
    }

    /// Set `id`.
    #[must_use]
    pub fn with_id(mut self, value: impl Into<String>) -> Self {
        self.id = Some(value.into());
        self
    }

    /// Set `instructions`.
    #[must_use]
    pub fn with_instructions(mut self, value: impl Into<String>) -> Self {
        self.instructions = value.into();
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }

    /// Set `optimization_state`.
    #[must_use]
    pub fn with_optimization_state(mut self, value: impl Into<State>) -> Self {
        self.optimization_state = Some(value.into());
        self
    }
}

/// `Dataset`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct Dataset {
    /// `table`
    #[serde(default)]
    pub table: Table,
}

impl Dataset {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(table: impl Into<Table>) -> Self {
        Self {
            table: table.into(),
            ..Default::default()
        }
    }

    /// Set `table`.
    #[must_use]
    pub fn with_table(mut self, value: impl Into<Table>) -> Self {
        self.table = value.into();
        self
    }
}

/// `DeleteCustomLlmRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct DeleteCustomLlmRequest {
    /// The id of the custom llm
    #[serde(skip)]
    pub id: String,
}

impl DeleteCustomLlmRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            ..Default::default()
        }
    }

    /// Set `id`.
    #[must_use]
    pub fn with_id(mut self, value: impl Into<String>) -> Self {
        self.id = value.into();
        self
    }
}

/// `GetCustomLlmRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GetCustomLlmRequest {
    /// The id of the custom llm
    #[serde(skip)]
    pub id: String,
}

impl GetCustomLlmRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            ..Default::default()
        }
    }

    /// Set `id`.
    #[must_use]
    pub fn with_id(mut self, value: impl Into<String>) -> Self {
        self.id = value.into();
        self
    }
}

/// `StartCustomLlmOptimizationRunRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct StartCustomLlmOptimizationRunRequest {
    /// The Id of the tile.
    #[serde(skip)]
    pub id: String,
}

impl StartCustomLlmOptimizationRunRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            ..Default::default()
        }
    }

    /// Set `id`.
    #[must_use]
    pub fn with_id(mut self, value: impl Into<String>) -> Self {
        self.id = value.into();
        self
    }
}

::databricks_core::open_enum! {
    /// States of Custom LLM optimization lifecycle.
    pub enum State {
        /// `CANCELLED`
        Cancelled => "CANCELLED",
        /// `COMPLETED`
        Completed => "COMPLETED",
        /// `CREATED`
        Created => "CREATED",
        /// `FAILED`
        Failed => "FAILED",
        /// `PENDING`
        Pending => "PENDING",
        /// `RUNNING`
        Running => "RUNNING",
    }
}

/// `Table`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct Table {
    /// Name of the request column
    #[serde(default)]
    pub request_col: String,
    /// Optional: Name of the response column if the data is labeled
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub response_col: Option<String>,
    /// Full UC table path in catalog.schema.table_name format
    #[serde(default)]
    pub table_path: String,
}

impl Table {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(request_col: impl Into<String>, table_path: impl Into<String>) -> Self {
        Self {
            request_col: request_col.into(),
            table_path: table_path.into(),
            ..Default::default()
        }
    }

    /// Set `request_col`.
    #[must_use]
    pub fn with_request_col(mut self, value: impl Into<String>) -> Self {
        self.request_col = value.into();
        self
    }

    /// Set `response_col`.
    #[must_use]
    pub fn with_response_col(mut self, value: impl Into<String>) -> Self {
        self.response_col = Some(value.into());
        self
    }

    /// Set `table_path`.
    #[must_use]
    pub fn with_table_path(mut self, value: impl Into<String>) -> Self {
        self.table_path = value.into();
        self
    }
}

/// `UpdateCustomLlmRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct UpdateCustomLlmRequest {
    /// The CustomLlm containing the fields which should be updated.
    #[serde(default)]
    pub custom_llm: CustomLlm,
    /// The id of the custom llm
    #[serde(skip)]
    pub id: String,
    /// The list of the CustomLlm fields to update. These should correspond to
    /// the values (or lack thereof) present in `custom_llm`.
    ///
    /// The field mask must be a single string, with multiple fields separated by
    /// commas (no spaces). The field path is relative to the resource object,
    /// using a dot (`.`) to navigate sub-fields (e.g., `author.given_name`).
    /// Specification of elements in sequence or map fields is not allowed, as
    /// only the entire collection field can be specified. Field names must
    /// exactly match the resource field names.
    ///
    /// A field mask of `*` indicates full replacement. It’s recommended to
    /// always explicitly list the fields being updated and avoid using `*`
    /// wildcards, as it can lead to unintended results if the API changes in the
    /// future.
    #[serde(default)]
    pub update_mask: String,
}

impl UpdateCustomLlmRequest {
    /// Set `custom_llm`.
    #[must_use]
    pub fn with_custom_llm(mut self, value: impl Into<CustomLlm>) -> Self {
        self.custom_llm = value.into();
        self
    }

    /// Set `id`.
    #[must_use]
    pub fn with_id(mut self, value: impl Into<String>) -> Self {
        self.id = value.into();
        self
    }

    /// Set `update_mask`.
    #[must_use]
    pub fn with_update_mask(mut self, value: impl Into<String>) -> Self {
        self.update_mask = value.into();
        self
    }
}

/// The Custom LLMs service manages state and powers the UI for the Custom
/// LLM product.
#[derive(Debug, Clone)]
pub struct AgentBricksApi {
    api: ApiClient,
}

impl AgentBricksApi {
    /// Wrap an [`ApiClient`].
    #[must_use]
    pub fn new(api: ApiClient) -> Self {
        Self { api }
    }

    /// Cancel a Custom LLM Optimization Run.
    ///
    /// `POST /api/2.0/custom-llms/{id}/optimize/cancel`
    pub async fn cancel_optimize(
        &self,
        request: CancelCustomLlmOptimizationRunRequest,
    ) -> ::databricks_core::Result<()> {
        let path = format!(
            "/api/2.0/custom-llms/{}/optimize/cancel",
            path_param(&request.id.to_string(), false)
        );
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request)?;
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Create a Custom LLM.
    ///
    /// `POST /api/2.0/custom-llms`
    pub async fn create_custom_llm(
        &self,
        request: CreateCustomLlmRequest,
    ) -> ::databricks_core::Result<CustomLlm> {
        let path = String::from("/api/2.0/custom-llms");
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request)?;
        self.api.send::<CustomLlm>(call).await
    }

    /// Delete a Custom LLM.
    ///
    /// `DELETE /api/2.0/custom-llms/{id}`
    pub async fn delete_custom_llm(
        &self,
        request: DeleteCustomLlmRequest,
    ) -> ::databricks_core::Result<()> {
        let path = format!(
            "/api/2.0/custom-llms/{}",
            path_param(&request.id.to_string(), false)
        );
        let call = Call::new(Method::DELETE, path).workspace();
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Get a Custom LLM.
    ///
    /// `GET /api/2.0/custom-llms/{id}`
    pub async fn get_custom_llm(
        &self,
        request: GetCustomLlmRequest,
    ) -> ::databricks_core::Result<CustomLlm> {
        let path = format!(
            "/api/2.0/custom-llms/{}",
            path_param(&request.id.to_string(), false)
        );
        let call = Call::new(Method::GET, path).workspace();
        self.api.send::<CustomLlm>(call).await
    }

    /// Start a Custom LLM Optimization Run.
    ///
    /// `POST /api/2.0/custom-llms/{id}/optimize`
    pub async fn start_optimize(
        &self,
        request: StartCustomLlmOptimizationRunRequest,
    ) -> ::databricks_core::Result<CustomLlm> {
        let path = format!(
            "/api/2.0/custom-llms/{}/optimize",
            path_param(&request.id.to_string(), false)
        );
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request)?;
        self.api.send::<CustomLlm>(call).await
    }

    /// Update a Custom LLM.
    ///
    /// `PATCH /api/2.0/custom-llms/{id}`
    pub async fn update_custom_llm(
        &self,
        request: UpdateCustomLlmRequest,
    ) -> ::databricks_core::Result<CustomLlm> {
        let path = format!(
            "/api/2.0/custom-llms/{}",
            path_param(&request.id.to_string(), false)
        );
        let mut call = Call::new(Method::PATCH, path).workspace();
        call = call.json(&request)?;
        self.api.send::<CustomLlm>(call).await
    }
}
