// Code generated by `cargo xtask codegen` from databricks-sdk-go v0.182.0 (OpenAPI 4648d66fa37e7683468dc92cc043c6aa7a34f301). DO NOT EDIT.

//! Service accessors on the clients.

#![allow(
    clippy::doc_markdown,
    clippy::too_many_lines,
    rustdoc::broken_intra_doc_links,
    rustdoc::invalid_html_tags,
    rustdoc::bare_urls
)]

use crate::{AccountClient, WorkspaceClient};

impl WorkspaceClient {
    /// Rule based Access Control for Databricks Resources.
    #[cfg(feature = "iam")]
    #[must_use]
    pub fn access_control(&self) -> crate::service::iam::AccessControlApi {
        crate::service::iam::AccessControlApi::new(self.api_client().clone())
    }

    /// These APIs manage access rules on resources in an account. Currently,
    /// only grant rules are supported. A grant rule specifies a role assigned to
    /// a set of principals. A list of rules attached to a resource is called a
    /// rule set. A workspace must belong to an account for these APIs to work
    #[cfg(feature = "iam")]
    #[must_use]
    pub fn account_access_control_proxy(
        &self,
    ) -> crate::service::iam::AccountAccessControlProxyApi {
        crate::service::iam::AccountAccessControlProxyApi::new(self.api_client().clone())
    }

    /// The Custom LLMs service manages state and powers the UI for the Custom
    /// LLM product.
    #[cfg(feature = "agentbricks")]
    #[must_use]
    pub fn agent_bricks(&self) -> crate::service::agentbricks::AgentBricksApi {
        crate::service::agentbricks::AgentBricksApi::new(self.api_client().clone())
    }

    /// Transform and enrich data with AI on Databricks.
    #[cfg(feature = "aifunctions")]
    #[must_use]
    pub fn ai_functions(&self) -> crate::service::aifunctions::AiFunctionsApi {
        crate::service::aifunctions::AiFunctionsApi::new(self.api_client().clone())
    }

    /// Govern AI workloads in Unity Catalog. This API manages the Unity Catalog
    /// securables that bring centralized access control, lineage, and auditing
    /// to AI-serving entities: model services (governed access to foundation
    /// models and external LLMs), model provider services (governed resources
    /// for external model providers), and MCP services (governed Model Context
    /// Protocol servers).
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn ai_gateway(&self) -> crate::service::catalog::AiGatewayApi {
        crate::service::catalog::AiGatewayApi::new(self.api_client().clone())
    }

    /// **AI Search Endpoint**: Represents the compute resources to host AI
    /// Search indexes. AIP-conformant replacement for the legacy
    /// VectorSearchEndpoints API; functionally equivalent.
    #[cfg(feature = "aisearch")]
    #[must_use]
    pub fn ai_search(&self) -> crate::service::aisearch::AiSearchApi {
        crate::service::aisearch::AiSearchApi::new(self.api_client().clone())
    }

    /// The alerts API can be used to perform CRUD operations on alerts. An alert
    /// is a Databricks SQL object that periodically runs a query, evaluates a
    /// condition of its result, and notifies one or more users and/or
    /// notification destinations if the condition was met. Alerts can be
    /// scheduled using the `sql_task` type of the Jobs API, e.g.
    /// :method:jobs/create.
    #[cfg(feature = "sql")]
    #[must_use]
    pub fn alerts(&self) -> crate::service::sql::AlertsApi {
        crate::service::sql::AlertsApi::new(self.api_client().clone())
    }

    /// The alerts API can be used to perform CRUD operations on alerts. An alert
    /// is a Databricks SQL object that periodically runs a query, evaluates a
    /// condition of its result, and notifies one or more users and/or
    /// notification destinations if the condition was met. Alerts can be
    /// scheduled using the `sql_task` type of the Jobs API, e.g.
    /// :method:jobs/create.
    #[cfg(feature = "sql")]
    #[must_use]
    pub fn alerts_legacy(&self) -> crate::service::sql::AlertsLegacyApi {
        crate::service::sql::AlertsLegacyApi::new(self.api_client().clone())
    }

    /// New version of SQL Alerts
    #[cfg(feature = "sql")]
    #[must_use]
    pub fn alerts_v2(&self) -> crate::service::sql::AlertsV2Api {
        crate::service::sql::AlertsV2Api::new(self.api_client().clone())
    }

    /// Apps run directly on a customer's Databricks instance, integrate with
    /// their data, use and extend Databricks services, and enable users to
    /// interact through single sign-on.
    #[cfg(feature = "apps")]
    #[must_use]
    pub fn apps(&self) -> crate::service::apps::AppsApi {
        crate::service::apps::AppsApi::new(self.api_client().clone())
    }

    /// Apps Settings manage the settings for the Apps service on a customer's
    /// Databricks instance.
    #[cfg(feature = "apps")]
    #[must_use]
    pub fn apps_settings(&self) -> crate::service::apps::AppsSettingsApi {
        crate::service::apps::AppsSettingsApi::new(self.api_client().clone())
    }

    /// In Databricks Runtime 13.3 and above, you can add libraries and init
    /// scripts to the `allowlist` in UC so that users can use these artifacts on
    /// compute configured with shared access mode.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn artifact_allowlists(&self) -> crate::service::catalog::ArtifactAllowlistsApi {
        crate::service::catalog::ArtifactAllowlistsApi::new(self.api_client().clone())
    }

    /// Service for managing bundle deployment metadata.
    #[cfg(feature = "bundledeployments")]
    #[must_use]
    pub fn bundle_deployments(&self) -> crate::service::bundledeployments::BundleDeploymentsApi {
        crate::service::bundledeployments::BundleDeploymentsApi::new(self.api_client().clone())
    }

    /// A catalog is the first layer of Unity Catalog’s three-level namespace.
    /// It’s used to organize your data assets. Users can see all catalogs on
    /// which they have been assigned the USE_CATALOG data permission.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn catalogs(&self) -> crate::service::catalog::CatalogsApi {
        crate::service::catalog::CatalogsApi::new(self.api_client().clone())
    }

    /// Clean Room Asset Revisions denote new versions of uploaded assets (e.g.
    /// notebooks) in the clean room.
    #[cfg(feature = "cleanrooms")]
    #[must_use]
    pub fn clean_room_asset_revisions(
        &self,
    ) -> crate::service::cleanrooms::CleanRoomAssetRevisionsApi {
        crate::service::cleanrooms::CleanRoomAssetRevisionsApi::new(self.api_client().clone())
    }

    /// Clean room assets are data and code objects — Tables, volumes, and
    /// notebooks that are shared with the clean room.
    #[cfg(feature = "cleanrooms")]
    #[must_use]
    pub fn clean_room_assets(&self) -> crate::service::cleanrooms::CleanRoomAssetsApi {
        crate::service::cleanrooms::CleanRoomAssetsApi::new(self.api_client().clone())
    }

    /// Clean room auto-approval rules automatically create an approval on your
    /// behalf when an asset (e.g. notebook) meeting specific criteria is shared
    /// in a clean room.
    #[cfg(feature = "cleanrooms")]
    #[must_use]
    pub fn clean_room_auto_approval_rules(
        &self,
    ) -> crate::service::cleanrooms::CleanRoomAutoApprovalRulesApi {
        crate::service::cleanrooms::CleanRoomAutoApprovalRulesApi::new(self.api_client().clone())
    }

    /// Clean room task runs are the executions of notebooks and JAR analyses in
    /// a clean room.
    #[cfg(feature = "cleanrooms")]
    #[must_use]
    pub fn clean_room_task_runs(&self) -> crate::service::cleanrooms::CleanRoomTaskRunsApi {
        crate::service::cleanrooms::CleanRoomTaskRunsApi::new(self.api_client().clone())
    }

    /// A clean room uses Delta Sharing and serverless compute to provide a
    /// secure and privacy-protecting environment where multiple parties can work
    /// together on sensitive enterprise data without direct access to each
    /// other's data.
    #[cfg(feature = "cleanrooms")]
    #[must_use]
    pub fn clean_rooms(&self) -> crate::service::cleanrooms::CleanRoomsApi {
        crate::service::cleanrooms::CleanRoomsApi::new(self.api_client().clone())
    }

    /// You can use cluster policies to control users' ability to configure
    /// clusters based on a set of rules. These rules specify which attributes or
    /// attribute values can be used during cluster creation. Cluster policies
    /// have ACLs that limit their use to specific users and groups.
    #[cfg(feature = "compute")]
    #[must_use]
    pub fn cluster_policies(&self) -> crate::service::compute::ClusterPoliciesApi {
        crate::service::compute::ClusterPoliciesApi::new(self.api_client().clone())
    }

    /// The Clusters API allows you to create, start, edit, list, terminate, and
    /// delete clusters.
    #[cfg(feature = "compute")]
    #[must_use]
    pub fn clusters(&self) -> crate::service::compute::ClustersApi {
        crate::service::compute::ClustersApi::new(self.api_client().clone())
    }

    /// This API allows execution of Python, Scala, SQL, or R commands on running
    /// Databricks Clusters. This API only supports (classic) all-purpose
    /// clusters. Serverless compute is not supported.
    #[cfg(feature = "compute")]
    #[must_use]
    pub fn command_execution(&self) -> crate::service::compute::CommandExecutionApi {
        crate::service::compute::CommandExecutionApi::new(self.api_client().clone())
    }

    /// A connection represents an external data source for use within
    /// Databricks.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn connections(&self) -> crate::service::catalog::ConnectionsApi {
        crate::service::catalog::ConnectionsApi::new(self.api_client().clone())
    }

    /// Fulfillments are entities that allow consumers to preview installations.
    #[cfg(feature = "marketplace")]
    #[must_use]
    pub fn consumer_fulfillments(&self) -> crate::service::marketplace::ConsumerFulfillmentsApi {
        crate::service::marketplace::ConsumerFulfillmentsApi::new(self.api_client().clone())
    }

    /// Installations are entities that allow consumers to interact with
    /// Databricks Marketplace listings.
    #[cfg(feature = "marketplace")]
    #[must_use]
    pub fn consumer_installations(&self) -> crate::service::marketplace::ConsumerInstallationsApi {
        crate::service::marketplace::ConsumerInstallationsApi::new(self.api_client().clone())
    }

    /// Listings are the core entities in the Marketplace. They represent the
    /// products that are available for consumption.
    #[cfg(feature = "marketplace")]
    #[must_use]
    pub fn consumer_listings(&self) -> crate::service::marketplace::ConsumerListingsApi {
        crate::service::marketplace::ConsumerListingsApi::new(self.api_client().clone())
    }

    /// Personalization Requests allow customers to interact with the
    /// individualized Marketplace listing flow.
    #[cfg(feature = "marketplace")]
    #[must_use]
    pub fn consumer_personalization_requests(
        &self,
    ) -> crate::service::marketplace::ConsumerPersonalizationRequestsApi {
        crate::service::marketplace::ConsumerPersonalizationRequestsApi::new(
            self.api_client().clone(),
        )
    }

    /// Providers are the entities that publish listings to the Marketplace.
    #[cfg(feature = "marketplace")]
    #[must_use]
    pub fn consumer_providers(&self) -> crate::service::marketplace::ConsumerProvidersApi {
        crate::service::marketplace::ConsumerProvidersApi::new(self.api_client().clone())
    }

    /// A credential represents an authentication and authorization mechanism for
    /// accessing services on your cloud tenant. Each credential is subject to
    /// Unity Catalog access-control policies that control which users and groups
    /// can access the credential.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn credentials(&self) -> crate::service::catalog::CredentialsApi {
        crate::service::catalog::CredentialsApi::new(self.api_client().clone())
    }

    /// Credentials manager interacts with with Identity Providers to to perform
    /// token exchanges using stored credentials and refresh tokens.
    #[cfg(feature = "settings")]
    #[must_use]
    pub fn credentials_manager(&self) -> crate::service::settings::CredentialsManagerApi {
        crate::service::settings::CredentialsManagerApi::new(self.api_client().clone())
    }

    /// This API allows retrieving information about currently authenticated user
    /// or service principal.
    #[cfg(feature = "iam")]
    #[must_use]
    pub fn current_user(&self) -> crate::service::iam::CurrentUserApi {
        crate::service::iam::CurrentUserApi::new(self.api_client().clone())
    }

    /// This is an evolving API that facilitates the addition and removal of
    /// widgets from existing dashboards within the Databricks Workspace. Data
    /// structures may change over time.
    #[cfg(feature = "sql")]
    #[must_use]
    pub fn dashboard_widgets(&self) -> crate::service::sql::DashboardWidgetsApi {
        crate::service::sql::DashboardWidgetsApi::new(self.api_client().clone())
    }

    /// In general, there is little need to modify dashboards using the API.
    /// However, it can be useful to use dashboard objects to look-up a
    /// collection of related query IDs. The API can also be used to duplicate
    /// multiple dashboards at once since you can get a dashboard definition with
    /// a GET request and then POST it to create a new one. Dashboards can be
    /// scheduled using the `sql_task` type of the Jobs API, e.g.
    /// :method:jobs/create.
    #[cfg(feature = "sql")]
    #[must_use]
    pub fn dashboards(&self) -> crate::service::sql::DashboardsApi {
        crate::service::sql::DashboardsApi::new(self.api_client().clone())
    }

    /// Manage data classification for Unity Catalog catalogs. Data
    /// classification automatically identifies and tags sensitive data (PII) in
    /// Unity Catalog tables. Each catalog can have at most one configuration
    /// resource that controls scanning behavior and auto-tagging rules.
    #[cfg(feature = "dataclassification")]
    #[must_use]
    pub fn data_classification(&self) -> crate::service::dataclassification::DataClassificationApi {
        crate::service::dataclassification::DataClassificationApi::new(self.api_client().clone())
    }

    /// Manage the data quality of Unity Catalog objects (currently support
    /// `schema` and `table`)
    #[cfg(feature = "dataquality")]
    #[must_use]
    pub fn data_quality(&self) -> crate::service::dataquality::DataQualityApi {
        crate::service::dataquality::DataQualityApi::new(self.api_client().clone())
    }

    /// This API is provided to assist you in making new query objects. When
    /// creating a query object, you may optionally specify a `data_source_id`
    /// for the SQL warehouse against which it will run. If you don't already
    /// know the `data_source_id` for your desired SQL warehouse, this API will
    /// help you find it.
    #[cfg(feature = "sql")]
    #[must_use]
    pub fn data_sources(&self) -> crate::service::sql::DataSourcesApi {
        crate::service::sql::DataSourcesApi::new(self.api_client().clone())
    }

    /// Database Instances provide access to a database via REST API or direct
    /// SQL.
    #[cfg(feature = "database")]
    #[must_use]
    pub fn database(&self) -> crate::service::database::DatabaseApi {
        crate::service::database::DatabaseApi::new(self.api_client().clone())
    }

    /// DBFS API makes it simple to interact with various data sources without
    /// having to include a users credentials every time to read a file.
    #[cfg(feature = "files")]
    #[must_use]
    pub fn dbfs(&self) -> crate::service::files::DbfsApi {
        crate::service::files::DbfsApi::new(self.api_client().clone())
    }

    /// The SQL Permissions API is similar to the endpoints of the
    /// :method:permissions/set. However, this exposes only one endpoint, which
    /// gets the Access Control List for a given object. You cannot modify any
    /// permissions using this API.
    #[cfg(feature = "sql")]
    #[must_use]
    pub fn dbsql_permissions(&self) -> crate::service::sql::DbsqlPermissionsApi {
        crate::service::sql::DbsqlPermissionsApi::new(self.api_client().clone())
    }

    /// Manage domains for organizing and discovering data assets.
    #[cfg(feature = "domains")]
    #[must_use]
    pub fn domains(&self) -> crate::service::domains::DomainsApi {
        crate::service::domains::DomainsApi::new(self.api_client().clone())
    }

    /// Tags are attributes that include keys and optional values that you can
    /// use to organize and categorize entities in Unity Catalog. Entity tagging
    /// is supported on catalogs, schemas, tables (including views), columns, and
    /// volumes. With these APIs, you can create, update, delete, and list tag
    /// assignments across Unity Catalog entities.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn entity_tag_assignments(&self) -> crate::service::catalog::EntityTagAssignmentsApi {
        crate::service::catalog::EntityTagAssignmentsApi::new(self.api_client().clone())
    }

    /// APIs to manage environment resources.
    #[cfg(feature = "environments")]
    #[must_use]
    pub fn environments(&self) -> crate::service::environments::EnvironmentsApi {
        crate::service::environments::EnvironmentsApi::new(self.api_client().clone())
    }

    /// Experiments are the primary unit of organization in MLflow; all MLflow
    /// runs belong to an experiment. Each experiment lets you visualize, search,
    /// and compare runs, as well as download run artifacts or metadata for
    /// analysis in other tools. Experiments are maintained in a Databricks
    /// hosted MLflow tracking server.
    #[cfg(feature = "ml")]
    #[must_use]
    pub fn experiments(&self) -> crate::service::ml::ExperimentsApi {
        crate::service::ml::ExperimentsApi::new(self.api_client().clone())
    }

    /// External Lineage APIs enable defining and managing lineage relationships
    /// between Databricks objects and external systems. These APIs allow users
    /// to capture data flows connecting Databricks tables, models, and file
    /// paths with external metadata objects.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn external_lineage(&self) -> crate::service::catalog::ExternalLineageApi {
        crate::service::catalog::ExternalLineageApi::new(self.api_client().clone())
    }

    /// An external location is an object that combines a cloud storage path with
    /// a storage credential that authorizes access to the cloud storage path.
    /// Each external location is subject to Unity Catalog access-control
    /// policies that control which users and groups can access the credential.
    /// If a user does not have access to an external location in Unity Catalog,
    /// the request fails and Unity Catalog does not attempt to authenticate to
    /// your cloud tenant on the user’s behalf.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn external_locations(&self) -> crate::service::catalog::ExternalLocationsApi {
        crate::service::catalog::ExternalLocationsApi::new(self.api_client().clone())
    }

    /// External Metadata objects enable customers to register and manage
    /// metadata about external systems within Unity Catalog.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn external_metadata(&self) -> crate::service::catalog::ExternalMetadataApi {
        crate::service::catalog::ExternalMetadataApi::new(self.api_client().clone())
    }

    /// [description]
    #[cfg(feature = "ml")]
    #[must_use]
    pub fn feature_engineering(&self) -> crate::service::ml::FeatureEngineeringApi {
        crate::service::ml::FeatureEngineeringApi::new(self.api_client().clone())
    }

    /// A feature store is a centralized repository that enables data scientists
    /// to find and share features. Using a feature store also ensures that the
    /// code used to compute feature values is the same during model training and
    /// when the model is used for inference.
    #[cfg(feature = "ml")]
    #[must_use]
    pub fn feature_store(&self) -> crate::service::ml::FeatureStoreApi {
        crate::service::ml::FeatureStoreApi::new(self.api_client().clone())
    }

    /// The Files API is a standard HTTP API that allows you to read, write,
    /// list, and delete files and directories by referring to their URI. The API
    /// makes working with file content as raw bytes easier and more efficient.
    #[cfg(feature = "files")]
    #[must_use]
    pub fn files(&self) -> crate::service::files::FilesApi {
        crate::service::files::FilesApi::new(self.api_client().clone())
    }

    /// The Forecasting API allows you to create and get serverless forecasting
    /// experiments
    #[cfg(feature = "ml")]
    #[must_use]
    pub fn forecasting(&self) -> crate::service::ml::ForecastingApi {
        crate::service::ml::ForecastingApi::new(self.api_client().clone())
    }

    /// Functions implement User-Defined Functions (UDFs) in Unity Catalog.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn functions(&self) -> crate::service::catalog::FunctionsApi {
        crate::service::catalog::FunctionsApi::new(self.api_client().clone())
    }

    /// Genie provides a no-code experience for business users, powered by AI/BI.
    /// Analysts set up spaces that business users can use to ask questions using
    /// natural language. Genie uses data registered to Unity Catalog and
    /// requires at least CAN USE permission on a Pro or Serverless SQL
    /// warehouse. Also, Databricks Assistant must be enabled.
    #[cfg(feature = "dashboards")]
    #[must_use]
    pub fn genie(&self) -> crate::service::dashboards::GenieApi {
        crate::service::dashboards::GenieApi::new(self.api_client().clone())
    }

    /// Registers personal access token for Databricks to do operations on behalf
    /// of the user.
    #[cfg(feature = "workspace")]
    #[must_use]
    pub fn git_credentials(&self) -> crate::service::workspace::GitCredentialsApi {
        crate::service::workspace::GitCredentialsApi::new(self.api_client().clone())
    }

    /// The Global Init Scripts API enables Workspace administrators to configure
    /// global initialization scripts for their workspace. These scripts run on
    /// every node in every cluster in the workspace.
    #[cfg(feature = "compute")]
    #[must_use]
    pub fn global_init_scripts(&self) -> crate::service::compute::GlobalInitScriptsApi {
        crate::service::compute::GlobalInitScriptsApi::new(self.api_client().clone())
    }

    /// In Unity Catalog, data is secure by default. Initially, users have no
    /// access to data in a metastore. Access can be granted by either a
    /// metastore admin, the owner of an object, or the owner of the catalog or
    /// schema that contains the object. Securable objects in Unity Catalog are
    /// hierarchical and privileges are inherited downward.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn grants(&self) -> crate::service::catalog::GrantsApi {
        crate::service::catalog::GrantsApi::new(self.api_client().clone())
    }

    /// Groups simplify identity management, making it easier to assign access to
    /// Databricks workspace, data, and other securable objects.
    #[cfg(feature = "iam")]
    #[must_use]
    pub fn groups_v2(&self) -> crate::service::iam::GroupsV2Api {
        crate::service::iam::GroupsV2Api::new(self.api_client().clone())
    }

    /// Instance Pools API are used to create, edit, delete and list instance
    /// pools by using ready-to-use cloud instances which reduces a cluster start
    /// and auto-scaling times.
    #[cfg(feature = "compute")]
    #[must_use]
    pub fn instance_pools(&self) -> crate::service::compute::InstancePoolsApi {
        crate::service::compute::InstancePoolsApi::new(self.api_client().clone())
    }

    /// The Instance Profiles API allows admins to add, list, and remove instance
    /// profiles that users can launch clusters with. Regular users can list the
    /// instance profiles available to them. See [Secure access to S3 buckets]
    /// using instance profiles for more information.
    #[cfg(feature = "compute")]
    #[must_use]
    pub fn instance_profiles(&self) -> crate::service::compute::InstanceProfilesApi {
        crate::service::compute::InstanceProfilesApi::new(self.api_client().clone())
    }

    /// IP Access List enables admins to configure IP access lists.
    #[cfg(feature = "settings")]
    #[must_use]
    pub fn ip_access_lists(&self) -> crate::service::settings::IpAccessListsApi {
        crate::service::settings::IpAccessListsApi::new(self.api_client().clone())
    }

    /// The Jobs API allows you to create, edit, and delete jobs.
    #[cfg(feature = "jobs")]
    #[must_use]
    pub fn jobs(&self) -> crate::service::jobs::JobsApi {
        crate::service::jobs::JobsApi::new(self.api_client().clone())
    }

    /// Manage Knowledge Assistants and related resources.
    #[cfg(feature = "knowledgeassistants")]
    #[must_use]
    pub fn knowledge_assistants(
        &self,
    ) -> crate::service::knowledgeassistants::KnowledgeAssistantsApi {
        crate::service::knowledgeassistants::KnowledgeAssistantsApi::new(self.api_client().clone())
    }

    /// These APIs provide specific management operations for Lakeview
    /// dashboards. Generic resource management can be done with Workspace API
    /// (import, export, get-status, list, delete).
    #[cfg(feature = "dashboards")]
    #[must_use]
    pub fn lakeview(&self) -> crate::service::dashboards::LakeviewApi {
        crate::service::dashboards::LakeviewApi::new(self.api_client().clone())
    }

    /// Token-based Lakeview APIs for embedding dashboards in external
    /// applications.
    #[cfg(feature = "dashboards")]
    #[must_use]
    pub fn lakeview_embedded(&self) -> crate::service::dashboards::LakeviewEmbeddedApi {
        crate::service::dashboards::LakeviewEmbeddedApi::new(self.api_client().clone())
    }

    /// The Libraries API allows you to install and uninstall libraries and get
    /// the status of libraries on a cluster.
    #[cfg(feature = "compute")]
    #[must_use]
    pub fn libraries(&self) -> crate::service::compute::LibrariesApi {
        crate::service::compute::LibrariesApi::new(self.api_client().clone())
    }

    /// Materialized Features are columns in tables and views that can be
    /// directly used as features to train and serve ML models.
    #[cfg(feature = "ml")]
    #[must_use]
    pub fn materialized_features(&self) -> crate::service::ml::MaterializedFeaturesApi {
        crate::service::ml::MaterializedFeaturesApi::new(self.api_client().clone())
    }

    /// A metastore is the top-level container of objects in Unity Catalog. It
    /// stores data assets (tables and views) and the permissions that govern
    /// access to them. Databricks account admins can create metastores and
    /// assign them to Databricks workspaces to control which workloads use each
    /// metastore. For a workspace to use Unity Catalog, it must have a Unity
    /// Catalog metastore attached.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn metastores(&self) -> crate::service::catalog::MetastoresApi {
        crate::service::catalog::MetastoresApi::new(self.api_client().clone())
    }

    /// Note: This API reference documents APIs for the Workspace Model Registry.
    /// Databricks recommends using [Models in Unity
    /// Catalog](/api/workspace/registeredmodels) instead. Models in Unity
    /// Catalog provides centralized model governance, cross-workspace access,
    /// lineage, and deployment. Workspace Model Registry will be deprecated in
    /// the future.
    #[cfg(feature = "ml")]
    #[must_use]
    pub fn model_registry(&self) -> crate::service::ml::ModelRegistryApi {
        crate::service::ml::ModelRegistryApi::new(self.api_client().clone())
    }

    /// Databricks provides a hosted version of MLflow Model Registry in Unity
    /// Catalog. Models in Unity Catalog provide centralized access control,
    /// auditing, lineage, and discovery of ML models across Databricks
    /// workspaces.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn model_versions(&self) -> crate::service::catalog::ModelVersionsApi {
        crate::service::catalog::ModelVersionsApi::new(self.api_client().clone())
    }

    /// The notification destinations API lets you programmatically manage a
    /// workspace's notification destinations. Notification destinations are used
    /// to send notifications for query alerts and jobs to destinations outside
    /// of Databricks. Only workspace admins can create, update, and delete
    /// notification destinations.
    #[cfg(feature = "settings")]
    #[must_use]
    pub fn notification_destinations(
        &self,
    ) -> crate::service::settings::NotificationDestinationsApi {
        crate::service::settings::NotificationDestinationsApi::new(self.api_client().clone())
    }

    /// Online tables provide lower latency and higher QPS access to data from
    /// Delta tables.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn online_tables(&self) -> crate::service::catalog::OnlineTablesApi {
        crate::service::catalog::OnlineTablesApi::new(self.api_client().clone())
    }

    /// APIs for migrating acl permissions, used only by the ucx tool:
    /// https://github.com/databrickslabs/ucx
    #[cfg(feature = "iam")]
    #[must_use]
    pub fn permission_migration(&self) -> crate::service::iam::PermissionMigrationApi {
        crate::service::iam::PermissionMigrationApi::new(self.api_client().clone())
    }

    /// Permissions API are used to create read, write, edit, update and manage
    /// access for various users on different objects and endpoints. * **[Apps
    /// permissions](:service:apps)** — Manage which users can manage or use
    /// apps. * **[Cluster permissions](:service:clusters)** — Manage which
    /// users can manage, restart, or attach to clusters. * **[Cluster policy
    /// permissions](:service:clusterpolicies)** — Manage which users can use
    /// cluster policies. * **[Spark Declarative Pipelines
    /// permissions](:service:pipelines)** — Manage which users can view,
    /// manage, run, cancel, or own a Spark Declarative Pipeline. * **[Job
    /// permissions](:service:jobs)** — Manage which users can view, manage,
    /// trigger, cancel, or own a job. * **[MLflow experiment
    /// permissions](:service:experiments)** — Manage which users can read,
    /// edit, or manage MLflow experiments. * **[MLflow registered model
    /// permissions](:service:modelregistry)** — Manage which users can read,
    /// edit, or manage MLflow registered models. * **[Instance Pool
    /// permissions](:service:instancepools)** — Manage which users can manage
    /// or attach to pools. * **[Repo permissions](repos)** — Manage which
    /// users can read, run, edit, or manage a repo. * **[Serving endpoint
    /// permissions](:service:servingendpoints)** — Manage which users can
    /// view, query, or manage a serving endpoint. * **[SQL warehouse
    /// permissions](:service:warehouses)** — Manage which users can use or
    /// manage SQL warehouses. * **[Token
    /// permissions](:service:tokenmanagement)** — Manage which users can
    /// create or use tokens. * **[Workspace object
    /// permissions](:service:workspace)** — Manage which users can read, run,
    /// edit, or manage alerts, dbsql-dashboards, directories, files, notebooks
    /// and queries. For the mapping of the required permissions for specific
    /// actions or abilities and other important information, see [Access
    /// Control]. Note that to manage access control on service principals, use
    /// **[Account Access Control Proxy](:service:accountaccesscontrolproxy)**.
    #[cfg(feature = "iam")]
    #[must_use]
    pub fn permissions(&self) -> crate::service::iam::PermissionsApi {
        crate::service::iam::PermissionsApi::new(self.api_client().clone())
    }

    /// The Lakeflow Spark Declarative Pipelines API allows you to create, edit,
    /// delete, start, and view details about pipelines.
    #[cfg(feature = "pipelines")]
    #[must_use]
    pub fn pipelines(&self) -> crate::service::pipelines::PipelinesApi {
        crate::service::pipelines::PipelinesApi::new(self.api_client().clone())
    }

    /// Attribute-Based Access Control (ABAC) provides high leverage governance
    /// for enforcing compliance policies in Unity Catalog. With ABAC policies,
    /// access is controlled in a hierarchical and scalable manner, based on data
    /// attributes rather than specific resources, enabling more flexible and
    /// comprehensive access control. ABAC policies in Unity Catalog support
    /// conditions on securable properties, governance tags, and environment
    /// contexts. Callers must have the `MANAGE` privilege on a securable to
    /// view, create, update, or delete ABAC policies.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn policies(&self) -> crate::service::catalog::PoliciesApi {
        crate::service::catalog::PoliciesApi::new(self.api_client().clone())
    }

    /// The policy compliance APIs allow you to view and manage the policy
    /// compliance status of clusters in your workspace.
    #[cfg(feature = "compute")]
    #[must_use]
    pub fn policy_compliance_for_clusters(
        &self,
    ) -> crate::service::compute::PolicyComplianceForClustersApi {
        crate::service::compute::PolicyComplianceForClustersApi::new(self.api_client().clone())
    }

    /// The compliance APIs allow you to view and manage the policy compliance
    /// status of jobs in your workspace. This API currently only supports
    /// compliance controls for cluster policies.
    #[cfg(feature = "jobs")]
    #[must_use]
    pub fn policy_compliance_for_jobs(&self) -> crate::service::jobs::PolicyComplianceForJobsApi {
        crate::service::jobs::PolicyComplianceForJobsApi::new(self.api_client().clone())
    }

    /// View available policy families. A policy family contains a policy
    /// definition providing best practices for configuring clusters for a
    /// particular use case.
    #[cfg(feature = "compute")]
    #[must_use]
    pub fn policy_families(&self) -> crate::service::compute::PolicyFamiliesApi {
        crate::service::compute::PolicyFamiliesApi::new(self.api_client().clone())
    }

    /// Use the Postgres API to create and manage Lakebase Autoscaling Postgres
    /// infrastructure, including projects, branches, compute endpoints, and
    /// roles.
    #[cfg(feature = "postgres")]
    #[must_use]
    pub fn postgres(&self) -> crate::service::postgres::PostgresApi {
        crate::service::postgres::PostgresApi::new(self.api_client().clone())
    }

    /// Marketplace exchanges filters curate which groups can access an exchange.
    #[cfg(feature = "marketplace")]
    #[must_use]
    pub fn provider_exchange_filters(
        &self,
    ) -> crate::service::marketplace::ProviderExchangeFiltersApi {
        crate::service::marketplace::ProviderExchangeFiltersApi::new(self.api_client().clone())
    }

    /// Marketplace exchanges allow providers to share their listings with a
    /// curated set of customers.
    #[cfg(feature = "marketplace")]
    #[must_use]
    pub fn provider_exchanges(&self) -> crate::service::marketplace::ProviderExchangesApi {
        crate::service::marketplace::ProviderExchangesApi::new(self.api_client().clone())
    }

    /// Marketplace offers a set of file APIs for various purposes such as
    /// preview notebooks and provider icons.
    #[cfg(feature = "marketplace")]
    #[must_use]
    pub fn provider_files(&self) -> crate::service::marketplace::ProviderFilesApi {
        crate::service::marketplace::ProviderFilesApi::new(self.api_client().clone())
    }

    /// Listings are the core entities in the Marketplace. They represent the
    /// products that are available for consumption.
    #[cfg(feature = "marketplace")]
    #[must_use]
    pub fn provider_listings(&self) -> crate::service::marketplace::ProviderListingsApi {
        crate::service::marketplace::ProviderListingsApi::new(self.api_client().clone())
    }

    /// Personalization requests are an alternate to instantly available
    /// listings. Control the lifecycle of personalized solutions.
    #[cfg(feature = "marketplace")]
    #[must_use]
    pub fn provider_personalization_requests(
        &self,
    ) -> crate::service::marketplace::ProviderPersonalizationRequestsApi {
        crate::service::marketplace::ProviderPersonalizationRequestsApi::new(
            self.api_client().clone(),
        )
    }

    /// Manage templated analytics solution for providers.
    #[cfg(feature = "marketplace")]
    #[must_use]
    pub fn provider_provider_analytics_dashboards(
        &self,
    ) -> crate::service::marketplace::ProviderProviderAnalyticsDashboardsApi {
        crate::service::marketplace::ProviderProviderAnalyticsDashboardsApi::new(
            self.api_client().clone(),
        )
    }

    /// Providers are entities that manage assets in Marketplace.
    #[cfg(feature = "marketplace")]
    #[must_use]
    pub fn provider_providers(&self) -> crate::service::marketplace::ProviderProvidersApi {
        crate::service::marketplace::ProviderProvidersApi::new(self.api_client().clone())
    }

    /// A data provider is an object representing the organization in the real
    /// world who shares the data. A provider contains shares which further
    /// contain the shared data.
    #[cfg(feature = "sharing")]
    #[must_use]
    pub fn providers(&self) -> crate::service::sharing::ProvidersApi {
        crate::service::sharing::ProvidersApi::new(self.api_client().clone())
    }

    /// Deprecated: Please use the Data Quality Monitoring API instead (REST:
    /// /api/data-quality/v1/monitors). Manage data quality of UC objects
    /// (currently support `schema`).
    #[cfg(feature = "qualitymonitorv2")]
    #[must_use]
    pub fn quality_monitor_v2(&self) -> crate::service::qualitymonitorv2::QualityMonitorV2Api {
        crate::service::qualitymonitorv2::QualityMonitorV2Api::new(self.api_client().clone())
    }

    /// Deprecated: Please use the Data Quality Monitors API instead (REST:
    /// /api/data-quality/v1/monitors), which manages both Data Profiling and
    /// Anomaly Detection.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn quality_monitors(&self) -> crate::service::catalog::QualityMonitorsApi {
        crate::service::catalog::QualityMonitorsApi::new(self.api_client().clone())
    }

    /// The queries API can be used to perform CRUD operations on queries. A
    /// query is a Databricks SQL object that includes the target SQL warehouse,
    /// query text, name, description, tags, and parameters. Queries can be
    /// scheduled using the `sql_task` type of the Jobs API, e.g.
    /// :method:jobs/create.
    #[cfg(feature = "sql")]
    #[must_use]
    pub fn queries(&self) -> crate::service::sql::QueriesApi {
        crate::service::sql::QueriesApi::new(self.api_client().clone())
    }

    /// These endpoints are used for CRUD operations on query definitions. Query
    /// definitions include the target SQL warehouse, query text, name,
    /// description, tags, parameters, and visualizations. Queries can be
    /// scheduled using the `sql_task` type of the Jobs API, e.g.
    /// :method:jobs/create.
    #[cfg(feature = "sql")]
    #[must_use]
    pub fn queries_legacy(&self) -> crate::service::sql::QueriesLegacyApi {
        crate::service::sql::QueriesLegacyApi::new(self.api_client().clone())
    }

    /// A service responsible for storing and retrieving the list of queries run
    /// against SQL endpoints and serverless compute.
    #[cfg(feature = "sql")]
    #[must_use]
    pub fn query_history(&self) -> crate::service::sql::QueryHistoryApi {
        crate::service::sql::QueryHistoryApi::new(self.api_client().clone())
    }

    /// This is an evolving API that facilitates the addition and removal of
    /// visualizations from existing queries in the Databricks Workspace. Data
    /// structures can change over time.
    #[cfg(feature = "sql")]
    #[must_use]
    pub fn query_visualizations(&self) -> crate::service::sql::QueryVisualizationsApi {
        crate::service::sql::QueryVisualizationsApi::new(self.api_client().clone())
    }

    /// This is an evolving API that facilitates the addition and removal of
    /// visualizations from existing queries within the Databricks Workspace.
    /// Data structures may change over time.
    #[cfg(feature = "sql")]
    #[must_use]
    pub fn query_visualizations_legacy(&self) -> crate::service::sql::QueryVisualizationsLegacyApi {
        crate::service::sql::QueryVisualizationsLegacyApi::new(self.api_client().clone())
    }

    /// The Recipient Activation API is only applicable in the open sharing model
    /// where the recipient object has the authentication type of `TOKEN`. The
    /// data recipient follows the activation link shared by the data provider to
    /// download the credential file that includes the access token. The
    /// recipient will then use the credential file to establish a secure
    /// connection with the provider to receive the shared data.
    #[cfg(feature = "sharing")]
    #[must_use]
    pub fn recipient_activation(&self) -> crate::service::sharing::RecipientActivationApi {
        crate::service::sharing::RecipientActivationApi::new(self.api_client().clone())
    }

    /// The Recipient Federation Policies APIs are only applicable in the open
    /// sharing model where the recipient object has the authentication type of
    /// `OIDC_RECIPIENT`, enabling data sharing from Databricks to non-Databricks
    /// recipients. OIDC Token Federation enables secure, secret-less
    /// authentication for accessing Delta Sharing servers. Users and
    /// applications authenticate using short-lived OIDC tokens issued by their
    /// own Identity Provider (IdP), such as Azure Entra ID or Okta, without the
    /// need for managing static credentials or client secrets. A federation
    /// policy defines how non-Databricks recipients authenticate using OIDC
    /// tokens. It validates the OIDC claims in federated tokens and is set at
    /// the recipient level. The caller must be the owner of the recipient to
    /// create or manage a federation policy. Federation policies support the
    /// following scenarios: - User-to-Machine (U2M) flow: A user accesses Delta
    /// Shares using their own identity, such as connecting through PowerBI Delta
    /// Sharing Client. - Machine-to-Machine (M2M) flow: An application accesses
    /// Delta Shares using its own identity, typically for automation tasks like
    /// nightly jobs through Python Delta Sharing Client. OIDC Token Federation
    /// enables fine-grained access control, supports Multi-Factor Authentication
    /// (MFA), and enhances security by minimizing the risk of credential leakage
    /// through the use of short-lived, expiring tokens. It is designed for
    /// strong identity governance, secure cross-platform data sharing, and
    /// reduced operational overhead for credential management.
    #[cfg(feature = "sharing")]
    #[must_use]
    pub fn recipient_federation_policies(
        &self,
    ) -> crate::service::sharing::RecipientFederationPoliciesApi {
        crate::service::sharing::RecipientFederationPoliciesApi::new(self.api_client().clone())
    }

    /// A recipient is an object you create using :method:recipients/create to
    /// represent an organization which you want to allow access shares. The way
    /// how sharing works differs depending on whether or not your recipient has
    /// access to a Databricks workspace that is enabled for Unity Catalog:
    #[cfg(feature = "sharing")]
    #[must_use]
    pub fn recipients(&self) -> crate::service::sharing::RecipientsApi {
        crate::service::sharing::RecipientsApi::new(self.api_client().clone())
    }

    /// Redash V2 service for workspace configurations (internal)
    #[cfg(feature = "sql")]
    #[must_use]
    pub fn redash_config(&self) -> crate::service::sql::RedashConfigApi {
        crate::service::sql::RedashConfigApi::new(self.api_client().clone())
    }

    /// Databricks provides a hosted version of MLflow Model Registry in Unity
    /// Catalog. Models in Unity Catalog provide centralized access control,
    /// auditing, lineage, and discovery of ML models across Databricks
    /// workspaces.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn registered_models(&self) -> crate::service::catalog::RegisteredModelsApi {
        crate::service::catalog::RegisteredModelsApi::new(self.api_client().clone())
    }

    /// The Repos API allows users to manage their git repos. Users can use the
    /// API to access all repos that they have manage permissions on.
    #[cfg(feature = "workspace")]
    #[must_use]
    pub fn repos(&self) -> crate::service::workspace::ReposApi {
        crate::service::workspace::ReposApi::new(self.api_client().clone())
    }

    /// Unity Catalog enforces resource quotas on all securable objects, which
    /// limits the number of resources that can be created. Quotas are expressed
    /// in terms of a resource type and a parent (for example, tables per
    /// metastore or schemas per catalog). The resource quota APIs enable you to
    /// monitor your current usage and limits. For more information on resource
    /// quotas see the [Unity Catalog documentation].
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn resource_quotas(&self) -> crate::service::catalog::ResourceQuotasApi {
        crate::service::catalog::ResourceQuotasApi::new(self.api_client().clone())
    }

    /// Request for Access enables users to request access for Unity Catalog
    /// securables.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn rfa(&self) -> crate::service::catalog::RfaApi {
        crate::service::catalog::RfaApi::new(self.api_client().clone())
    }

    /// Create, manage, and control the lifecycle of sandboxes -- isolated,
    /// pre-configured, low-latency Serverless compute environments for running
    /// code.
    #[cfg(feature = "sandbox")]
    #[must_use]
    pub fn sandbox(&self) -> crate::service::sandbox::SandboxApi {
        crate::service::sandbox::SandboxApi::new(self.api_client().clone())
    }

    /// A schema (also called a database) is the second layer of Unity
    /// Catalog’s three-level namespace. A schema organizes tables, views, and
    /// functions. To access (or list) a table or view in a schema, users must
    /// have the USE_SCHEMA data permission on the schema and its parent catalog,
    /// and they must have the SELECT permission on the table or view.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn schemas(&self) -> crate::service::catalog::SchemasApi {
        crate::service::catalog::SchemasApi::new(self.api_client().clone())
    }

    /// The Secrets API allows you to manage secrets, secret scopes, and access
    /// permissions.
    #[cfg(feature = "workspace")]
    #[must_use]
    pub fn secrets(&self) -> crate::service::workspace::SecretsApi {
        crate::service::workspace::SecretsApi::new(self.api_client().clone())
    }

    /// A secret is a Unity Catalog securable object that stores sensitive
    /// credential data (such as passwords, tokens, and keys) within a
    /// three-level namespace (**catalog_name.schema_name.secret_name**).
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn secrets_uc(&self) -> crate::service::catalog::SecretsUcApi {
        crate::service::catalog::SecretsUcApi::new(self.api_client().clone())
    }

    /// These APIs enable administrators to manage service principal secrets at
    /// the workspace level. To use these APIs, the service principal must be
    /// first added to the current workspace.
    #[cfg(feature = "oauth2")]
    #[must_use]
    pub fn service_principal_secrets_proxy(
        &self,
    ) -> crate::service::oauth2::ServicePrincipalSecretsProxyApi {
        crate::service::oauth2::ServicePrincipalSecretsProxyApi::new(self.api_client().clone())
    }

    /// Identities for use with jobs, automated tools, and systems such as
    /// scripts, apps, and CI/CD platforms. Databricks recommends creating
    /// service principals to run production jobs or modify production data. If
    /// all processes that act on production data run with service principals,
    /// interactive users do not need any write, delete, or modify privileges in
    /// production. This eliminates the risk of a user overwriting production
    /// data by accident.
    #[cfg(feature = "iam")]
    #[must_use]
    pub fn service_principals_v2(&self) -> crate::service::iam::ServicePrincipalsV2Api {
        crate::service::iam::ServicePrincipalsV2Api::new(self.api_client().clone())
    }

    /// The Serving Endpoints API allows you to create, update, and delete model
    /// serving endpoints.
    #[cfg(feature = "serving")]
    #[must_use]
    pub fn serving_endpoints(&self) -> crate::service::serving::ServingEndpointsApi {
        crate::service::serving::ServingEndpointsApi::new(self.api_client().clone())
    }

    /// Workspace Settings API allows users to manage settings at the workspace
    /// level.
    #[cfg(feature = "settings")]
    #[must_use]
    pub fn settings(&self) -> crate::service::settings::SettingsApi {
        crate::service::settings::SettingsApi::new(self.api_client().clone())
    }

    /// A share is a container instantiated with :method:shares/create. Once
    /// created you can iteratively register a collection of existing data assets
    /// defined within the metastore using :method:shares/update. You can
    /// register data assets under their original name, qualified by their
    /// original schema, or provide alternate exposed names.
    #[cfg(feature = "sharing")]
    #[must_use]
    pub fn shares(&self) -> crate::service::sharing::SharesApi {
        crate::service::sharing::SharesApi::new(self.api_client().clone())
    }

    /// The Databricks SQL Statement Execution API can be used to execute SQL
    /// statements on a SQL warehouse and fetch the result.
    #[cfg(feature = "sql")]
    #[must_use]
    pub fn statement_execution(&self) -> crate::service::sql::StatementExecutionApi {
        crate::service::sql::StatementExecutionApi::new(self.api_client().clone())
    }

    /// A storage credential represents an authentication and authorization
    /// mechanism for accessing data stored on your cloud tenant. Each storage
    /// credential is subject to Unity Catalog access-control policies that
    /// control which users and groups can access the credential. If a user does
    /// not have access to a storage credential in Unity Catalog, the request
    /// fails and Unity Catalog does not attempt to authenticate to your cloud
    /// tenant on the user’s behalf.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn storage_credentials(&self) -> crate::service::catalog::StorageCredentialsApi {
        crate::service::catalog::StorageCredentialsApi::new(self.api_client().clone())
    }

    /// Manage Supervisor Agents and related resources.
    #[cfg(feature = "supervisoragents")]
    #[must_use]
    pub fn supervisor_agents(&self) -> crate::service::supervisoragents::SupervisorAgentsApi {
        crate::service::supervisoragents::SupervisorAgentsApi::new(self.api_client().clone())
    }

    /// A system schema is a schema that lives within the system catalog. A
    /// system schema may contain information about customer usage of Unity
    /// Catalog such as audit logs, billing logs, and lineage information.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn system_schemas(&self) -> crate::service::catalog::SystemSchemasApi {
        crate::service::catalog::SystemSchemasApi::new(self.api_client().clone())
    }

    /// Primary key and foreign key constraints encode relationships between
    /// fields in tables.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn table_constraints(&self) -> crate::service::catalog::TableConstraintsApi {
        crate::service::catalog::TableConstraintsApi::new(self.api_client().clone())
    }

    /// A table resides in the third layer of Unity Catalog’s three-level
    /// namespace. It contains rows of data. To create a table, users must have
    /// CREATE_TABLE and USE_SCHEMA permissions on the schema, and they must have
    /// the USE_CATALOG permission on its parent catalog. To query a table, users
    /// must have the SELECT permission on the table, and they must have the
    /// USE_CATALOG permission on its parent catalog and the USE_SCHEMA
    /// permission on its parent schema.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn tables(&self) -> crate::service::catalog::TablesApi {
        crate::service::catalog::TablesApi::new(self.api_client().clone())
    }

    /// The Tag Policy API allows you to manage policies for governed tags in
    /// Databricks. For Terraform usage, see the [Tag Policy Terraform
    /// documentation]. Permissions for tag policies can be managed using the
    /// [Account Access Control Proxy API].
    #[cfg(feature = "tags")]
    #[must_use]
    pub fn tag_policies(&self) -> crate::service::tags::TagPoliciesApi {
        crate::service::tags::TagPoliciesApi::new(self.api_client().clone())
    }

    /// Temporary Path Credentials are short-lived, downscoped credentials used
    /// to access external cloud storage locations registered in Databricks.
    /// These credentials provide secure and time-limited access to data in cloud
    /// environments such as AWS, Azure, and Google Cloud. Each cloud provider
    /// has its own type of credentials: AWS uses temporary session tokens
    /// through AWS Security Token Service (STS), Azure uses Shared Access
    /// Signatures (SAS) for its data storage services, and Google Cloud supports
    /// temporary credentials through OAuth 2.0.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn temporary_path_credentials(
        &self,
    ) -> crate::service::catalog::TemporaryPathCredentialsApi {
        crate::service::catalog::TemporaryPathCredentialsApi::new(self.api_client().clone())
    }

    /// Temporary Table Credentials are short-lived, downscoped credentials used
    /// to access cloud storage locations where table data is stored in
    /// Databricks. These credentials provide secure and time-limited access to
    /// data in cloud environments such as AWS, Azure, and Google Cloud. Each
    /// cloud provider has its own type of credentials: AWS uses temporary
    /// session tokens through AWS Security Token Service (STS), Azure uses
    /// Shared Access Signatures (SAS) for its data storage services, and Google
    /// Cloud supports temporary credentials through OAuth 2.0.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn temporary_table_credentials(
        &self,
    ) -> crate::service::catalog::TemporaryTableCredentialsApi {
        crate::service::catalog::TemporaryTableCredentialsApi::new(self.api_client().clone())
    }

    /// Temporary Volume Credentials are short-lived, downscoped credentials used
    /// to access cloud storage locations where volume data is stored in
    /// Databricks. These credentials provide secure and time-limited access to
    /// data in cloud environments such as AWS, Azure, and Google Cloud. Each
    /// cloud provider has its own type of credentials: AWS uses temporary
    /// session tokens through AWS Security Token Service (STS), Azure uses
    /// Shared Access Signatures (SAS) for its data storage services, and Google
    /// Cloud supports temporary credentials through OAuth 2.0.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn temporary_volume_credentials(
        &self,
    ) -> crate::service::catalog::TemporaryVolumeCredentialsApi {
        crate::service::catalog::TemporaryVolumeCredentialsApi::new(self.api_client().clone())
    }

    /// Enables administrators to get all tokens and delete tokens for other
    /// users. Admins can either get every token, get a specific token by ID, or
    /// get all tokens for a particular user.
    #[cfg(feature = "settings")]
    #[must_use]
    pub fn token_management(&self) -> crate::service::settings::TokenManagementApi {
        crate::service::settings::TokenManagementApi::new(self.api_client().clone())
    }

    /// The Token API allows you to create, list, and revoke tokens that can be
    /// used to authenticate and access Databricks REST APIs.
    #[cfg(feature = "settings")]
    #[must_use]
    pub fn tokens(&self) -> crate::service::settings::TokensApi {
        crate::service::settings::TokensApi::new(self.api_client().clone())
    }

    /// User identities recognized by Databricks and represented by email
    /// addresses.
    #[cfg(feature = "iam")]
    #[must_use]
    pub fn users_v2(&self) -> crate::service::iam::UsersV2Api {
        crate::service::iam::UsersV2Api::new(self.api_client().clone())
    }

    /// **Endpoint**: Represents the compute resources to host AI Search indexes.
    #[cfg(feature = "vectorsearch")]
    #[must_use]
    pub fn vector_search_endpoints(
        &self,
    ) -> crate::service::vectorsearch::VectorSearchEndpointsApi {
        crate::service::vectorsearch::VectorSearchEndpointsApi::new(self.api_client().clone())
    }

    /// **Index**: An efficient representation of your embedding vectors that
    /// supports real-time and efficient approximate nearest neighbor (ANN)
    /// search queries.
    #[cfg(feature = "vectorsearch")]
    #[must_use]
    pub fn vector_search_indexes(&self) -> crate::service::vectorsearch::VectorSearchIndexesApi {
        crate::service::vectorsearch::VectorSearchIndexesApi::new(self.api_client().clone())
    }

    /// Volumes are a Unity Catalog (UC) capability for accessing, storing,
    /// governing, organizing, and processing files. Use cases include running
    /// machine learning on unstructured data such as image, audio, video, or PDF
    /// files, organizing data sets during the data exploration stages in data
    /// science, working with libraries that require access to the local file
    /// system on cluster machines, storing library and config files of arbitrary
    /// formats such as .whl or .txt centrally and providing secure access to
    /// those files across workspaces, or transforming and querying non-tabular
    /// data files in ETL.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn volumes(&self) -> crate::service::catalog::VolumesApi {
        crate::service::catalog::VolumesApi::new(self.api_client().clone())
    }

    /// A SQL warehouse is a compute resource that lets you run SQL commands on
    /// data objects within Databricks SQL. Compute resources are infrastructure
    /// resources that provide processing capabilities in the cloud.
    #[cfg(feature = "sql")]
    #[must_use]
    pub fn warehouses(&self) -> crate::service::sql::WarehousesApi {
        crate::service::sql::WarehousesApi::new(self.api_client().clone())
    }

    /// The Workspace API allows you to list, import, export, and delete
    /// workspace objects such as notebooks, files, folders, and dashboards.
    /// Additionally, it provides endpoints to manage permissions for any
    /// workspace object.
    #[cfg(feature = "workspace")]
    #[must_use]
    pub fn workspace(&self) -> crate::service::workspace::WorkspaceApi {
        crate::service::workspace::WorkspaceApi::new(self.api_client().clone())
    }

    /// A securable in Databricks can be configured as __OPEN__ or __ISOLATED__.
    /// An __OPEN__ securable can be accessed from any workspace, while an
    /// __ISOLATED__ securable can only be accessed from a configured list of
    /// workspaces. This API allows you to configure (bind) securables to
    /// workspaces.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn workspace_bindings(&self) -> crate::service::catalog::WorkspaceBindingsApi {
        crate::service::catalog::WorkspaceBindingsApi::new(self.api_client().clone())
    }

    /// This API allows updating known workspace settings for advanced users.
    #[cfg(feature = "settings")]
    #[must_use]
    pub fn workspace_conf(&self) -> crate::service::settings::WorkspaceConfApi {
        crate::service::settings::WorkspaceConfApi::new(self.api_client().clone())
    }

    /// Manage tag assignments on workspace-scoped objects.
    #[cfg(feature = "tags")]
    #[must_use]
    pub fn workspace_entity_tag_assignments(
        &self,
    ) -> crate::service::tags::WorkspaceEntityTagAssignmentsApi {
        crate::service::tags::WorkspaceEntityTagAssignmentsApi::new(self.api_client().clone())
    }

    /// These APIs are used to manage identities and the workspace access of
    /// these identities in Databricks.
    #[cfg(feature = "iamv2")]
    #[must_use]
    pub fn workspace_iam_v2(&self) -> crate::service::iamv2::WorkspaceIamV2Api {
        crate::service::iamv2::WorkspaceIamV2Api::new(self.api_client().clone())
    }

    /// APIs to manage workspace level settings
    #[cfg(feature = "settingsv2")]
    #[must_use]
    pub fn workspace_settings_v2(&self) -> crate::service::settingsv2::WorkspaceSettingsV2Api {
        crate::service::settingsv2::WorkspaceSettingsV2Api::new(self.api_client().clone())
    }
}

impl AccountClient {
    /// These APIs manage access rules on resources in an account. Currently,
    /// only grant rules are supported. A grant rule specifies a role assigned to
    /// a set of principals. A list of rules attached to a resource is called a
    /// rule set.
    #[cfg(feature = "iam")]
    #[must_use]
    pub fn access_control(&self) -> crate::service::iam::AccountAccessControlApi {
        crate::service::iam::AccountAccessControlApi::new(self.api_client().clone())
    }

    /// This API allows you to download billable usage logs for the specified
    /// account and date range. This feature works with all account types.
    #[cfg(feature = "billing")]
    #[must_use]
    pub fn billable_usage(&self) -> crate::service::billing::BillableUsageApi {
        crate::service::billing::BillableUsageApi::new(self.api_client().clone())
    }

    /// A service serves REST API about Budget policies
    #[cfg(feature = "billing")]
    #[must_use]
    pub fn budget_policy(&self) -> crate::service::billing::BudgetPolicyApi {
        crate::service::billing::BudgetPolicyApi::new(self.api_client().clone())
    }

    /// These APIs manage budget configurations for this account. Budgets enable
    /// you to monitor usage across your account. You can set up budgets to
    /// either track account-wide spending, or apply filters to track the
    /// spending of specific teams, projects, or workspaces.
    #[cfg(feature = "billing")]
    #[must_use]
    pub fn budgets(&self) -> crate::service::billing::BudgetsApi {
        crate::service::billing::BudgetsApi::new(self.api_client().clone())
    }

    /// These APIs manage credential configurations for this workspace.
    /// Databricks needs access to a cross-account service IAM role in your AWS
    /// account so that Databricks can deploy clusters in the appropriate VPC for
    /// the new workspace. A credential configuration encapsulates this role
    /// information, and its ID is used when creating a new workspace.
    #[cfg(feature = "provisioning")]
    #[must_use]
    pub fn credentials(&self) -> crate::service::provisioning::CredentialsApi {
        crate::service::provisioning::CredentialsApi::new(self.api_client().clone())
    }

    /// These APIs enable administrators to manage custom OAuth app integrations,
    /// which is required for adding/using Custom OAuth App Integration like
    /// Tableau Cloud for Databricks in AWS cloud.
    #[cfg(feature = "oauth2")]
    #[must_use]
    pub fn custom_app_integration(&self) -> crate::service::oauth2::CustomAppIntegrationApi {
        crate::service::oauth2::CustomAppIntegrationApi::new(self.api_client().clone())
    }

    /// Manage disaster recovery configurations and execute failover operations.
    #[cfg(feature = "disasterrecovery")]
    #[must_use]
    pub fn disaster_recovery(&self) -> crate::service::disasterrecovery::DisasterRecoveryApi {
        crate::service::disasterrecovery::DisasterRecoveryApi::new(self.api_client().clone())
    }

    /// These APIs manage encryption key configurations for this workspace
    /// (optional). A key configuration encapsulates the AWS KMS key information
    /// and some information about how the key configuration can be used. There
    /// are two possible uses for key configurations:
    #[cfg(feature = "provisioning")]
    #[must_use]
    pub fn encryption_keys(&self) -> crate::service::provisioning::EncryptionKeysApi {
        crate::service::provisioning::EncryptionKeysApi::new(self.api_client().clone())
    }

    /// These APIs manage endpoint configurations for this account.
    #[cfg(feature = "networking")]
    #[must_use]
    pub fn endpoints(&self) -> crate::service::networking::EndpointsApi {
        crate::service::networking::EndpointsApi::new(self.api_client().clone())
    }

    /// These APIs manage account federation policies.
    #[cfg(feature = "oauth2")]
    #[must_use]
    pub fn federation_policy(&self) -> crate::service::oauth2::AccountFederationPolicyApi {
        crate::service::oauth2::AccountFederationPolicyApi::new(self.api_client().clone())
    }

    /// Groups simplify identity management, making it easier to assign access to
    /// Databricks account, data, and other securable objects.
    #[cfg(feature = "iam")]
    #[must_use]
    pub fn groups_v2(&self) -> crate::service::iam::AccountGroupsV2Api {
        crate::service::iam::AccountGroupsV2Api::new(self.api_client().clone())
    }

    /// These APIs are used to manage identities and the workspace access of
    /// these identities in Databricks.
    #[cfg(feature = "iamv2")]
    #[must_use]
    pub fn iam_v2(&self) -> crate::service::iamv2::AccountIamV2Api {
        crate::service::iamv2::AccountIamV2Api::new(self.api_client().clone())
    }

    /// The Accounts IP Access List API enables account admins to configure IP
    /// access lists for access to the account console.
    #[cfg(feature = "settings")]
    #[must_use]
    pub fn ip_access_lists(&self) -> crate::service::settings::AccountIpAccessListsApi {
        crate::service::settings::AccountIpAccessListsApi::new(self.api_client().clone())
    }

    /// These APIs manage log delivery configurations for this account. The two
    /// supported log types for this API are _billable usage logs_ (AWS only) and
    /// _audit logs_ (AWS and GCP). This feature is in Public Preview. This
    /// feature works with all account ID types.
    #[cfg(feature = "billing")]
    #[must_use]
    pub fn log_delivery(&self) -> crate::service::billing::LogDeliveryApi {
        crate::service::billing::LogDeliveryApi::new(self.api_client().clone())
    }

    /// These APIs manage metastore assignments to a workspace.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn metastore_assignments(&self) -> crate::service::catalog::AccountMetastoreAssignmentsApi {
        crate::service::catalog::AccountMetastoreAssignmentsApi::new(self.api_client().clone())
    }

    /// These APIs manage Unity Catalog metastores for an account. A metastore
    /// contains catalogs that can be associated with workspaces
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn metastores(&self) -> crate::service::catalog::AccountMetastoresApi {
        crate::service::catalog::AccountMetastoresApi::new(self.api_client().clone())
    }

    /// These APIs provide configurations for the network connectivity of your
    /// workspaces for serverless compute resources. This API provides stable
    /// subnets for your workspace so that you can configure your firewalls on
    /// your Azure Storage accounts to allow access from Databricks. You can also
    /// use the API to provision private endpoints for Databricks to privately
    /// connect serverless compute resources to your Azure resources using Azure
    /// Private Link. See [configure serverless secure connectivity].
    #[cfg(feature = "settings")]
    #[must_use]
    pub fn network_connectivity(&self) -> crate::service::settings::NetworkConnectivityApi {
        crate::service::settings::NetworkConnectivityApi::new(self.api_client().clone())
    }

    /// These APIs manage network policies for this account. Network policies
    /// control which network destinations can be accessed from the Databricks
    /// environment. Each Databricks account includes a default policy named
    /// 'default-policy'. 'default-policy' is associated with any workspace
    /// lacking an explicit network policy assignment, and is automatically
    /// associated with each newly created workspace. 'default-policy' is
    /// reserved and cannot be deleted, but it can be updated to customize the
    /// default network access rules for your account.
    #[cfg(feature = "settings")]
    #[must_use]
    pub fn network_policies(&self) -> crate::service::settings::NetworkPoliciesApi {
        crate::service::settings::NetworkPoliciesApi::new(self.api_client().clone())
    }

    /// These APIs manage network configurations for customer-managed VPCs
    /// (optional). Its ID is used when creating a new workspace if you use
    /// customer-managed VPCs.
    #[cfg(feature = "provisioning")]
    #[must_use]
    pub fn networks(&self) -> crate::service::provisioning::NetworksApi {
        crate::service::provisioning::NetworksApi::new(self.api_client().clone())
    }

    /// These APIs enable administrators to view all the available published
    /// OAuth applications in Databricks. Administrators can add the published
    /// OAuth applications to their account through the OAuth Published App
    /// Integration APIs.
    #[cfg(feature = "oauth2")]
    #[must_use]
    pub fn o_auth_published_apps(&self) -> crate::service::oauth2::OAuthPublishedAppsApi {
        crate::service::oauth2::OAuthPublishedAppsApi::new(self.api_client().clone())
    }

    /// These APIs manage private access settings for this account.
    #[cfg(feature = "provisioning")]
    #[must_use]
    pub fn private_access(&self) -> crate::service::provisioning::PrivateAccessApi {
        crate::service::provisioning::PrivateAccessApi::new(self.api_client().clone())
    }

    /// These APIs enable administrators to manage published OAuth app
    /// integrations, which is required for adding/using Published OAuth App
    /// Integration like Tableau Desktop for Databricks in AWS cloud.
    #[cfg(feature = "oauth2")]
    #[must_use]
    pub fn published_app_integration(&self) -> crate::service::oauth2::PublishedAppIntegrationApi {
        crate::service::oauth2::PublishedAppIntegrationApi::new(self.api_client().clone())
    }

    /// These APIs manage service principal federation policies.
    #[cfg(feature = "oauth2")]
    #[must_use]
    pub fn service_principal_federation_policy(
        &self,
    ) -> crate::service::oauth2::ServicePrincipalFederationPolicyApi {
        crate::service::oauth2::ServicePrincipalFederationPolicyApi::new(self.api_client().clone())
    }

    /// These APIs enable administrators to manage service principal secrets.
    #[cfg(feature = "oauth2")]
    #[must_use]
    pub fn service_principal_secrets(&self) -> crate::service::oauth2::ServicePrincipalSecretsApi {
        crate::service::oauth2::ServicePrincipalSecretsApi::new(self.api_client().clone())
    }

    /// Identities for use with jobs, automated tools, and systems such as
    /// scripts, apps, and CI/CD platforms. Databricks recommends creating
    /// service principals to run production jobs or modify production data. If
    /// all processes that act on production data run with service principals,
    /// interactive users do not need any write, delete, or modify privileges in
    /// production. This eliminates the risk of a user overwriting production
    /// data by accident.
    #[cfg(feature = "iam")]
    #[must_use]
    pub fn service_principals_v2(&self) -> crate::service::iam::AccountServicePrincipalsV2Api {
        crate::service::iam::AccountServicePrincipalsV2Api::new(self.api_client().clone())
    }

    /// Accounts Settings API allows users to manage settings at the account
    /// level.
    #[cfg(feature = "settings")]
    #[must_use]
    pub fn settings(&self) -> crate::service::settings::AccountSettingsApi {
        crate::service::settings::AccountSettingsApi::new(self.api_client().clone())
    }

    /// APIs to manage account level settings
    #[cfg(feature = "settingsv2")]
    #[must_use]
    pub fn settings_v2(&self) -> crate::service::settingsv2::AccountSettingsV2Api {
        crate::service::settingsv2::AccountSettingsV2Api::new(self.api_client().clone())
    }

    /// These APIs manage storage configurations for this workspace. A root
    /// storage S3 bucket in your account is required to store objects like
    /// cluster logs, notebook revisions, and job results. You can also use the
    /// root storage S3 bucket for storage of non-production DBFS data. A storage
    /// configuration encapsulates this bucket information, and its ID is used
    /// when creating a new workspace.
    #[cfg(feature = "provisioning")]
    #[must_use]
    pub fn storage(&self) -> crate::service::provisioning::StorageApi {
        crate::service::provisioning::StorageApi::new(self.api_client().clone())
    }

    /// These APIs manage storage credentials for a particular metastore.
    #[cfg(feature = "catalog")]
    #[must_use]
    pub fn storage_credentials(&self) -> crate::service::catalog::AccountStorageCredentialsApi {
        crate::service::catalog::AccountStorageCredentialsApi::new(self.api_client().clone())
    }

    /// These APIs manage usage dashboards for this account. Usage dashboards
    /// enable you to gain insights into your usage with pre-built dashboards:
    /// visualize breakdowns, analyze tag attributions, and identify cost
    /// drivers.
    #[cfg(feature = "billing")]
    #[must_use]
    pub fn usage_dashboards(&self) -> crate::service::billing::UsageDashboardsApi {
        crate::service::billing::UsageDashboardsApi::new(self.api_client().clone())
    }

    /// User identities recognized by Databricks and represented by email
    /// addresses.
    #[cfg(feature = "iam")]
    #[must_use]
    pub fn users_v2(&self) -> crate::service::iam::AccountUsersV2Api {
        crate::service::iam::AccountUsersV2Api::new(self.api_client().clone())
    }

    /// These APIs manage VPC endpoint configurations for this account.
    #[cfg(feature = "provisioning")]
    #[must_use]
    pub fn vpc_endpoints(&self) -> crate::service::provisioning::VpcEndpointsApi {
        crate::service::provisioning::VpcEndpointsApi::new(self.api_client().clone())
    }

    /// The Workspace Permission Assignment API allows you to manage workspace
    /// permissions for principals in your account.
    #[cfg(feature = "iam")]
    #[must_use]
    pub fn workspace_assignment(&self) -> crate::service::iam::WorkspaceAssignmentApi {
        crate::service::iam::WorkspaceAssignmentApi::new(self.api_client().clone())
    }

    /// These APIs allow configuration of network settings for Databricks
    /// workspaces by selecting which network policy to associate with the
    /// workspace. Each workspace is always associated with exactly one network
    /// policy that controls which network destinations can be accessed from the
    /// Databricks environment. By default, workspaces are associated with the
    /// 'default-policy' network policy. You cannot create or delete a
    /// workspace's network option, only update it to associate the workspace
    /// with a different policy
    #[cfg(feature = "settings")]
    #[must_use]
    pub fn workspace_network_configuration(
        &self,
    ) -> crate::service::settings::WorkspaceNetworkConfigurationApi {
        crate::service::settings::WorkspaceNetworkConfigurationApi::new(self.api_client().clone())
    }

    /// These APIs manage workspaces for this account. A Databricks workspace is
    /// an environment for accessing all of your Databricks assets. The workspace
    /// organizes objects (notebooks, libraries, and experiments) into folders,
    /// and provides access to data and computational resources such as clusters
    /// and jobs.
    #[cfg(feature = "provisioning")]
    #[must_use]
    pub fn workspaces(&self) -> crate::service::provisioning::WorkspacesApi {
        crate::service::provisioning::WorkspacesApi::new(self.api_client().clone())
    }
}
