//! Unofficial Rust SDK for the Databricks REST APIs.
//!
//! Every service module under [`service`] is generated by `cargo xtask
//! codegen` from `spec/ir.json`, which is extracted from databricks-sdk-go
//! (see `spec/README.md`). Each Go SDK package is a feature of the same name;
//! `default` enables `catalog`, `compute`, `jobs` and `provisioning`, and
//! `full` enables everything.
//!
//! ```no_run
//! use community_databricks_sdk::WorkspaceClient;
//! use community_databricks_sdk::service::compute::{ListClustersRequest, State};
//! use futures_util::TryStreamExt;
//!
//! # async fn run() -> community_databricks_sdk::Result<()> {
//! // Host and credentials from DATABRICKS_* env vars or ~/.databrickscfg.
//! let w = WorkspaceClient::from_env().await?;
//! let mut clusters = w.clusters().list(ListClustersRequest::default().with_page_size(50));
//! while let Some(c) = clusters.try_next().await? {
//!     println!("{} {:?}", c.cluster_name.unwrap_or_default(), c.state);
//! }
//! # Ok(()) }
//! ```

mod accessors;
pub mod service;

use community_databricks_core::auth::DefaultCredentials;
pub use community_databricks_core::{
    self as core, ApiClient, ApiError, Config, Error, ErrorKind, Result,
};

/// Client for workspace-level APIs.
#[derive(Debug, Clone)]
pub struct WorkspaceClient {
    api: ApiClient,
}

impl WorkspaceClient {
    /// Configure entirely from the environment / `~/.databrickscfg`.
    pub async fn from_env() -> Result<Self> {
        Self::new(Config::default()).await
    }

    /// Build from a config; unset values are filled from the environment.
    pub async fn new(cfg: Config) -> Result<Self> {
        Ok(Self::from_api_client(ApiClient::new(cfg).await?))
    }

    /// Build with a custom credential chain.
    pub async fn with_credentials(cfg: Config, credentials: DefaultCredentials) -> Result<Self> {
        Ok(Self::from_api_client(
            ApiClient::with_credentials(cfg, credentials).await?,
        ))
    }

    /// Wrap an existing [`ApiClient`].
    #[must_use]
    pub fn from_api_client(api: ApiClient) -> Self {
        Self { api }
    }

    /// The underlying client, for calling endpoints the SDK doesn't cover.
    #[must_use]
    pub fn api_client(&self) -> &ApiClient {
        &self.api
    }

    /// The resolved configuration.
    #[must_use]
    pub fn config(&self) -> &Config {
        self.api.config()
    }
}

/// Client for account-level APIs.
#[derive(Debug, Clone)]
pub struct AccountClient {
    api: ApiClient,
    account_id: String,
}

impl AccountClient {
    /// Configure entirely from the environment / `~/.databrickscfg`.
    pub async fn from_env() -> Result<Self> {
        Self::new(Config::default()).await
    }

    /// Build from a config; `account_id` must resolve to a value.
    pub async fn new(cfg: Config) -> Result<Self> {
        Self::from_api_client(ApiClient::new(cfg).await?)
    }

    /// Build with a custom credential chain.
    pub async fn with_credentials(cfg: Config, credentials: DefaultCredentials) -> Result<Self> {
        Self::from_api_client(ApiClient::with_credentials(cfg, credentials).await?)
    }

    /// Wrap an existing [`ApiClient`].
    pub fn from_api_client(api: ApiClient) -> Result<Self> {
        let account_id = api
            .config()
            .account_id
            .clone()
            .filter(|a| !a.is_empty())
            .ok_or_else(|| {
                Error::Config(
                    "invalid Databricks Account configuration - host incorrect or account_id missing"
                        .into(),
                )
            })?;
        Ok(Self { api, account_id })
    }

    /// The underlying client.
    #[must_use]
    pub fn api_client(&self) -> &ApiClient {
        &self.api
    }

    /// The account ID requests are made against.
    #[must_use]
    pub fn account_id(&self) -> &str {
        &self.account_id
    }
}
