//! Unofficial Rust SDK for the Databricks REST APIs.
//!
//! Every service module under [`service`] is generated by `cargo xtask
//! codegen` from `spec/ir.json`, which is extracted from databricks-sdk-go
//! (see `spec/README.md`). Each Go SDK package is a feature of the same name;
//! `default` enables `catalog`, `compute`, `jobs` and `provisioning`, and
//! `full` enables everything.
//!
//! ```no_run
//! use community_databricks_sdk::WorkspaceClient;
//! use community_databricks_sdk::service::compute::{ListClustersRequest, State};
//! use futures_util::TryStreamExt;
//!
//! # async fn run() -> community_databricks_sdk::Result<()> {
//! // Host and credentials from DATABRICKS_* env vars or ~/.databrickscfg.
//! let w = WorkspaceClient::from_env().await?;
//! let mut clusters = w.clusters().list(ListClustersRequest::default().with_page_size(50));
//! while let Some(c) = clusters.try_next().await? {
//!     println!("{} {:?}", c.cluster_name.unwrap_or_default(), c.state);
//! }
//! # Ok(()) }
//! ```

mod accessors;
pub mod service;

use std::sync::{Arc, OnceLock};

use community_databricks_core::auth::DefaultCredentials;
use community_databricks_core::http::{Call, Method};
pub use community_databricks_core::{
    self as core, ApiClient, ApiError, Config, Error, ErrorKind, Result,
};

/// Client for workspace-level APIs.
#[derive(Debug, Clone)]
pub struct WorkspaceClient {
    api: ApiClient,
    workspace_id: Arc<OnceLock<i64>>,
}

impl WorkspaceClient {
    /// Configure entirely from the environment / `~/.databrickscfg`.
    pub async fn from_env() -> Result<Self> {
        Self::new(Config::default()).await
    }

    /// Build from a config; unset values are filled from the environment.
    pub async fn new(cfg: Config) -> Result<Self> {
        Ok(Self::from_api_client(ApiClient::new(cfg).await?))
    }

    /// Build with a custom credential chain.
    pub async fn with_credentials(cfg: Config, credentials: DefaultCredentials) -> Result<Self> {
        Ok(Self::from_api_client(
            ApiClient::with_credentials(cfg, credentials).await?,
        ))
    }

    /// Wrap an existing [`ApiClient`].
    #[must_use]
    pub fn from_api_client(api: ApiClient) -> Self {
        Self {
            api,
            workspace_id: Arc::default(),
        }
    }

    /// The underlying client, for calling endpoints the SDK doesn't cover.
    #[must_use]
    pub fn api_client(&self) -> &ApiClient {
        &self.api
    }

    /// The resolved configuration.
    #[must_use]
    pub fn config(&self) -> &Config {
        self.api.config()
    }

    /// The numeric ID of the workspace this client talks to (Go:
    /// `WorkspaceClient.CurrentWorkspaceID`), from the `X-Databricks-Org-Id`
    /// header of `GET /api/2.0/preview/scim/v2/Me`. Cached after the first
    /// call, including by clones of this client.
    pub async fn current_workspace_id(&self) -> Result<i64> {
        if let Some(id) = self.workspace_id.get() {
            return Ok(*id);
        }
        let call = Call::new(Method::GET, "/api/2.0/preview/scim/v2/Me".to_owned())
            .workspace()
            .query(vec![("excludedAttributes".into(), "entitlements".into())]);
        let (_, headers) = self
            .api
            .send_with_headers::<serde::de::IgnoredAny>(call)
            .await?;
        let id: i64 = community_databricks_core::http::header(&headers, "x-databricks-org-id")
            .ok_or_else(|| {
                Error::Config("the response had no numeric X-Databricks-Org-Id header".into())
            })?;
        Ok(*self.workspace_id.get_or_init(|| id))
    }

    /// Workspace users (Go: `w.Users`, the v1 facade over the same SCIM
    /// endpoints as [`users_v2`](Self::users_v2), which this returns).
    #[cfg(feature = "iam")]
    #[must_use]
    pub fn users(&self) -> service::iam::UsersV2Api {
        self.users_v2()
    }

    /// Workspace groups (Go: `w.Groups`); see [`users`](Self::users).
    #[cfg(feature = "iam")]
    #[must_use]
    pub fn groups(&self) -> service::iam::GroupsV2Api {
        self.groups_v2()
    }

    /// Workspace service principals (Go: `w.ServicePrincipals`); see
    /// [`users`](Self::users).
    #[cfg(feature = "iam")]
    #[must_use]
    pub fn service_principals(&self) -> service::iam::ServicePrincipalsV2Api {
        self.service_principals_v2()
    }
}

/// Client for account-level APIs.
#[derive(Debug, Clone)]
pub struct AccountClient {
    api: ApiClient,
    account_id: String,
}

impl AccountClient {
    /// Configure entirely from the environment / `~/.databrickscfg`.
    pub async fn from_env() -> Result<Self> {
        Self::new(Config::default()).await
    }

    /// Build from a config; `account_id` must resolve to a value.
    pub async fn new(cfg: Config) -> Result<Self> {
        Self::from_api_client(ApiClient::new(cfg).await?)
    }

    /// Build with a custom credential chain.
    pub async fn with_credentials(cfg: Config, credentials: DefaultCredentials) -> Result<Self> {
        Self::from_api_client(ApiClient::with_credentials(cfg, credentials).await?)
    }

    /// Wrap an existing [`ApiClient`].
    pub fn from_api_client(api: ApiClient) -> Result<Self> {
        let account_id = api
            .config()
            .account_id
            .clone()
            .filter(|a| !a.is_empty())
            .ok_or_else(|| {
                Error::Config(
                    "invalid Databricks Account configuration - host incorrect or account_id missing"
                        .into(),
                )
            })?;
        Ok(Self { api, account_id })
    }

    /// The underlying client.
    #[must_use]
    pub fn api_client(&self) -> &ApiClient {
        &self.api
    }

    /// A [`WorkspaceClient`] for one of this account's workspaces (Go:
    /// `AccountClient.GetWorkspaceClient`).
    ///
    /// The workspace host comes from the workspace's `deployment_name`
    /// (`https://{deployment}.cloud.databricks.com` and so on); on a
    /// unified host the account host itself serves the workspace. The
    /// workspace client shares this client's connection pool and rate
    /// limiter, and on a unified host its credentials as well.
    ///
    /// ```no_run
    /// # async fn run(a: community_databricks_sdk::AccountClient) -> community_databricks_sdk::Result<()> {
    /// use community_databricks_sdk::service::provisioning::GetWorkspaceRequest;
    /// let ws = a.workspaces().get(GetWorkspaceRequest::new(123)).await?;
    /// let w = a.get_workspace_client(&ws)?;
    /// # let _ = w; Ok(()) }
    /// ```
    #[cfg(feature = "provisioning")]
    pub fn get_workspace_client(
        &self,
        workspace: &service::provisioning::Workspace,
    ) -> Result<WorkspaceClient> {
        let id = workspace
            .workspace_id
            .ok_or_else(|| Error::Config("workspace has no workspace_id".into()))?;
        let deployment = workspace.deployment_name.as_deref().unwrap_or_default();
        let host = self.api.config().workspace_host(deployment);
        let azure_id = workspace.azure_resource_id();
        let api = self
            .api
            .for_workspace(host.as_deref(), &id.to_string(), azure_id.as_deref())?;
        Ok(WorkspaceClient::from_api_client(api))
    }

    /// The account ID requests are made against.
    #[must_use]
    pub fn account_id(&self) -> &str {
        &self.account_id
    }

    /// Account users (Go: `a.Users`, the v1 facade over the same SCIM
    /// endpoints as [`users_v2`](Self::users_v2), which this returns).
    #[cfg(feature = "iam")]
    #[must_use]
    pub fn users(&self) -> service::iam::AccountUsersV2Api {
        self.users_v2()
    }

    /// Account groups (Go: `a.Groups`); see [`users`](Self::users).
    #[cfg(feature = "iam")]
    #[must_use]
    pub fn groups(&self) -> service::iam::AccountGroupsV2Api {
        self.groups_v2()
    }

    /// Account service principals (Go: `a.ServicePrincipals`); see
    /// [`users`](Self::users).
    #[cfg(feature = "iam")]
    #[must_use]
    pub fn service_principals(&self) -> service::iam::AccountServicePrincipalsV2Api {
        self.service_principals_v2()
    }
}
