// Code generated by `cargo xtask codegen` from databricks-sdk-go v0.182.0 (OpenAPI 4648d66fa37e7683468dc92cc043c6aa7a34f301). DO NOT EDIT.

//! Databricks `supervisoragents` API: models and services.
//!
//! Generated from databricks-sdk-go v0.182.0; use it through the
//! [`community-databricks-sdk`](https://docs.rs/community-databricks-sdk) clients
//! (`community_databricks_sdk::service::supervisoragents`).

#![allow(
    clippy::all,
    clippy::pedantic,
    rustdoc::broken_intra_doc_links,
    rustdoc::invalid_html_tags,
    rustdoc::bare_urls,
    unused_imports
)]

use community_databricks_core::http::{Call, Method, path_param};
use community_databricks_core::paging::{self, Paged};
use community_databricks_core::{ApiClient, query, wait};

/// Databricks app. Supported app: custom mcp, custom agent.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct App {
    /// App name
    #[serde(default)]
    pub name: String,
}

impl App {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// `CreateExampleRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct CreateExampleRequest {
    /// The example to create under the parent Supervisor Agent.
    #[serde(default)]
    pub example: Example,
    /// Parent resource where this example will be created. Format:
    /// supervisor-agents/{supervisor_agent_id}
    #[serde(skip)]
    pub parent: String,
}

impl CreateExampleRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(example: impl Into<Example>, parent: impl Into<String>) -> Self {
        Self {
            example: example.into(),
            parent: parent.into(),
            ..Default::default()
        }
    }

    /// Set `example`.
    #[must_use]
    pub fn with_example(mut self, value: impl Into<Example>) -> Self {
        self.example = value.into();
        self
    }

    /// Set `parent`.
    #[must_use]
    pub fn with_parent(mut self, value: impl Into<String>) -> Self {
        self.parent = value.into();
        self
    }
}

/// `CreateSupervisorAgentRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct CreateSupervisorAgentRequest {
    /// The Supervisor Agent to create.
    #[serde(default)]
    pub supervisor_agent: SupervisorAgent,
}

impl CreateSupervisorAgentRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(supervisor_agent: impl Into<SupervisorAgent>) -> Self {
        Self {
            supervisor_agent: supervisor_agent.into(),
            ..Default::default()
        }
    }

    /// Set `supervisor_agent`.
    #[must_use]
    pub fn with_supervisor_agent(mut self, value: impl Into<SupervisorAgent>) -> Self {
        self.supervisor_agent = value.into();
        self
    }
}

/// `CreateToolRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct CreateToolRequest {
    /// Parent resource where this tool will be created. Format:
    /// supervisor-agents/{supervisor_agent_id}
    #[serde(skip)]
    pub parent: String,
    /// `tool`
    #[serde(default)]
    pub tool: Tool,
    /// The ID to use for the tool, which will become the final component of the
    /// tool's resource name.
    #[serde(skip)]
    pub tool_id: String,
}

impl CreateToolRequest {
    /// Set `parent`.
    #[must_use]
    pub fn with_parent(mut self, value: impl Into<String>) -> Self {
        self.parent = value.into();
        self
    }

    /// Set `tool`.
    #[must_use]
    pub fn with_tool(mut self, value: impl Into<Tool>) -> Self {
        self.tool = value.into();
        self
    }

    /// Set `tool_id`.
    #[must_use]
    pub fn with_tool_id(mut self, value: impl Into<String>) -> Self {
        self.tool_id = value.into();
        self
    }
}

/// `DeleteExampleRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct DeleteExampleRequest {
    /// The resource name of the example to delete. Format:
    /// supervisor-agents/{supervisor_agent_id}/examples/{example_id}
    #[serde(skip)]
    pub name: String,
}

impl DeleteExampleRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// `DeleteSupervisorAgentRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct DeleteSupervisorAgentRequest {
    /// The resource name of the Supervisor Agent. Format:
    /// supervisor-agents/{supervisor_agent_id}
    #[serde(skip)]
    pub name: String,
}

impl DeleteSupervisorAgentRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// `DeleteToolRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct DeleteToolRequest {
    /// The resource name of the Tool. Format:
    /// supervisor-agents/{supervisor_agent_id}/tools/{tool_id}
    #[serde(skip)]
    pub name: String,
}

impl DeleteToolRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// An example associated with a Supervisor Agent. Contains a question and
/// guidelines for how the agent should respond.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct Example {
    /// The universally unique identifier (UUID) of the example.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub example_id: Option<String>,
    /// Guidelines for answering the question.
    #[serde(default)]
    pub guidelines: Vec<String>,
    /// Full resource name:
    /// supervisor-agents/{supervisor_agent_id}/examples/{example_id}
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The example question.
    #[serde(default)]
    pub question: String,
}

impl Example {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(guidelines: impl Into<Vec<String>>, question: impl Into<String>) -> Self {
        Self {
            guidelines: guidelines.into(),
            question: question.into(),
            ..Default::default()
        }
    }

    /// Set `example_id`.
    #[must_use]
    pub fn with_example_id(mut self, value: impl Into<String>) -> Self {
        self.example_id = Some(value.into());
        self
    }

    /// Set `guidelines`.
    #[must_use]
    pub fn with_guidelines(mut self, value: impl Into<Vec<String>>) -> Self {
        self.guidelines = value.into();
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = Some(value.into());
        self
    }

    /// Set `question`.
    #[must_use]
    pub fn with_question(mut self, value: impl Into<String>) -> Self {
        self.question = value.into();
        self
    }
}

/// `GenieSpace`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GenieSpace {
    /// Deprecated: use space_id instead. Still REQUIRED for backward
    /// compatibility until a future API version removes it.
    #[serde(default)]
    pub id: String,
}

impl GenieSpace {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            ..Default::default()
        }
    }

    /// Set `id`.
    #[must_use]
    pub fn with_id(mut self, value: impl Into<String>) -> Self {
        self.id = value.into();
        self
    }
}

/// `GetExampleRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GetExampleRequest {
    /// The resource name of the example. Format:
    /// supervisor-agents/{supervisor_agent_id}/examples/{example_id}
    #[serde(skip)]
    pub name: String,
}

impl GetExampleRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// `GetSupervisorAgentPermissionLevelsRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GetSupervisorAgentPermissionLevelsRequest {
    /// The supervisor agent for which to get or manage permissions.
    #[serde(skip)]
    pub supervisor_agent_id: String,
}

impl GetSupervisorAgentPermissionLevelsRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(supervisor_agent_id: impl Into<String>) -> Self {
        Self {
            supervisor_agent_id: supervisor_agent_id.into(),
            ..Default::default()
        }
    }

    /// Set `supervisor_agent_id`.
    #[must_use]
    pub fn with_supervisor_agent_id(mut self, value: impl Into<String>) -> Self {
        self.supervisor_agent_id = value.into();
        self
    }
}

/// `GetSupervisorAgentPermissionLevelsResponse`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GetSupervisorAgentPermissionLevelsResponse {
    /// Specific permission levels
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub permission_levels: Vec<SupervisorAgentPermissionsDescription>,
}

impl GetSupervisorAgentPermissionLevelsResponse {
    /// Set `permission_levels`.
    #[must_use]
    pub fn with_permission_levels(
        mut self,
        value: impl Into<Vec<SupervisorAgentPermissionsDescription>>,
    ) -> Self {
        self.permission_levels = value.into();
        self
    }
}

/// `GetSupervisorAgentPermissionsRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GetSupervisorAgentPermissionsRequest {
    /// The supervisor agent for which to get or manage permissions.
    #[serde(skip)]
    pub supervisor_agent_id: String,
}

impl GetSupervisorAgentPermissionsRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(supervisor_agent_id: impl Into<String>) -> Self {
        Self {
            supervisor_agent_id: supervisor_agent_id.into(),
            ..Default::default()
        }
    }

    /// Set `supervisor_agent_id`.
    #[must_use]
    pub fn with_supervisor_agent_id(mut self, value: impl Into<String>) -> Self {
        self.supervisor_agent_id = value.into();
        self
    }
}

/// `GetSupervisorAgentRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GetSupervisorAgentRequest {
    /// The resource name of the Supervisor Agent. Format:
    /// supervisor-agents/{supervisor_agent_id}
    #[serde(skip)]
    pub name: String,
}

impl GetSupervisorAgentRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// `GetToolRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GetToolRequest {
    /// The resource name of the Tool. Format:
    /// supervisor-agents/{supervisor_agent_id}/tools/{tool_id}
    #[serde(skip)]
    pub name: String,
}

impl GetToolRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// `KnowledgeAssistant`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct KnowledgeAssistant {
    /// The ID of the knowledge assistant.
    #[serde(default)]
    pub knowledge_assistant_id: String,
    /// Deprecated: use knowledge_assistant_id instead.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub serving_endpoint_name: Option<String>,
}

impl KnowledgeAssistant {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(knowledge_assistant_id: impl Into<String>) -> Self {
        Self {
            knowledge_assistant_id: knowledge_assistant_id.into(),
            ..Default::default()
        }
    }

    /// Set `knowledge_assistant_id`.
    #[must_use]
    pub fn with_knowledge_assistant_id(mut self, value: impl Into<String>) -> Self {
        self.knowledge_assistant_id = value.into();
        self
    }

    /// Set `serving_endpoint_name`.
    #[must_use]
    pub fn with_serving_endpoint_name(mut self, value: impl Into<String>) -> Self {
        self.serving_endpoint_name = Some(value.into());
        self
    }
}

/// `ListExamplesRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListExamplesRequest {
    /// The maximum number of examples to return. If unspecified, at most 100
    /// examples will be returned. The maximum value is 100; values above 100
    /// will be coerced to 100.
    #[serde(skip)]
    pub page_size: Option<i64>,
    /// A page token, received from a previous `ListExamples` call. Provide this
    /// to retrieve the subsequent page. If unspecified, the first page will be
    /// returned.
    #[serde(skip)]
    pub page_token: Option<String>,
    /// Parent resource to list from. Format:
    /// supervisor-agents/{supervisor_agent_id}
    #[serde(skip)]
    pub parent: String,
}

impl ListExamplesRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(parent: impl Into<String>) -> Self {
        Self {
            parent: parent.into(),
            ..Default::default()
        }
    }

    /// Set `page_size`.
    #[must_use]
    pub fn with_page_size(mut self, value: i64) -> Self {
        self.page_size = Some(value);
        self
    }

    /// Set `page_token`.
    #[must_use]
    pub fn with_page_token(mut self, value: impl Into<String>) -> Self {
        self.page_token = Some(value.into());
        self
    }

    /// Set `parent`.
    #[must_use]
    pub fn with_parent(mut self, value: impl Into<String>) -> Self {
        self.parent = value.into();
        self
    }
}

/// A list of Supervisor Agent examples.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListExamplesResponse {
    /// `examples`
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub examples: Vec<Example>,
    /// `next_page_token`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
}

impl ListExamplesResponse {
    /// Set `examples`.
    #[must_use]
    pub fn with_examples(mut self, value: impl Into<Vec<Example>>) -> Self {
        self.examples = value.into();
        self
    }

    /// Set `next_page_token`.
    #[must_use]
    pub fn with_next_page_token(mut self, value: impl Into<String>) -> Self {
        self.next_page_token = Some(value.into());
        self
    }
}

/// `ListSupervisorAgentsRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListSupervisorAgentsRequest {
    /// The maximum number of supervisor agents to return. If unspecified, at
    /// most 100 supervisor agents will be returned. The maximum value is 100;
    /// values above 100 will be coerced to 100.
    #[serde(skip)]
    pub page_size: Option<i64>,
    /// A page token, received from a previous `ListSupervisorAgents` call.
    /// Provide this to retrieve the subsequent page. If unspecified, the first
    /// page will be returned.
    #[serde(skip)]
    pub page_token: Option<String>,
}

impl ListSupervisorAgentsRequest {
    /// Set `page_size`.
    #[must_use]
    pub fn with_page_size(mut self, value: i64) -> Self {
        self.page_size = Some(value);
        self
    }

    /// Set `page_token`.
    #[must_use]
    pub fn with_page_token(mut self, value: impl Into<String>) -> Self {
        self.page_token = Some(value.into());
        self
    }
}

/// `ListSupervisorAgentsResponse`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListSupervisorAgentsResponse {
    /// A token that can be sent as `page_token` to retrieve the next page. If
    /// this field is omitted, there are no subsequent pages.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    /// `supervisor_agents`
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub supervisor_agents: Vec<SupervisorAgent>,
}

impl ListSupervisorAgentsResponse {
    /// Set `next_page_token`.
    #[must_use]
    pub fn with_next_page_token(mut self, value: impl Into<String>) -> Self {
        self.next_page_token = Some(value.into());
        self
    }

    /// Set `supervisor_agents`.
    #[must_use]
    pub fn with_supervisor_agents(mut self, value: impl Into<Vec<SupervisorAgent>>) -> Self {
        self.supervisor_agents = value.into();
        self
    }
}

/// `ListToolsRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListToolsRequest {
    /// `page_size`
    #[serde(skip)]
    pub page_size: Option<i64>,
    /// `page_token`
    #[serde(skip)]
    pub page_token: Option<String>,
    /// Parent resource to list from. Format:
    /// supervisor-agents/{supervisor_agent_id}
    #[serde(skip)]
    pub parent: String,
}

impl ListToolsRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(parent: impl Into<String>) -> Self {
        Self {
            parent: parent.into(),
            ..Default::default()
        }
    }

    /// Set `page_size`.
    #[must_use]
    pub fn with_page_size(mut self, value: i64) -> Self {
        self.page_size = Some(value);
        self
    }

    /// Set `page_token`.
    #[must_use]
    pub fn with_page_token(mut self, value: impl Into<String>) -> Self {
        self.page_token = Some(value.into());
        self
    }

    /// Set `parent`.
    #[must_use]
    pub fn with_parent(mut self, value: impl Into<String>) -> Self {
        self.parent = value.into();
        self
    }
}

/// `ListToolsResponse`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListToolsResponse {
    /// `next_page_token`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    /// `tools`
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tools: Vec<Tool>,
}

impl ListToolsResponse {
    /// Set `next_page_token`.
    #[must_use]
    pub fn with_next_page_token(mut self, value: impl Into<String>) -> Self {
        self.next_page_token = Some(value.into());
        self
    }

    /// Set `tools`.
    #[must_use]
    pub fn with_tools(mut self, value: impl Into<Vec<Tool>>) -> Self {
        self.tools = value.into();
        self
    }
}

/// `SupervisorAgent`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct SupervisorAgent {
    /// Creation timestamp.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub create_time: Option<String>,
    /// The creator of the Supervisor Agent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub creator: Option<String>,
    /// Description of what this agent can do (user-facing).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The display name of the Supervisor Agent, unique at workspace level.
    #[serde(default)]
    pub display_name: String,
    /// The name of the supervisor agent's serving endpoint.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub endpoint_name: Option<String>,
    /// The MLflow experiment ID.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub experiment_id: Option<String>,
    /// Deprecated: Use supervisor_agent_id instead.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Optional natural-language instructions for the supervisor agent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub instructions: Option<String>,
    /// The resource name of the SupervisorAgent. Format:
    /// supervisor-agents/{supervisor_agent_id}
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The universally unique identifier (UUID) of the Supervisor Agent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub supervisor_agent_id: Option<String>,
}

impl SupervisorAgent {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(display_name: impl Into<String>) -> Self {
        Self {
            display_name: display_name.into(),
            ..Default::default()
        }
    }

    /// Set `create_time`.
    #[must_use]
    pub fn with_create_time(mut self, value: impl Into<String>) -> Self {
        self.create_time = Some(value.into());
        self
    }

    /// Set `creator`.
    #[must_use]
    pub fn with_creator(mut self, value: impl Into<String>) -> Self {
        self.creator = Some(value.into());
        self
    }

    /// Set `description`.
    #[must_use]
    pub fn with_description(mut self, value: impl Into<String>) -> Self {
        self.description = Some(value.into());
        self
    }

    /// Set `display_name`.
    #[must_use]
    pub fn with_display_name(mut self, value: impl Into<String>) -> Self {
        self.display_name = value.into();
        self
    }

    /// Set `endpoint_name`.
    #[must_use]
    pub fn with_endpoint_name(mut self, value: impl Into<String>) -> Self {
        self.endpoint_name = Some(value.into());
        self
    }

    /// Set `experiment_id`.
    #[must_use]
    pub fn with_experiment_id(mut self, value: impl Into<String>) -> Self {
        self.experiment_id = Some(value.into());
        self
    }

    /// Set `id`.
    #[must_use]
    pub fn with_id(mut self, value: impl Into<String>) -> Self {
        self.id = Some(value.into());
        self
    }

    /// Set `instructions`.
    #[must_use]
    pub fn with_instructions(mut self, value: impl Into<String>) -> Self {
        self.instructions = Some(value.into());
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = Some(value.into());
        self
    }

    /// Set `supervisor_agent_id`.
    #[must_use]
    pub fn with_supervisor_agent_id(mut self, value: impl Into<String>) -> Self {
        self.supervisor_agent_id = Some(value.into());
        self
    }
}

/// `SupervisorAgentAccessControlRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct SupervisorAgentAccessControlRequest {
    /// name of the group
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_name: Option<String>,
    /// `permission_level`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub permission_level: Option<SupervisorAgentPermissionLevel>,
    /// application ID of a service principal
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_principal_name: Option<String>,
    /// name of the user
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_name: Option<String>,
}

impl SupervisorAgentAccessControlRequest {
    /// Set `group_name`.
    #[must_use]
    pub fn with_group_name(mut self, value: impl Into<String>) -> Self {
        self.group_name = Some(value.into());
        self
    }

    /// Set `permission_level`.
    #[must_use]
    pub fn with_permission_level(
        mut self,
        value: impl Into<SupervisorAgentPermissionLevel>,
    ) -> Self {
        self.permission_level = Some(value.into());
        self
    }

    /// Set `service_principal_name`.
    #[must_use]
    pub fn with_service_principal_name(mut self, value: impl Into<String>) -> Self {
        self.service_principal_name = Some(value.into());
        self
    }

    /// Set `user_name`.
    #[must_use]
    pub fn with_user_name(mut self, value: impl Into<String>) -> Self {
        self.user_name = Some(value.into());
        self
    }
}

/// `SupervisorAgentAccessControlResponse`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct SupervisorAgentAccessControlResponse {
    /// All permissions.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub all_permissions: Vec<SupervisorAgentPermission>,
    /// Display name of the user or service principal.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// name of the group
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_name: Option<String>,
    /// Name of the service principal.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_principal_name: Option<String>,
    /// name of the user
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_name: Option<String>,
}

impl SupervisorAgentAccessControlResponse {
    /// Set `all_permissions`.
    #[must_use]
    pub fn with_all_permissions(
        mut self,
        value: impl Into<Vec<SupervisorAgentPermission>>,
    ) -> Self {
        self.all_permissions = value.into();
        self
    }

    /// Set `display_name`.
    #[must_use]
    pub fn with_display_name(mut self, value: impl Into<String>) -> Self {
        self.display_name = Some(value.into());
        self
    }

    /// Set `group_name`.
    #[must_use]
    pub fn with_group_name(mut self, value: impl Into<String>) -> Self {
        self.group_name = Some(value.into());
        self
    }

    /// Set `service_principal_name`.
    #[must_use]
    pub fn with_service_principal_name(mut self, value: impl Into<String>) -> Self {
        self.service_principal_name = Some(value.into());
        self
    }

    /// Set `user_name`.
    #[must_use]
    pub fn with_user_name(mut self, value: impl Into<String>) -> Self {
        self.user_name = Some(value.into());
        self
    }
}

/// `SupervisorAgentPermission`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct SupervisorAgentPermission {
    /// `inherited`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub inherited: Option<bool>,
    /// `inherited_from_object`
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub inherited_from_object: Vec<String>,
    /// `permission_level`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub permission_level: Option<SupervisorAgentPermissionLevel>,
}

impl SupervisorAgentPermission {
    /// Set `inherited`.
    #[must_use]
    pub fn with_inherited(mut self, value: bool) -> Self {
        self.inherited = Some(value);
        self
    }

    /// Set `inherited_from_object`.
    #[must_use]
    pub fn with_inherited_from_object(mut self, value: impl Into<Vec<String>>) -> Self {
        self.inherited_from_object = value.into();
        self
    }

    /// Set `permission_level`.
    #[must_use]
    pub fn with_permission_level(
        mut self,
        value: impl Into<SupervisorAgentPermissionLevel>,
    ) -> Self {
        self.permission_level = Some(value.into());
        self
    }
}

::community_databricks_core::open_enum! {
    /// Permission level
    pub enum SupervisorAgentPermissionLevel {
        /// `CAN_MANAGE`
        CanManage => "CAN_MANAGE",
        /// `CAN_QUERY`
        CanQuery => "CAN_QUERY",
    }
}

/// `SupervisorAgentPermissions`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct SupervisorAgentPermissions {
    /// `access_control_list`
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub access_control_list: Vec<SupervisorAgentAccessControlResponse>,
    /// `object_id`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object_id: Option<String>,
    /// `object_type`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object_type: Option<String>,
}

impl SupervisorAgentPermissions {
    /// Set `access_control_list`.
    #[must_use]
    pub fn with_access_control_list(
        mut self,
        value: impl Into<Vec<SupervisorAgentAccessControlResponse>>,
    ) -> Self {
        self.access_control_list = value.into();
        self
    }

    /// Set `object_id`.
    #[must_use]
    pub fn with_object_id(mut self, value: impl Into<String>) -> Self {
        self.object_id = Some(value.into());
        self
    }

    /// Set `object_type`.
    #[must_use]
    pub fn with_object_type(mut self, value: impl Into<String>) -> Self {
        self.object_type = Some(value.into());
        self
    }
}

/// `SupervisorAgentPermissionsDescription`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct SupervisorAgentPermissionsDescription {
    /// `description`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// `permission_level`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub permission_level: Option<SupervisorAgentPermissionLevel>,
}

impl SupervisorAgentPermissionsDescription {
    /// Set `description`.
    #[must_use]
    pub fn with_description(mut self, value: impl Into<String>) -> Self {
        self.description = Some(value.into());
        self
    }

    /// Set `permission_level`.
    #[must_use]
    pub fn with_permission_level(
        mut self,
        value: impl Into<SupervisorAgentPermissionLevel>,
    ) -> Self {
        self.permission_level = Some(value.into());
        self
    }
}

/// `SupervisorAgentPermissionsRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct SupervisorAgentPermissionsRequest {
    /// `access_control_list`
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub access_control_list: Vec<SupervisorAgentAccessControlRequest>,
    /// The supervisor agent for which to get or manage permissions.
    #[serde(skip)]
    pub supervisor_agent_id: String,
}

impl SupervisorAgentPermissionsRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(supervisor_agent_id: impl Into<String>) -> Self {
        Self {
            supervisor_agent_id: supervisor_agent_id.into(),
            ..Default::default()
        }
    }

    /// Set `access_control_list`.
    #[must_use]
    pub fn with_access_control_list(
        mut self,
        value: impl Into<Vec<SupervisorAgentAccessControlRequest>>,
    ) -> Self {
        self.access_control_list = value.into();
        self
    }

    /// Set `supervisor_agent_id`.
    #[must_use]
    pub fn with_supervisor_agent_id(mut self, value: impl Into<String>) -> Self {
        self.supervisor_agent_id = value.into();
        self
    }
}

/// `Tool`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct Tool {
    /// `app`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub app: Option<App>,
    /// Description of what this tool does (user-facing).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// `genie_space`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub genie_space: Option<GenieSpace>,
    /// Deprecated: Use tool_id instead.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// `knowledge_assistant`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub knowledge_assistant: Option<KnowledgeAssistant>,
    /// Full resource name:
    /// supervisor-agents/{supervisor_agent_id}/tools/{tool_id}
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// User specified id of the Tool.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_id: Option<String>,
    /// Tool type. Must be one of: "genie_space", "knowledge_assistant",
    /// "uc_function", "uc_connection", "uc_mcp", "app", "volume", "dashboard",
    /// "serving_endpoint", "table", "vector_search_index", "catalog", "schema",
    /// "supervisor_agent", "databricks_web_search", "skill". The legacy values
    /// "lakeview_dashboard", "uc_table", and "web_search" are also accepted and
    /// remain equivalent to "dashboard", "table", and "databricks_web_search"
    /// respectively. The "databricks_web_search" tool_type maps to the
    /// `web_search` spec field.
    #[serde(default)]
    pub tool_type: String,
    /// `uc_connection`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub uc_connection: Option<UcConnection>,
    /// `uc_function`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub uc_function: Option<UcFunction>,
    /// `volume`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub volume: Option<Volume>,
}

impl Tool {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(tool_type: impl Into<String>) -> Self {
        Self {
            tool_type: tool_type.into(),
            ..Default::default()
        }
    }

    /// Set `app`.
    #[must_use]
    pub fn with_app(mut self, value: impl Into<App>) -> Self {
        self.app = Some(value.into());
        self
    }

    /// Set `description`.
    #[must_use]
    pub fn with_description(mut self, value: impl Into<String>) -> Self {
        self.description = Some(value.into());
        self
    }

    /// Set `genie_space`.
    #[must_use]
    pub fn with_genie_space(mut self, value: impl Into<GenieSpace>) -> Self {
        self.genie_space = Some(value.into());
        self
    }

    /// Set `id`.
    #[must_use]
    pub fn with_id(mut self, value: impl Into<String>) -> Self {
        self.id = Some(value.into());
        self
    }

    /// Set `knowledge_assistant`.
    #[must_use]
    pub fn with_knowledge_assistant(mut self, value: impl Into<KnowledgeAssistant>) -> Self {
        self.knowledge_assistant = Some(value.into());
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = Some(value.into());
        self
    }

    /// Set `tool_id`.
    #[must_use]
    pub fn with_tool_id(mut self, value: impl Into<String>) -> Self {
        self.tool_id = Some(value.into());
        self
    }

    /// Set `tool_type`.
    #[must_use]
    pub fn with_tool_type(mut self, value: impl Into<String>) -> Self {
        self.tool_type = value.into();
        self
    }

    /// Set `uc_connection`.
    #[must_use]
    pub fn with_uc_connection(mut self, value: impl Into<UcConnection>) -> Self {
        self.uc_connection = Some(value.into());
        self
    }

    /// Set `uc_function`.
    #[must_use]
    pub fn with_uc_function(mut self, value: impl Into<UcFunction>) -> Self {
        self.uc_function = Some(value.into());
        self
    }

    /// Set `volume`.
    #[must_use]
    pub fn with_volume(mut self, value: impl Into<Volume>) -> Self {
        self.volume = Some(value.into());
        self
    }
}

/// Databricks UC connection. Supported connection: external mcp server.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct UcConnection {
    /// `name`
    #[serde(default)]
    pub name: String,
}

impl UcConnection {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// `UcFunction`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct UcFunction {
    /// Full uc function name
    #[serde(default)]
    pub name: String,
}

impl UcFunction {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// `UpdateExampleRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct UpdateExampleRequest {
    /// `example`
    #[serde(default)]
    pub example: Example,
    /// The resource name of the example to update. Format:
    /// supervisor-agents/{supervisor_agent_id}/examples/{example_id}
    #[serde(skip)]
    pub name: String,
    /// Comma-delimited list of fields to update on the example. Allowed values:
    /// `question`, `guidelines`. Examples: - `question` - `question,guidelines`
    #[serde(skip)]
    pub update_mask: String,
}

impl UpdateExampleRequest {
    /// Set `example`.
    #[must_use]
    pub fn with_example(mut self, value: impl Into<Example>) -> Self {
        self.example = value.into();
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }

    /// Set `update_mask`.
    #[must_use]
    pub fn with_update_mask(mut self, value: impl Into<String>) -> Self {
        self.update_mask = value.into();
        self
    }
}

/// `UpdateSupervisorAgentRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct UpdateSupervisorAgentRequest {
    /// The resource name of the SupervisorAgent. Format:
    /// supervisor-agents/{supervisor_agent_id}
    #[serde(skip)]
    pub name: String,
    /// The SupervisorAgent to update.
    #[serde(default)]
    pub supervisor_agent: SupervisorAgent,
    /// Field mask for fields to be updated.
    #[serde(skip)]
    pub update_mask: String,
}

impl UpdateSupervisorAgentRequest {
    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }

    /// Set `supervisor_agent`.
    #[must_use]
    pub fn with_supervisor_agent(mut self, value: impl Into<SupervisorAgent>) -> Self {
        self.supervisor_agent = value.into();
        self
    }

    /// Set `update_mask`.
    #[must_use]
    pub fn with_update_mask(mut self, value: impl Into<String>) -> Self {
        self.update_mask = value.into();
        self
    }
}

/// `UpdateToolRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct UpdateToolRequest {
    /// Full resource name:
    /// supervisor-agents/{supervisor_agent_id}/tools/{tool_id}
    #[serde(skip)]
    pub name: String,
    /// The Tool to update.
    #[serde(default)]
    pub tool: Tool,
    /// Field mask for fields to be updated.
    #[serde(skip)]
    pub update_mask: String,
}

impl UpdateToolRequest {
    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }

    /// Set `tool`.
    #[must_use]
    pub fn with_tool(mut self, value: impl Into<Tool>) -> Self {
        self.tool = value.into();
        self
    }

    /// Set `update_mask`.
    #[must_use]
    pub fn with_update_mask(mut self, value: impl Into<String>) -> Self {
        self.update_mask = value.into();
        self
    }
}

/// `Volume`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct Volume {
    /// Full uc volume name
    #[serde(default)]
    pub name: String,
}

impl Volume {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// Manage Supervisor Agents and related resources.
#[derive(Debug, Clone)]
pub struct SupervisorAgentsApi {
    api: ApiClient,
}

impl SupervisorAgentsApi {
    /// Wrap an [`ApiClient`].
    #[must_use]
    pub fn new(api: ApiClient) -> Self {
        Self { api }
    }

    /// Creates an example for a Supervisor Agent.
    ///
    /// `POST /api/2.1/{parent}/examples`
    pub async fn create_example(
        &self,
        request: CreateExampleRequest,
    ) -> ::community_databricks_core::Result<Example> {
        let path = format!(
            "/api/2.1/{}/examples",
            path_param(&request.parent.to_string(), true)
        );
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request.example)?;
        self.api.send::<Example>(call).await
    }

    /// Creates a new Supervisor Agent.
    ///
    /// `POST /api/2.1/supervisor-agents`
    pub async fn create_supervisor_agent(
        &self,
        request: CreateSupervisorAgentRequest,
    ) -> ::community_databricks_core::Result<SupervisorAgent> {
        let path = String::from("/api/2.1/supervisor-agents");
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request.supervisor_agent)?;
        self.api.send::<SupervisorAgent>(call).await
    }

    /// Creates a Tool under a Supervisor Agent. Specify one of "genie_space",
    /// "knowledge_assistant", "uc_function", "uc_connection", "app", "volume",
    /// "dashboard", "table", "vector_search_index", "catalog", "schema",
    /// "supervisor_agent", "databricks_web_search", "skill" in the request body. The
    /// legacy values "lakeview_dashboard", "uc_table", and "web_search" are also
    /// accepted and remain equivalent to "dashboard", "table", and
    /// "databricks_web_search" respectively. The "databricks_web_search" tool_type
    /// maps to the `web_search` spec field.
    ///
    /// `POST /api/2.1/{parent}/tools`
    pub async fn create_tool(
        &self,
        request: CreateToolRequest,
    ) -> ::community_databricks_core::Result<Tool> {
        let path = format!(
            "/api/2.1/{}/tools",
            path_param(&request.parent.to_string(), true)
        );
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.query(query::field("tool_id", &request.tool_id)?);
        call = call.json(&request.tool)?;
        self.api.send::<Tool>(call).await
    }

    /// Deletes an example from a Supervisor Agent.
    ///
    /// `DELETE /api/2.1/{name}`
    pub async fn delete_example(
        &self,
        request: DeleteExampleRequest,
    ) -> ::community_databricks_core::Result<()> {
        let path = format!("/api/2.1/{}", path_param(&request.name.to_string(), true));
        let call = Call::new(Method::DELETE, path).workspace();
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Deletes a Supervisor Agent.
    ///
    /// `DELETE /api/2.1/{name}`
    pub async fn delete_supervisor_agent(
        &self,
        request: DeleteSupervisorAgentRequest,
    ) -> ::community_databricks_core::Result<()> {
        let path = format!("/api/2.1/{}", path_param(&request.name.to_string(), true));
        let call = Call::new(Method::DELETE, path).workspace();
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Deletes a Tool.
    ///
    /// `DELETE /api/2.1/{name}`
    pub async fn delete_tool(
        &self,
        request: DeleteToolRequest,
    ) -> ::community_databricks_core::Result<()> {
        let path = format!("/api/2.1/{}", path_param(&request.name.to_string(), true));
        let call = Call::new(Method::DELETE, path).workspace();
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Gets an example from a Supervisor Agent.
    ///
    /// `GET /api/2.1/{name}`
    pub async fn get_example(
        &self,
        request: GetExampleRequest,
    ) -> ::community_databricks_core::Result<Example> {
        let path = format!("/api/2.1/{}", path_param(&request.name.to_string(), true));
        let call = Call::new(Method::GET, path).workspace();
        self.api.send::<Example>(call).await
    }

    /// Gets the permission levels that a user can have on an object.
    ///
    /// `GET /api/2.0/permissions/supervisor-agents/{supervisor_agent_id}/permissionLevels`
    pub async fn get_permission_levels(
        &self,
        request: GetSupervisorAgentPermissionLevelsRequest,
    ) -> ::community_databricks_core::Result<GetSupervisorAgentPermissionLevelsResponse> {
        let path = format!(
            "/api/2.0/permissions/supervisor-agents/{}/permissionLevels",
            path_param(&request.supervisor_agent_id.to_string(), false)
        );
        let call = Call::new(Method::GET, path).workspace();
        self.api
            .send::<GetSupervisorAgentPermissionLevelsResponse>(call)
            .await
    }

    /// Gets the permissions of a supervisor agent. Supervisor agents can inherit
    /// permissions from their root object.
    ///
    /// `GET /api/2.0/permissions/supervisor-agents/{supervisor_agent_id}`
    pub async fn get_permissions(
        &self,
        request: GetSupervisorAgentPermissionsRequest,
    ) -> ::community_databricks_core::Result<SupervisorAgentPermissions> {
        let path = format!(
            "/api/2.0/permissions/supervisor-agents/{}",
            path_param(&request.supervisor_agent_id.to_string(), false)
        );
        let call = Call::new(Method::GET, path).workspace();
        self.api.send::<SupervisorAgentPermissions>(call).await
    }

    /// Gets a Supervisor Agent.
    ///
    /// `GET /api/2.1/{name}`
    pub async fn get_supervisor_agent(
        &self,
        request: GetSupervisorAgentRequest,
    ) -> ::community_databricks_core::Result<SupervisorAgent> {
        let path = format!("/api/2.1/{}", path_param(&request.name.to_string(), true));
        let call = Call::new(Method::GET, path).workspace();
        self.api.send::<SupervisorAgent>(call).await
    }

    /// Gets a Tool.
    ///
    /// `GET /api/2.1/{name}`
    pub async fn get_tool(
        &self,
        request: GetToolRequest,
    ) -> ::community_databricks_core::Result<Tool> {
        let path = format!("/api/2.1/{}", path_param(&request.name.to_string(), true));
        let call = Call::new(Method::GET, path).workspace();
        self.api.send::<Tool>(call).await
    }

    /// One page of [`list_examples`](Self::list_examples).
    ///
    /// `GET /api/2.1/{parent}/examples`
    pub async fn list_examples_page(
        &self,
        request: ListExamplesRequest,
    ) -> ::community_databricks_core::Result<ListExamplesResponse> {
        let path = format!(
            "/api/2.1/{}/examples",
            path_param(&request.parent.to_string(), true)
        );
        let mut call = Call::new(Method::GET, path).workspace();
        call = call.query(query::field("page_size", &request.page_size)?);
        call = call.query(query::field("page_token", &request.page_token)?);
        self.api.send::<ListExamplesResponse>(call).await
    }

    /// Lists examples under a Supervisor Agent.
    ///
    /// This method is generated by Databricks SDK Code Generator.
    ///
    /// `GET /api/2.1/{parent}/examples`
    ///
    /// Returns a lazily paginated stream.
    #[must_use]
    pub fn list_examples(&self, request: ListExamplesRequest) -> Paged<'static, Example> {
        let this = Clone::clone(self);
        paging::paginate(
            request,
            move |req: &ListExamplesRequest| {
                let this = Clone::clone(&this);
                let req = req.clone();
                async move { this.list_examples_page(req).await }
            },
            |req, resp| {
                let items = resp.examples;
                let more = paging::next_token(resp.next_page_token, |t| req.page_token = Some(t));
                (items, more)
            },
        )
    }

    /// Every page of [`list_examples`](Self::list_examples), collected.
    pub async fn list_examples_all(
        &self,
        request: ListExamplesRequest,
    ) -> ::community_databricks_core::Result<Vec<Example>> {
        paging::collect(self.list_examples(request)).await
    }

    /// One page of [`list_supervisor_agents`](Self::list_supervisor_agents).
    ///
    /// `GET /api/2.1/supervisor-agents`
    pub async fn list_supervisor_agents_page(
        &self,
        request: ListSupervisorAgentsRequest,
    ) -> ::community_databricks_core::Result<ListSupervisorAgentsResponse> {
        let path = String::from("/api/2.1/supervisor-agents");
        let mut call = Call::new(Method::GET, path).workspace();
        call = call.query(query::field("page_size", &request.page_size)?);
        call = call.query(query::field("page_token", &request.page_token)?);
        self.api.send::<ListSupervisorAgentsResponse>(call).await
    }

    /// Lists Supervisor Agents.
    ///
    /// This method is generated by Databricks SDK Code Generator.
    ///
    /// `GET /api/2.1/supervisor-agents`
    ///
    /// Returns a lazily paginated stream.
    #[must_use]
    pub fn list_supervisor_agents(
        &self,
        request: ListSupervisorAgentsRequest,
    ) -> Paged<'static, SupervisorAgent> {
        let this = Clone::clone(self);
        paging::paginate(
            request,
            move |req: &ListSupervisorAgentsRequest| {
                let this = Clone::clone(&this);
                let req = req.clone();
                async move { this.list_supervisor_agents_page(req).await }
            },
            |req, resp| {
                let items = resp.supervisor_agents;
                let more = paging::next_token(resp.next_page_token, |t| req.page_token = Some(t));
                (items, more)
            },
        )
    }

    /// Every page of [`list_supervisor_agents`](Self::list_supervisor_agents), collected.
    pub async fn list_supervisor_agents_all(
        &self,
        request: ListSupervisorAgentsRequest,
    ) -> ::community_databricks_core::Result<Vec<SupervisorAgent>> {
        paging::collect(self.list_supervisor_agents(request)).await
    }

    /// One page of [`list_tools`](Self::list_tools).
    ///
    /// `GET /api/2.1/{parent}/tools`
    pub async fn list_tools_page(
        &self,
        request: ListToolsRequest,
    ) -> ::community_databricks_core::Result<ListToolsResponse> {
        let path = format!(
            "/api/2.1/{}/tools",
            path_param(&request.parent.to_string(), true)
        );
        let mut call = Call::new(Method::GET, path).workspace();
        call = call.query(query::field("page_size", &request.page_size)?);
        call = call.query(query::field("page_token", &request.page_token)?);
        self.api.send::<ListToolsResponse>(call).await
    }

    /// Lists Tools under a Supervisor Agent.
    ///
    /// This method is generated by Databricks SDK Code Generator.
    ///
    /// `GET /api/2.1/{parent}/tools`
    ///
    /// Returns a lazily paginated stream.
    #[must_use]
    pub fn list_tools(&self, request: ListToolsRequest) -> Paged<'static, Tool> {
        let this = Clone::clone(self);
        paging::paginate(
            request,
            move |req: &ListToolsRequest| {
                let this = Clone::clone(&this);
                let req = req.clone();
                async move { this.list_tools_page(req).await }
            },
            |req, resp| {
                let items = resp.tools;
                let more = paging::next_token(resp.next_page_token, |t| req.page_token = Some(t));
                (items, more)
            },
        )
    }

    /// Every page of [`list_tools`](Self::list_tools), collected.
    pub async fn list_tools_all(
        &self,
        request: ListToolsRequest,
    ) -> ::community_databricks_core::Result<Vec<Tool>> {
        paging::collect(self.list_tools(request)).await
    }

    /// Sets permissions on an object, replacing existing permissions if they exist.
    /// Deletes all direct permissions if none are specified. Objects can inherit
    /// permissions from their root object.
    ///
    /// `PUT /api/2.0/permissions/supervisor-agents/{supervisor_agent_id}`
    pub async fn set_permissions(
        &self,
        request: SupervisorAgentPermissionsRequest,
    ) -> ::community_databricks_core::Result<SupervisorAgentPermissions> {
        let path = format!(
            "/api/2.0/permissions/supervisor-agents/{}",
            path_param(&request.supervisor_agent_id.to_string(), false)
        );
        let mut call = Call::new(Method::PUT, path).workspace();
        call = call.json(&request)?;
        self.api.send::<SupervisorAgentPermissions>(call).await
    }

    /// Updates an example in a Supervisor Agent.
    ///
    /// `PATCH /api/2.1/{name}`
    pub async fn update_example(
        &self,
        request: UpdateExampleRequest,
    ) -> ::community_databricks_core::Result<Example> {
        let path = format!("/api/2.1/{}", path_param(&request.name.to_string(), true));
        let mut call = Call::new(Method::PATCH, path).workspace();
        call = call.query(query::field("update_mask", &request.update_mask)?);
        call = call.json(&request.example)?;
        self.api.send::<Example>(call).await
    }

    /// Updates the permissions on a supervisor agent. Supervisor agents can inherit
    /// permissions from their root object.
    ///
    /// `PATCH /api/2.0/permissions/supervisor-agents/{supervisor_agent_id}`
    pub async fn update_permissions(
        &self,
        request: SupervisorAgentPermissionsRequest,
    ) -> ::community_databricks_core::Result<SupervisorAgentPermissions> {
        let path = format!(
            "/api/2.0/permissions/supervisor-agents/{}",
            path_param(&request.supervisor_agent_id.to_string(), false)
        );
        let mut call = Call::new(Method::PATCH, path).workspace();
        call = call.json(&request)?;
        self.api.send::<SupervisorAgentPermissions>(call).await
    }

    /// Updates a Supervisor Agent. The fields that are required depend on the paths
    /// specified in `update_mask`. Only fields included in the mask will be updated.
    ///
    /// `PATCH /api/2.1/{name}`
    pub async fn update_supervisor_agent(
        &self,
        request: UpdateSupervisorAgentRequest,
    ) -> ::community_databricks_core::Result<SupervisorAgent> {
        let path = format!("/api/2.1/{}", path_param(&request.name.to_string(), true));
        let mut call = Call::new(Method::PATCH, path).workspace();
        call = call.query(query::field("update_mask", &request.update_mask)?);
        call = call.json(&request.supervisor_agent)?;
        self.api.send::<SupervisorAgent>(call).await
    }

    /// Updates a Tool. Only the `description` field can be updated. To change
    /// immutable fields such as tool type, spec, or tool ID, delete the tool and
    /// recreate it.
    ///
    /// `PATCH /api/2.1/{name}`
    pub async fn update_tool(
        &self,
        request: UpdateToolRequest,
    ) -> ::community_databricks_core::Result<Tool> {
        let path = format!("/api/2.1/{}", path_param(&request.name.to_string(), true));
        let mut call = Call::new(Method::PATCH, path).workspace();
        call = call.query(query::field("update_mask", &request.update_mask)?);
        call = call.json(&request.tool)?;
        self.api.send::<Tool>(call).await
    }
}
