// Code generated by `cargo xtask codegen` from databricks-sdk-go v0.182.0 (OpenAPI 4648d66fa37e7683468dc92cc043c6aa7a34f301). DO NOT EDIT.

//! Databricks `qualitymonitorv2` API: models and services.
//!
//! Generated from databricks-sdk-go v0.182.0; use it through the
//! [`databricks-sdk`](https://docs.rs/databricks-sdk) clients
//! (`databricks_sdk::service::qualitymonitorv2`).

#![allow(
    clippy::all,
    clippy::pedantic,
    rustdoc::broken_intra_doc_links,
    rustdoc::invalid_html_tags,
    rustdoc::bare_urls,
    unused_imports
)]

use databricks_core::http::{Call, Method, path_param};
use databricks_core::paging::{self, Paged};
use databricks_core::{ApiClient, query, wait};

/// `AnomalyDetectionConfig`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct AnomalyDetectionConfig {
    /// List of fully qualified table names to exclude from anomaly detection.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub excluded_table_full_names: Vec<String>,
    /// Run id of the last run of the workflow
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_run_id: Option<String>,
    /// The status of the last run of the workflow.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latest_run_status: Option<AnomalyDetectionRunStatus>,
}

impl AnomalyDetectionConfig {
    /// Set `excluded_table_full_names`.
    #[must_use]
    pub fn with_excluded_table_full_names(mut self, value: impl Into<Vec<String>>) -> Self {
        self.excluded_table_full_names = value.into();
        self
    }

    /// Set `last_run_id`.
    #[must_use]
    pub fn with_last_run_id(mut self, value: impl Into<String>) -> Self {
        self.last_run_id = Some(value.into());
        self
    }

    /// Set `latest_run_status`.
    #[must_use]
    pub fn with_latest_run_status(mut self, value: impl Into<AnomalyDetectionRunStatus>) -> Self {
        self.latest_run_status = Some(value.into());
        self
    }
}

::databricks_core::open_enum! {
    /// Status of Anomaly Detection Job Run
    pub enum AnomalyDetectionRunStatus {
        /// `ANOMALY_DETECTION_RUN_STATUS_CANCELED`
        AnomalyDetectionRunStatusCanceled => "ANOMALY_DETECTION_RUN_STATUS_CANCELED",
        /// `ANOMALY_DETECTION_RUN_STATUS_FAILED`
        AnomalyDetectionRunStatusFailed => "ANOMALY_DETECTION_RUN_STATUS_FAILED",
        /// `ANOMALY_DETECTION_RUN_STATUS_JOB_DELETED`
        AnomalyDetectionRunStatusJobDeleted => "ANOMALY_DETECTION_RUN_STATUS_JOB_DELETED",
        /// `ANOMALY_DETECTION_RUN_STATUS_PENDING`
        AnomalyDetectionRunStatusPending => "ANOMALY_DETECTION_RUN_STATUS_PENDING",
        /// `ANOMALY_DETECTION_RUN_STATUS_RUNNING`
        AnomalyDetectionRunStatusRunning => "ANOMALY_DETECTION_RUN_STATUS_RUNNING",
        /// `ANOMALY_DETECTION_RUN_STATUS_SUCCESS`
        AnomalyDetectionRunStatusSuccess => "ANOMALY_DETECTION_RUN_STATUS_SUCCESS",
        /// `ANOMALY_DETECTION_RUN_STATUS_UNKNOWN`
        AnomalyDetectionRunStatusUnknown => "ANOMALY_DETECTION_RUN_STATUS_UNKNOWN",
        /// `ANOMALY_DETECTION_RUN_STATUS_WORKSPACE_MISMATCH_ERROR`
        AnomalyDetectionRunStatusWorkspaceMismatchError => "ANOMALY_DETECTION_RUN_STATUS_WORKSPACE_MISMATCH_ERROR",
    }
}

/// `CreateQualityMonitorRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct CreateQualityMonitorRequest {
    /// `quality_monitor`
    #[serde(default)]
    pub quality_monitor: QualityMonitor,
}

impl CreateQualityMonitorRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(quality_monitor: impl Into<QualityMonitor>) -> Self {
        Self {
            quality_monitor: quality_monitor.into(),
            ..Default::default()
        }
    }

    /// Set `quality_monitor`.
    #[must_use]
    pub fn with_quality_monitor(mut self, value: impl Into<QualityMonitor>) -> Self {
        self.quality_monitor = value.into();
        self
    }
}

/// `DeleteQualityMonitorRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct DeleteQualityMonitorRequest {
    /// The uuid of the request object. For example, schema id.
    #[serde(skip)]
    pub object_id: String,
    /// The type of the monitored object. Can be one of the following: schema.
    #[serde(skip)]
    pub object_type: String,
}

impl DeleteQualityMonitorRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(object_id: impl Into<String>, object_type: impl Into<String>) -> Self {
        Self {
            object_id: object_id.into(),
            object_type: object_type.into(),
            ..Default::default()
        }
    }

    /// Set `object_id`.
    #[must_use]
    pub fn with_object_id(mut self, value: impl Into<String>) -> Self {
        self.object_id = value.into();
        self
    }

    /// Set `object_type`.
    #[must_use]
    pub fn with_object_type(mut self, value: impl Into<String>) -> Self {
        self.object_type = value.into();
        self
    }
}

/// `GetQualityMonitorRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GetQualityMonitorRequest {
    /// The uuid of the request object. For example, schema id.
    #[serde(skip)]
    pub object_id: String,
    /// The type of the monitored object. Can be one of the following: schema.
    #[serde(skip)]
    pub object_type: String,
}

impl GetQualityMonitorRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(object_id: impl Into<String>, object_type: impl Into<String>) -> Self {
        Self {
            object_id: object_id.into(),
            object_type: object_type.into(),
            ..Default::default()
        }
    }

    /// Set `object_id`.
    #[must_use]
    pub fn with_object_id(mut self, value: impl Into<String>) -> Self {
        self.object_id = value.into();
        self
    }

    /// Set `object_type`.
    #[must_use]
    pub fn with_object_type(mut self, value: impl Into<String>) -> Self {
        self.object_type = value.into();
        self
    }
}

/// `ListQualityMonitorRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListQualityMonitorRequest {
    /// `page_size`
    #[serde(skip)]
    pub page_size: Option<i64>,
    /// `page_token`
    #[serde(skip)]
    pub page_token: Option<String>,
}

impl ListQualityMonitorRequest {
    /// Set `page_size`.
    #[must_use]
    pub fn with_page_size(mut self, value: i64) -> Self {
        self.page_size = Some(value);
        self
    }

    /// Set `page_token`.
    #[must_use]
    pub fn with_page_token(mut self, value: impl Into<String>) -> Self {
        self.page_token = Some(value.into());
        self
    }
}

/// `ListQualityMonitorResponse`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListQualityMonitorResponse {
    /// `next_page_token`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    /// `quality_monitors`
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub quality_monitors: Vec<QualityMonitor>,
}

impl ListQualityMonitorResponse {
    /// Set `next_page_token`.
    #[must_use]
    pub fn with_next_page_token(mut self, value: impl Into<String>) -> Self {
        self.next_page_token = Some(value.into());
        self
    }

    /// Set `quality_monitors`.
    #[must_use]
    pub fn with_quality_monitors(mut self, value: impl Into<Vec<QualityMonitor>>) -> Self {
        self.quality_monitors = value.into();
        self
    }
}

/// `PercentNullValidityCheck`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct PercentNullValidityCheck {
    /// List of column names to check for null percentage
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub column_names: Vec<String>,
    /// Optional upper bound; we should use auto determined bounds for now
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub upper_bound: Option<f64>,
}

impl PercentNullValidityCheck {
    /// Set `column_names`.
    #[must_use]
    pub fn with_column_names(mut self, value: impl Into<Vec<String>>) -> Self {
        self.column_names = value.into();
        self
    }

    /// Set `upper_bound`.
    #[must_use]
    pub fn with_upper_bound(mut self, value: f64) -> Self {
        self.upper_bound = Some(value);
        self
    }
}

/// `QualityMonitor`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct QualityMonitor {
    /// `anomaly_detection_config`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub anomaly_detection_config: Option<AnomalyDetectionConfig>,
    /// The uuid of the request object. For example, schema id.
    #[serde(default)]
    pub object_id: String,
    /// The type of the monitored object. Can be one of the following: schema.
    #[serde(default)]
    pub object_type: String,
    /// Validity check configurations for anomaly detection.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub validity_check_configurations: Vec<ValidityCheckConfiguration>,
}

impl QualityMonitor {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(object_id: impl Into<String>, object_type: impl Into<String>) -> Self {
        Self {
            object_id: object_id.into(),
            object_type: object_type.into(),
            ..Default::default()
        }
    }

    /// Set `anomaly_detection_config`.
    #[must_use]
    pub fn with_anomaly_detection_config(
        mut self,
        value: impl Into<AnomalyDetectionConfig>,
    ) -> Self {
        self.anomaly_detection_config = Some(value.into());
        self
    }

    /// Set `object_id`.
    #[must_use]
    pub fn with_object_id(mut self, value: impl Into<String>) -> Self {
        self.object_id = value.into();
        self
    }

    /// Set `object_type`.
    #[must_use]
    pub fn with_object_type(mut self, value: impl Into<String>) -> Self {
        self.object_type = value.into();
        self
    }

    /// Set `validity_check_configurations`.
    #[must_use]
    pub fn with_validity_check_configurations(
        mut self,
        value: impl Into<Vec<ValidityCheckConfiguration>>,
    ) -> Self {
        self.validity_check_configurations = value.into();
        self
    }
}

/// `RangeValidityCheck`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct RangeValidityCheck {
    /// List of column names to check for range validity
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub column_names: Vec<String>,
    /// Lower bound for the range
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lower_bound: Option<f64>,
    /// Upper bound for the range
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub upper_bound: Option<f64>,
}

impl RangeValidityCheck {
    /// Set `column_names`.
    #[must_use]
    pub fn with_column_names(mut self, value: impl Into<Vec<String>>) -> Self {
        self.column_names = value.into();
        self
    }

    /// Set `lower_bound`.
    #[must_use]
    pub fn with_lower_bound(mut self, value: f64) -> Self {
        self.lower_bound = Some(value);
        self
    }

    /// Set `upper_bound`.
    #[must_use]
    pub fn with_upper_bound(mut self, value: f64) -> Self {
        self.upper_bound = Some(value);
        self
    }
}

/// `UniquenessValidityCheck`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct UniquenessValidityCheck {
    /// List of column names to check for uniqueness
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub column_names: Vec<String>,
}

impl UniquenessValidityCheck {
    /// Set `column_names`.
    #[must_use]
    pub fn with_column_names(mut self, value: impl Into<Vec<String>>) -> Self {
        self.column_names = value.into();
        self
    }
}

/// `UpdateQualityMonitorRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct UpdateQualityMonitorRequest {
    /// The uuid of the request object. For example, schema id.
    #[serde(skip)]
    pub object_id: String,
    /// The type of the monitored object. Can be one of the following: schema.
    #[serde(skip)]
    pub object_type: String,
    /// `quality_monitor`
    #[serde(default)]
    pub quality_monitor: QualityMonitor,
}

impl UpdateQualityMonitorRequest {
    /// Set `object_id`.
    #[must_use]
    pub fn with_object_id(mut self, value: impl Into<String>) -> Self {
        self.object_id = value.into();
        self
    }

    /// Set `object_type`.
    #[must_use]
    pub fn with_object_type(mut self, value: impl Into<String>) -> Self {
        self.object_type = value.into();
        self
    }

    /// Set `quality_monitor`.
    #[must_use]
    pub fn with_quality_monitor(mut self, value: impl Into<QualityMonitor>) -> Self {
        self.quality_monitor = value.into();
        self
    }
}

/// `ValidityCheckConfiguration`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ValidityCheckConfiguration {
    /// Can be set by system. Does not need to be user facing.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// `percent_null_validity_check`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub percent_null_validity_check: Option<PercentNullValidityCheck>,
    /// `range_validity_check`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub range_validity_check: Option<RangeValidityCheck>,
    /// `uniqueness_validity_check`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub uniqueness_validity_check: Option<UniquenessValidityCheck>,
}

impl ValidityCheckConfiguration {
    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = Some(value.into());
        self
    }

    /// Set `percent_null_validity_check`.
    #[must_use]
    pub fn with_percent_null_validity_check(
        mut self,
        value: impl Into<PercentNullValidityCheck>,
    ) -> Self {
        self.percent_null_validity_check = Some(value.into());
        self
    }

    /// Set `range_validity_check`.
    #[must_use]
    pub fn with_range_validity_check(mut self, value: impl Into<RangeValidityCheck>) -> Self {
        self.range_validity_check = Some(value.into());
        self
    }

    /// Set `uniqueness_validity_check`.
    #[must_use]
    pub fn with_uniqueness_validity_check(
        mut self,
        value: impl Into<UniquenessValidityCheck>,
    ) -> Self {
        self.uniqueness_validity_check = Some(value.into());
        self
    }
}

/// Deprecated: Please use the Data Quality Monitoring API instead (REST:
/// /api/data-quality/v1/monitors). Manage data quality of UC objects
/// (currently support `schema`).
#[derive(Debug, Clone)]
pub struct QualityMonitorV2Api {
    api: ApiClient,
}

impl QualityMonitorV2Api {
    /// Wrap an [`ApiClient`].
    #[must_use]
    pub fn new(api: ApiClient) -> Self {
        Self { api }
    }

    /// Deprecated: Use Data Quality Monitoring API instead
    /// (/api/data-quality/v1/monitors). Create a quality monitor on UC object.
    ///
    /// `POST /api/2.0/quality-monitors`
    pub async fn create_quality_monitor(
        &self,
        request: CreateQualityMonitorRequest,
    ) -> ::databricks_core::Result<QualityMonitor> {
        let path = String::from("/api/2.0/quality-monitors");
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request.quality_monitor)?;
        self.api.send::<QualityMonitor>(call).await
    }

    /// Deprecated: Use Data Quality Monitoring API instead
    /// (/api/data-quality/v1/monitors). Delete a quality monitor on UC object.
    ///
    /// `DELETE /api/2.0/quality-monitors/{object_type}/{object_id}`
    pub async fn delete_quality_monitor(
        &self,
        request: DeleteQualityMonitorRequest,
    ) -> ::databricks_core::Result<()> {
        let path = format!(
            "/api/2.0/quality-monitors/{}/{}",
            path_param(&request.object_type.to_string(), false),
            path_param(&request.object_id.to_string(), false)
        );
        let call = Call::new(Method::DELETE, path).workspace();
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Deprecated: Use Data Quality Monitoring API instead
    /// (/api/data-quality/v1/monitors). Read a quality monitor on UC object.
    ///
    /// `GET /api/2.0/quality-monitors/{object_type}/{object_id}`
    pub async fn get_quality_monitor(
        &self,
        request: GetQualityMonitorRequest,
    ) -> ::databricks_core::Result<QualityMonitor> {
        let path = format!(
            "/api/2.0/quality-monitors/{}/{}",
            path_param(&request.object_type.to_string(), false),
            path_param(&request.object_id.to_string(), false)
        );
        let call = Call::new(Method::GET, path).workspace();
        self.api.send::<QualityMonitor>(call).await
    }

    /// One page of [`list_quality_monitor`](Self::list_quality_monitor).
    ///
    /// `GET /api/2.0/quality-monitors`
    pub async fn list_quality_monitor_page(
        &self,
        request: ListQualityMonitorRequest,
    ) -> ::databricks_core::Result<ListQualityMonitorResponse> {
        let path = String::from("/api/2.0/quality-monitors");
        let mut call = Call::new(Method::GET, path).workspace();
        call = call.query(query::field("page_size", &request.page_size)?);
        call = call.query(query::field("page_token", &request.page_token)?);
        self.api.send::<ListQualityMonitorResponse>(call).await
    }

    /// Deprecated: Use Data Quality Monitoring API instead
    /// (/api/data-quality/v1/monitors). (Unimplemented) List quality monitors.
    ///
    /// This method is generated by Databricks SDK Code Generator.
    ///
    /// `GET /api/2.0/quality-monitors`
    ///
    /// Returns a lazily paginated stream.
    #[must_use]
    pub fn list_quality_monitor(
        &self,
        request: ListQualityMonitorRequest,
    ) -> Paged<'static, QualityMonitor> {
        let this = Clone::clone(self);
        paging::paginate(
            request,
            move |req: &ListQualityMonitorRequest| {
                let this = Clone::clone(&this);
                let req = req.clone();
                async move { this.list_quality_monitor_page(req).await }
            },
            |req, resp| {
                let items = resp.quality_monitors;
                let more = paging::next_token(resp.next_page_token, |t| req.page_token = Some(t));
                (items, more)
            },
        )
    }

    /// Every page of [`list_quality_monitor`](Self::list_quality_monitor), collected.
    pub async fn list_quality_monitor_all(
        &self,
        request: ListQualityMonitorRequest,
    ) -> ::databricks_core::Result<Vec<QualityMonitor>> {
        paging::collect(self.list_quality_monitor(request)).await
    }

    /// Deprecated: Use Data Quality Monitoring API instead
    /// (/api/data-quality/v1/monitors). (Unimplemented) Update a quality monitor on
    /// UC object.
    ///
    /// `PUT /api/2.0/quality-monitors/{object_type}/{object_id}`
    pub async fn update_quality_monitor(
        &self,
        request: UpdateQualityMonitorRequest,
    ) -> ::databricks_core::Result<QualityMonitor> {
        let path = format!(
            "/api/2.0/quality-monitors/{}/{}",
            path_param(&request.object_type.to_string(), false),
            path_param(&request.object_id.to_string(), false)
        );
        let mut call = Call::new(Method::PUT, path).workspace();
        call = call.json(&request.quality_monitor)?;
        self.api.send::<QualityMonitor>(call).await
    }
}
