// Code generated by `cargo xtask codegen` from databricks-sdk-go v0.182.0 (OpenAPI 4648d66fa37e7683468dc92cc043c6aa7a34f301). DO NOT EDIT.

//! Databricks `sandbox` API: models and services.
//!
//! Generated from databricks-sdk-go v0.182.0; use it through the
//! [`databricks-sdk`](https://docs.rs/databricks-sdk) clients
//! (`databricks_sdk::service::sandbox`).

#![allow(
    clippy::all,
    clippy::pedantic,
    rustdoc::broken_intra_doc_links,
    rustdoc::invalid_html_tags,
    rustdoc::bare_urls,
    unused_imports
)]

use databricks_core::http::{Call, Method, path_param};
use databricks_core::paging::{self, Paged};
use databricks_core::{ApiClient, query, wait};

/// `ComputeSpec`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ComputeSpec {
    /// Idle duration after which the sandbox is automatically terminated.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub inactivity_timeout: Option<String>,
}

impl ComputeSpec {
    /// Set `inactivity_timeout`.
    #[must_use]
    pub fn with_inactivity_timeout(mut self, value: impl Into<String>) -> Self {
        self.inactivity_timeout = Some(value.into());
        self
    }
}

/// `CreateSandboxRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct CreateSandboxRequest {
    /// The sandbox to create.
    #[serde(default)]
    pub sandbox: Sandbox,
    /// Client-supplied ID that becomes the final path segment of the resource
    /// name.
    #[serde(skip)]
    pub sandbox_id: String,
}

impl CreateSandboxRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(sandbox: impl Into<Sandbox>, sandbox_id: impl Into<String>) -> Self {
        Self {
            sandbox: sandbox.into(),
            sandbox_id: sandbox_id.into(),
            ..Default::default()
        }
    }

    /// Set `sandbox`.
    #[must_use]
    pub fn with_sandbox(mut self, value: impl Into<Sandbox>) -> Self {
        self.sandbox = value.into();
        self
    }

    /// Set `sandbox_id`.
    #[must_use]
    pub fn with_sandbox_id(mut self, value: impl Into<String>) -> Self {
        self.sandbox_id = value.into();
        self
    }
}

/// `DeleteSandboxRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct DeleteSandboxRequest {
    /// `name`
    #[serde(skip)]
    pub name: String,
}

impl DeleteSandboxRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

::databricks_core::open_enum! {
    /// Terminal status of a unary command execution.
    pub enum ExecuteCommandStatus {
        /// `EXECUTE_COMMAND_STATUS_COMPLETED`
        ExecuteCommandStatusCompleted => "EXECUTE_COMMAND_STATUS_COMPLETED",
        /// `EXECUTE_COMMAND_STATUS_FAILED`
        ExecuteCommandStatusFailed => "EXECUTE_COMMAND_STATUS_FAILED",
        /// `EXECUTE_COMMAND_STATUS_TIMED_OUT`
        ExecuteCommandStatusTimedOut => "EXECUTE_COMMAND_STATUS_TIMED_OUT",
    }
}

/// Request to run a command in the given sandbox and wait for it to finish.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ExecuteCommandSyncRequest {
    /// Arguments passed to `cmd`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub args: Vec<String>,
    /// Executable or command to run (e.g. `/bin/echo`, `python3`).
    #[serde(default)]
    pub cmd: String,
    /// Extra environment variables for the command's process, merged over the
    /// sandbox's default environment.
    #[serde(
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub envs: ::std::collections::BTreeMap<String, String>,
    /// Maximum time to wait for the command to finish. When it elapses the
    /// command is terminated and the response carries status `TIMED_OUT`. The
    /// server applies a default when unset and clamps to an upper bound;
    /// negative or otherwise invalid durations are rejected with
    /// `INVALID_ARGUMENT`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub execution_timeout: Option<String>,
    /// Resource name of the sandbox to run the command in, in the form
    /// `sandboxes/{sandbox_id}`. Bound from the URL path.
    #[serde(skip)]
    pub name: String,
}

impl ExecuteCommandSyncRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(cmd: impl Into<String>, name: impl Into<String>) -> Self {
        Self {
            cmd: cmd.into(),
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `args`.
    #[must_use]
    pub fn with_args(mut self, value: impl Into<Vec<String>>) -> Self {
        self.args = value.into();
        self
    }

    /// Set `cmd`.
    #[must_use]
    pub fn with_cmd(mut self, value: impl Into<String>) -> Self {
        self.cmd = value.into();
        self
    }

    /// Set `envs`.
    #[must_use]
    pub fn with_envs(
        mut self,
        value: impl Into<::std::collections::BTreeMap<String, String>>,
    ) -> Self {
        self.envs = value.into();
        self
    }

    /// Set `execution_timeout`.
    #[must_use]
    pub fn with_execution_timeout(mut self, value: impl Into<String>) -> Self {
        self.execution_timeout = Some(value.into());
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// Result of a completed unary command execution: captured output, exit code,
/// and terminal status.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ExecuteCommandSyncResponse {
    /// Daemon-generated identifier for this command execution, for correlation
    /// (for example in `ListCommands`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub command_id: Option<String>,
    /// Process exit code. Unset when the process was terminated by a signal
    /// (e.g. on `TIMED_OUT`) or never started (`FAILED`) rather than exiting
    /// normally.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i64>,
    /// Terminal status of the command execution. Always set on a successful
    /// response; never `EXECUTE_COMMAND_STATUS_UNSPECIFIED`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<ExecuteCommandStatus>,
    /// Captured standard error, with the same UTF-8 semantics as `stdout`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stderr: Option<String>,
    /// Captured standard output as UTF-8 text. Invalid UTF-8 bytes are replaced
    /// with the Unicode replacement character (U+FFFD).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stdout: Option<String>,
    /// True when `stdout` / `stderr` were truncated because the captured output
    /// exceeded the server's per-response size cap. The dropped output is not
    /// included in this response and is not recoverable through this unary API.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub truncated: Option<bool>,
}

impl ExecuteCommandSyncResponse {
    /// Set `command_id`.
    #[must_use]
    pub fn with_command_id(mut self, value: impl Into<String>) -> Self {
        self.command_id = Some(value.into());
        self
    }

    /// Set `exit_code`.
    #[must_use]
    pub fn with_exit_code(mut self, value: i64) -> Self {
        self.exit_code = Some(value);
        self
    }

    /// Set `status`.
    #[must_use]
    pub fn with_status(mut self, value: impl Into<ExecuteCommandStatus>) -> Self {
        self.status = Some(value.into());
        self
    }

    /// Set `stderr`.
    #[must_use]
    pub fn with_stderr(mut self, value: impl Into<String>) -> Self {
        self.stderr = Some(value.into());
        self
    }

    /// Set `stdout`.
    #[must_use]
    pub fn with_stdout(mut self, value: impl Into<String>) -> Self {
        self.stdout = Some(value.into());
        self
    }

    /// Set `truncated`.
    #[must_use]
    pub fn with_truncated(mut self, value: bool) -> Self {
        self.truncated = Some(value);
        self
    }
}

/// `GetSandboxRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GetSandboxRequest {
    /// `name`
    #[serde(skip)]
    pub name: String,
}

impl GetSandboxRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// `ListSandboxesRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListSandboxesRequest {
    /// `page_size`
    #[serde(skip)]
    pub page_size: Option<i64>,
    /// `page_token`
    #[serde(skip)]
    pub page_token: Option<String>,
}

impl ListSandboxesRequest {
    /// Set `page_size`.
    #[must_use]
    pub fn with_page_size(mut self, value: i64) -> Self {
        self.page_size = Some(value);
        self
    }

    /// Set `page_token`.
    #[must_use]
    pub fn with_page_token(mut self, value: impl Into<String>) -> Self {
        self.page_token = Some(value.into());
        self
    }
}

/// A list of Sandboxes.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListSandboxesResponse {
    /// `next_page_token`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    /// `sandboxes`
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub sandboxes: Vec<Sandbox>,
}

impl ListSandboxesResponse {
    /// Set `next_page_token`.
    #[must_use]
    pub fn with_next_page_token(mut self, value: impl Into<String>) -> Self {
        self.next_page_token = Some(value.into());
        self
    }

    /// Set `sandboxes`.
    #[must_use]
    pub fn with_sandboxes(mut self, value: impl Into<Vec<Sandbox>>) -> Self {
        self.sandboxes = value.into();
        self
    }
}

/// A Sandbox resource representing an execution environment.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct Sandbox {
    /// Output only. The creation time of the sandbox.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub create_time: Option<String>,
    /// Human-readable display label for the sandbox. At most 256 characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// The sandbox resource name, in the form `sandboxes/{sandbox_id}`. Derived
    /// from `sandbox_id`; any value supplied in a create or update request body
    /// is ignored.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The desired configuration of the sandbox, supplied by the caller at
    /// creation time.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub spec: Option<SandboxSpec>,
    /// The observed runtime state of the sandbox, populated by the server.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<SandboxStatus>,
    /// Output only. The last update time of the sandbox metadata and spec.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub update_time: Option<String>,
}

impl Sandbox {
    /// Set `create_time`.
    #[must_use]
    pub fn with_create_time(mut self, value: impl Into<String>) -> Self {
        self.create_time = Some(value.into());
        self
    }

    /// Set `display_name`.
    #[must_use]
    pub fn with_display_name(mut self, value: impl Into<String>) -> Self {
        self.display_name = Some(value.into());
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = Some(value.into());
        self
    }

    /// Set `spec`.
    #[must_use]
    pub fn with_spec(mut self, value: impl Into<SandboxSpec>) -> Self {
        self.spec = Some(value.into());
        self
    }

    /// Set `status`.
    #[must_use]
    pub fn with_status(mut self, value: impl Into<SandboxStatus>) -> Self {
        self.status = Some(value.into());
        self
    }

    /// Set `update_time`.
    #[must_use]
    pub fn with_update_time(mut self, value: impl Into<String>) -> Self {
        self.update_time = Some(value.into());
        self
    }
}

/// `SandboxSpec`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct SandboxSpec {
    /// Compute configuration (size, inactivity timeout) requested for the
    /// sandbox.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub compute: Option<ComputeSpec>,
}

impl SandboxSpec {
    /// Set `compute`.
    #[must_use]
    pub fn with_compute(mut self, value: impl Into<ComputeSpec>) -> Self {
        self.compute = Some(value.into());
        self
    }
}

::databricks_core::open_enum! {
    /// Lifecycle state of a Sandbox resource. STOPPING is the transient state while
    /// the sandbox is being stopped -- by a Stop request or inactivity
    /// auto-termination -- and settles to STOPPED once the operation completes.
    pub enum SandboxState {
        /// `SANDBOX_STATE_PENDING`
        SandboxStatePending => "SANDBOX_STATE_PENDING",
        /// `SANDBOX_STATE_RUNNING`
        SandboxStateRunning => "SANDBOX_STATE_RUNNING",
        /// `SANDBOX_STATE_STOPPED`
        SandboxStateStopped => "SANDBOX_STATE_STOPPED",
        /// `SANDBOX_STATE_STOPPING`
        SandboxStateStopping => "SANDBOX_STATE_STOPPING",
    }
}

/// `SandboxStatus`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct SandboxStatus {
    /// Lifecycle state of the sandbox.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<SandboxState>,
}

impl SandboxStatus {
    /// Set `state`.
    #[must_use]
    pub fn with_state(mut self, value: impl Into<SandboxState>) -> Self {
        self.state = Some(value.into());
        self
    }
}

/// A request to start a Sandbox.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct StartSandboxRequest {
    /// Resource name of the sandbox to start, in the form
    /// `sandboxes/{sandbox_id}`.
    #[serde(skip)]
    pub name: String,
}

impl StartSandboxRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// A request to stop a Sandbox.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct StopSandboxRequest {
    /// Resource name of the sandbox to stop, in the form
    /// `sandboxes/{sandbox_id}`.
    #[serde(skip)]
    pub name: String,
}

impl StopSandboxRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// `UpdateSandboxRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct UpdateSandboxRequest {
    /// Resource name of the sandbox to update, in the form
    /// `sandboxes/{sandbox_id}`.
    #[serde(skip)]
    pub name: String,
    /// The Sandbox resource carrying new field values. Only fields named in
    /// `update_mask` are read; unmasked fields are ignored.
    #[serde(default)]
    pub sandbox: Sandbox,
    /// Field paths to update. Must be a non-empty subset of: - display_name -
    /// spec.compute.inactivity_timeout Any other path returns
    /// INVALID_PARAMETER_VALUE.
    #[serde(skip)]
    pub update_mask: String,
}

impl UpdateSandboxRequest {
    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }

    /// Set `sandbox`.
    #[must_use]
    pub fn with_sandbox(mut self, value: impl Into<Sandbox>) -> Self {
        self.sandbox = value.into();
        self
    }

    /// Set `update_mask`.
    #[must_use]
    pub fn with_update_mask(mut self, value: impl Into<String>) -> Self {
        self.update_mask = value.into();
        self
    }
}

/// Create, manage, and control the lifecycle of sandboxes -- isolated,
/// pre-configured, low-latency Serverless compute environments for running
/// code.
#[derive(Debug, Clone)]
pub struct SandboxApi {
    api: ApiClient,
}

impl SandboxApi {
    /// Wrap an [`ApiClient`].
    #[must_use]
    pub fn new(api: ApiClient) -> Self {
        Self { api }
    }

    /// Creates a new Sandbox.
    ///
    /// `POST /api/2.0/sandboxes`
    pub async fn create_sandbox(
        &self,
        request: CreateSandboxRequest,
    ) -> ::databricks_core::Result<Sandbox> {
        let path = String::from("/api/2.0/sandboxes");
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.query(query::field("sandbox_id", &request.sandbox_id)?);
        call = call.json(&request.sandbox)?;
        self.api.send::<Sandbox>(call).await
    }

    /// Deletes a Sandbox.
    ///
    /// `DELETE /api/2.0/{name}`
    pub async fn delete_sandbox(
        &self,
        request: DeleteSandboxRequest,
    ) -> ::databricks_core::Result<()> {
        let path = format!("/api/2.0/{}", path_param(&request.name.to_string(), false));
        let call = Call::new(Method::DELETE, path).workspace();
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Runs a command in the sandbox and blocks until it exits, returning the
    /// captured stdout, stderr and exit code in a single response.
    ///
    /// `POST /api/2.0/sandbox-exec/{name}/exec-sync`
    pub async fn execute_command_sync(
        &self,
        request: ExecuteCommandSyncRequest,
    ) -> ::databricks_core::Result<ExecuteCommandSyncResponse> {
        let path = format!(
            "/api/2.0/sandbox-exec/{}/exec-sync",
            path_param(&request.name.to_string(), false)
        );
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request)?;
        self.api.send::<ExecuteCommandSyncResponse>(call).await
    }

    /// Retrieves a Sandbox by name.
    ///
    /// `GET /api/2.0/{name}`
    pub async fn get_sandbox(
        &self,
        request: GetSandboxRequest,
    ) -> ::databricks_core::Result<Sandbox> {
        let path = format!("/api/2.0/{}", path_param(&request.name.to_string(), false));
        let call = Call::new(Method::GET, path).workspace();
        self.api.send::<Sandbox>(call).await
    }

    /// One page of [`list_sandboxes`](Self::list_sandboxes).
    ///
    /// `GET /api/2.0/sandboxes`
    pub async fn list_sandboxes_page(
        &self,
        request: ListSandboxesRequest,
    ) -> ::databricks_core::Result<ListSandboxesResponse> {
        let path = String::from("/api/2.0/sandboxes");
        let mut call = Call::new(Method::GET, path).workspace();
        call = call.query(query::field("page_size", &request.page_size)?);
        call = call.query(query::field("page_token", &request.page_token)?);
        self.api.send::<ListSandboxesResponse>(call).await
    }

    /// Lists all Sandboxes.
    ///
    /// This method is generated by Databricks SDK Code Generator.
    ///
    /// `GET /api/2.0/sandboxes`
    ///
    /// Returns a lazily paginated stream.
    #[must_use]
    pub fn list_sandboxes(&self, request: ListSandboxesRequest) -> Paged<'static, Sandbox> {
        let this = Clone::clone(self);
        paging::paginate(
            request,
            move |req: &ListSandboxesRequest| {
                let this = Clone::clone(&this);
                let req = req.clone();
                async move { this.list_sandboxes_page(req).await }
            },
            |req, resp| {
                let items = resp.sandboxes;
                let more = paging::next_token(resp.next_page_token, |t| req.page_token = Some(t));
                (items, more)
            },
        )
    }

    /// Every page of [`list_sandboxes`](Self::list_sandboxes), collected.
    pub async fn list_sandboxes_all(
        &self,
        request: ListSandboxesRequest,
    ) -> ::databricks_core::Result<Vec<Sandbox>> {
        paging::collect(self.list_sandboxes(request)).await
    }

    /// Starts a previously stopped Sandbox under the same sandbox name. Returns
    /// NOT_FOUND if there is no stopped sandbox to start for the given name.
    ///
    /// `POST /api/2.0/{name}/start`
    pub async fn start_sandbox(
        &self,
        request: StartSandboxRequest,
    ) -> ::databricks_core::Result<Sandbox> {
        let path = format!(
            "/api/2.0/{}/start",
            path_param(&request.name.to_string(), false)
        );
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request)?;
        self.api.send::<Sandbox>(call).await
    }

    /// Stops a running Sandbox, preserving it so it can later be restarted with a
    /// Start request.
    ///
    /// `POST /api/2.0/{name}/stop`
    pub async fn stop_sandbox(
        &self,
        request: StopSandboxRequest,
    ) -> ::databricks_core::Result<Sandbox> {
        let path = format!(
            "/api/2.0/{}/stop",
            path_param(&request.name.to_string(), false)
        );
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request)?;
        self.api.send::<Sandbox>(call).await
    }

    /// Updates mutable fields on an existing Sandbox. Allowlisted update_mask paths
    /// today: display_name, spec.compute.inactivity_timeout. Returns
    /// INVALID_PARAMETER_VALUE for empty masks or unknown paths; NOT_FOUND if the
    /// sandbox does not exist.
    ///
    /// `PATCH /api/2.0/{name}`
    pub async fn update_sandbox(
        &self,
        request: UpdateSandboxRequest,
    ) -> ::databricks_core::Result<Sandbox> {
        let path = format!("/api/2.0/{}", path_param(&request.name.to_string(), false));
        let mut call = Call::new(Method::PATCH, path).workspace();
        call = call.query(query::field("update_mask", &request.update_mask)?);
        call = call.json(&request.sandbox)?;
        self.api.send::<Sandbox>(call).await
    }
}
