// Code generated by `cargo xtask codegen` from databricks-sdk-go v0.182.0 (OpenAPI 4648d66fa37e7683468dc92cc043c6aa7a34f301). DO NOT EDIT.

//! Databricks `files` API: models and services.
//!
//! Generated from databricks-sdk-go v0.182.0; use it through the
//! [`databricks-sdk`](https://docs.rs/databricks-sdk) clients
//! (`databricks_sdk::service::files`).

#![allow(
    clippy::all,
    clippy::pedantic,
    rustdoc::broken_intra_doc_links,
    rustdoc::invalid_html_tags,
    rustdoc::bare_urls,
    unused_imports
)]

use databricks_core::http::{Call, Method, path_param};
use databricks_core::paging::{self, Paged};
use databricks_core::{ApiClient, query, wait};

/// `AddBlock`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct AddBlock {
    /// The base64-encoded data to append to the stream. This has a limit of 1
    /// MB.
    #[serde(default)]
    pub data: String,
    /// The handle on an open stream.
    #[serde(deserialize_with = "::databricks_core::serde_num::i64", default)]
    pub handle: i64,
}

impl AddBlock {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(data: impl Into<String>, handle: i64) -> Self {
        Self {
            data: data.into(),
            handle,
            ..Default::default()
        }
    }

    /// Set `data`.
    #[must_use]
    pub fn with_data(mut self, value: impl Into<String>) -> Self {
        self.data = value.into();
        self
    }

    /// Set `handle`.
    #[must_use]
    pub fn with_handle(mut self, value: i64) -> Self {
        self.handle = value;
        self
    }
}

/// `Close`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct Close {
    /// The handle on an open stream.
    #[serde(deserialize_with = "::databricks_core::serde_num::i64", default)]
    pub handle: i64,
}

impl Close {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(handle: i64) -> Self {
        Self {
            handle,
            ..Default::default()
        }
    }

    /// Set `handle`.
    #[must_use]
    pub fn with_handle(mut self, value: i64) -> Self {
        self.handle = value;
        self
    }
}

/// `Create`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct Create {
    /// The flag that specifies whether to overwrite existing file/files.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub overwrite: Option<bool>,
    /// The path of the new file. The path should be the absolute DBFS path.
    #[serde(default)]
    pub path: String,
}

impl Create {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(path: impl Into<String>) -> Self {
        Self {
            path: path.into(),
            ..Default::default()
        }
    }

    /// Set `overwrite`.
    #[must_use]
    pub fn with_overwrite(mut self, value: bool) -> Self {
        self.overwrite = Some(value);
        self
    }

    /// Set `path`.
    #[must_use]
    pub fn with_path(mut self, value: impl Into<String>) -> Self {
        self.path = value.into();
        self
    }
}

/// `CreateDirectoryRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct CreateDirectoryRequest {
    /// The absolute path of a directory.
    #[serde(skip)]
    pub directory_path: String,
}

impl CreateDirectoryRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(directory_path: impl Into<String>) -> Self {
        Self {
            directory_path: directory_path.into(),
            ..Default::default()
        }
    }

    /// Set `directory_path`.
    #[must_use]
    pub fn with_directory_path(mut self, value: impl Into<String>) -> Self {
        self.directory_path = value.into();
        self
    }
}

/// `CreateResponse`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct CreateResponse {
    /// Handle which should subsequently be passed into the AddBlock and Close
    /// calls when writing to a file through a stream.
    #[serde(
        deserialize_with = "::databricks_core::serde_num::opt_i64",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub handle: Option<i64>,
}

impl CreateResponse {
    /// Set `handle`.
    #[must_use]
    pub fn with_handle(mut self, value: i64) -> Self {
        self.handle = Some(value);
        self
    }
}

/// `Delete`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct Delete {
    /// The path of the file or directory to delete. The path should be the
    /// absolute DBFS path.
    #[serde(default)]
    pub path: String,
    /// Whether or not to recursively delete the directory's contents. Deleting
    /// empty directories can be done without providing the recursive flag.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub recursive: Option<bool>,
}

impl Delete {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(path: impl Into<String>) -> Self {
        Self {
            path: path.into(),
            ..Default::default()
        }
    }

    /// Set `path`.
    #[must_use]
    pub fn with_path(mut self, value: impl Into<String>) -> Self {
        self.path = value.into();
        self
    }

    /// Set `recursive`.
    #[must_use]
    pub fn with_recursive(mut self, value: bool) -> Self {
        self.recursive = Some(value);
        self
    }
}

/// `DeleteDirectoryRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct DeleteDirectoryRequest {
    /// The absolute path of a directory.
    #[serde(skip)]
    pub directory_path: String,
}

impl DeleteDirectoryRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(directory_path: impl Into<String>) -> Self {
        Self {
            directory_path: directory_path.into(),
            ..Default::default()
        }
    }

    /// Set `directory_path`.
    #[must_use]
    pub fn with_directory_path(mut self, value: impl Into<String>) -> Self {
        self.directory_path = value.into();
        self
    }
}

/// `DeleteFileRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct DeleteFileRequest {
    /// The absolute path of the file.
    #[serde(skip)]
    pub file_path: String,
}

impl DeleteFileRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(file_path: impl Into<String>) -> Self {
        Self {
            file_path: file_path.into(),
            ..Default::default()
        }
    }

    /// Set `file_path`.
    #[must_use]
    pub fn with_file_path(mut self, value: impl Into<String>) -> Self {
        self.file_path = value.into();
        self
    }
}

/// `DirectoryEntry`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct DirectoryEntry {
    /// The length of the file in bytes. This field is omitted for directories.
    #[serde(
        deserialize_with = "::databricks_core::serde_num::opt_i64",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub file_size: Option<i64>,
    /// True if the path is a directory.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub is_directory: Option<bool>,
    /// Last modification time of given file in milliseconds since unix epoch.
    #[serde(
        deserialize_with = "::databricks_core::serde_num::opt_i64",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub last_modified: Option<i64>,
    /// The name of the file or directory. This is the last component of the
    /// path.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The absolute path of the file or directory.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
}

impl DirectoryEntry {
    /// Set `file_size`.
    #[must_use]
    pub fn with_file_size(mut self, value: i64) -> Self {
        self.file_size = Some(value);
        self
    }

    /// Set `is_directory`.
    #[must_use]
    pub fn with_is_directory(mut self, value: bool) -> Self {
        self.is_directory = Some(value);
        self
    }

    /// Set `last_modified`.
    #[must_use]
    pub fn with_last_modified(mut self, value: i64) -> Self {
        self.last_modified = Some(value);
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = Some(value.into());
        self
    }

    /// Set `path`.
    #[must_use]
    pub fn with_path(mut self, value: impl Into<String>) -> Self {
        self.path = Some(value.into());
        self
    }
}

/// `DownloadRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct DownloadRequest {
    /// The absolute path of the file.
    #[serde(skip)]
    pub file_path: String,
}

impl DownloadRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(file_path: impl Into<String>) -> Self {
        Self {
            file_path: file_path.into(),
            ..Default::default()
        }
    }

    /// Set `file_path`.
    #[must_use]
    pub fn with_file_path(mut self, value: impl Into<String>) -> Self {
        self.file_path = value.into();
        self
    }
}

/// `DownloadResponse`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct DownloadResponse {
    /// The length of the HTTP response body in bytes.
    #[serde(skip)]
    pub content_length: Option<i64>,
    /// `content-type`
    #[serde(skip)]
    pub content_type: Option<String>,
    /// `contents`
    #[serde(skip)]
    pub contents: ::serde_json::Value,
    /// The last modified time of the file in HTTP-date (RFC 7231) format.
    #[serde(skip)]
    pub last_modified: Option<String>,
}

impl DownloadResponse {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(contents: impl Into<::serde_json::Value>) -> Self {
        Self {
            contents: contents.into(),
            ..Default::default()
        }
    }

    /// Set `content_length`.
    #[must_use]
    pub fn with_content_length(mut self, value: i64) -> Self {
        self.content_length = Some(value);
        self
    }

    /// Set `content_type`.
    #[must_use]
    pub fn with_content_type(mut self, value: impl Into<String>) -> Self {
        self.content_type = Some(value.into());
        self
    }

    /// Set `contents`.
    #[must_use]
    pub fn with_contents(mut self, value: impl Into<::serde_json::Value>) -> Self {
        self.contents = value.into();
        self
    }

    /// Set `last_modified`.
    #[must_use]
    pub fn with_last_modified(mut self, value: impl Into<String>) -> Self {
        self.last_modified = Some(value.into());
        self
    }
}

/// `FileInfo`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct FileInfo {
    /// The length of the file in bytes. Set to 0 for directories.
    #[serde(
        deserialize_with = "::databricks_core::serde_num::opt_i64",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub file_size: Option<i64>,
    /// True if the path is a directory.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub is_dir: Option<bool>,
    /// Last modification time of given file in milliseconds since epoch.
    #[serde(
        deserialize_with = "::databricks_core::serde_num::opt_i64",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub modification_time: Option<i64>,
    /// The absolute path of the file or directory.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
}

impl FileInfo {
    /// Set `file_size`.
    #[must_use]
    pub fn with_file_size(mut self, value: i64) -> Self {
        self.file_size = Some(value);
        self
    }

    /// Set `is_dir`.
    #[must_use]
    pub fn with_is_dir(mut self, value: bool) -> Self {
        self.is_dir = Some(value);
        self
    }

    /// Set `modification_time`.
    #[must_use]
    pub fn with_modification_time(mut self, value: i64) -> Self {
        self.modification_time = Some(value);
        self
    }

    /// Set `path`.
    #[must_use]
    pub fn with_path(mut self, value: impl Into<String>) -> Self {
        self.path = Some(value.into());
        self
    }
}

/// `GetDirectoryMetadataRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GetDirectoryMetadataRequest {
    /// The absolute path of a directory.
    #[serde(skip)]
    pub directory_path: String,
}

impl GetDirectoryMetadataRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(directory_path: impl Into<String>) -> Self {
        Self {
            directory_path: directory_path.into(),
            ..Default::default()
        }
    }

    /// Set `directory_path`.
    #[must_use]
    pub fn with_directory_path(mut self, value: impl Into<String>) -> Self {
        self.directory_path = value.into();
        self
    }
}

/// `GetMetadataRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GetMetadataRequest {
    /// The absolute path of the file.
    #[serde(skip)]
    pub file_path: String,
}

impl GetMetadataRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(file_path: impl Into<String>) -> Self {
        Self {
            file_path: file_path.into(),
            ..Default::default()
        }
    }

    /// Set `file_path`.
    #[must_use]
    pub fn with_file_path(mut self, value: impl Into<String>) -> Self {
        self.file_path = value.into();
        self
    }
}

/// `GetMetadataResponse`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GetMetadataResponse {
    /// The length of the HTTP response body in bytes.
    #[serde(skip)]
    pub content_length: Option<i64>,
    /// `content-type`
    #[serde(skip)]
    pub content_type: Option<String>,
    /// The last modified time of the file in HTTP-date (RFC 7231) format.
    #[serde(skip)]
    pub last_modified: Option<String>,
}

impl GetMetadataResponse {
    /// Set `content_length`.
    #[must_use]
    pub fn with_content_length(mut self, value: i64) -> Self {
        self.content_length = Some(value);
        self
    }

    /// Set `content_type`.
    #[must_use]
    pub fn with_content_type(mut self, value: impl Into<String>) -> Self {
        self.content_type = Some(value.into());
        self
    }

    /// Set `last_modified`.
    #[must_use]
    pub fn with_last_modified(mut self, value: impl Into<String>) -> Self {
        self.last_modified = Some(value.into());
        self
    }
}

/// `GetStatusRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GetStatusRequest {
    /// The path of the file or directory. The path should be the absolute DBFS
    /// path.
    #[serde(skip)]
    pub path: String,
}

impl GetStatusRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(path: impl Into<String>) -> Self {
        Self {
            path: path.into(),
            ..Default::default()
        }
    }

    /// Set `path`.
    #[must_use]
    pub fn with_path(mut self, value: impl Into<String>) -> Self {
        self.path = value.into();
        self
    }
}

/// `ListDbfsRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListDbfsRequest {
    /// The path of the file or directory. The path should be the absolute DBFS
    /// path.
    #[serde(skip)]
    pub path: String,
}

impl ListDbfsRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(path: impl Into<String>) -> Self {
        Self {
            path: path.into(),
            ..Default::default()
        }
    }

    /// Set `path`.
    #[must_use]
    pub fn with_path(mut self, value: impl Into<String>) -> Self {
        self.path = value.into();
        self
    }
}

/// `ListDirectoryContentsRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListDirectoryContentsRequest {
    /// The absolute path of a directory.
    #[serde(skip)]
    pub directory_path: String,
    /// The maximum number of directory entries to return. The response may
    /// contain fewer entries. If the response contains a `next_page_token`,
    /// there may be more entries, even if fewer than `page_size` entries are in
    /// the response.
    ///
    /// We recommend not to set this value unless you are intentionally listing
    /// less than the complete directory contents.
    ///
    /// If unspecified, at most 1000 directory entries will be returned. The
    /// maximum value is 1000. Values above 1000 will be coerced to 1000.
    #[serde(skip)]
    pub page_size: Option<i64>,
    /// An opaque page token which was the `next_page_token` in the response of
    /// the previous request to list the contents of this directory. Provide this
    /// token to retrieve the next page of directory entries. When providing a
    /// `page_token`, all other parameters provided to the request must match the
    /// previous request. To list all of the entries in a directory, it is
    /// necessary to continue requesting pages of entries until the response
    /// contains no `next_page_token`. Note that the number of entries returned
    /// must not be used to determine when the listing is complete.
    #[serde(skip)]
    pub page_token: Option<String>,
}

impl ListDirectoryContentsRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(directory_path: impl Into<String>) -> Self {
        Self {
            directory_path: directory_path.into(),
            ..Default::default()
        }
    }

    /// Set `directory_path`.
    #[must_use]
    pub fn with_directory_path(mut self, value: impl Into<String>) -> Self {
        self.directory_path = value.into();
        self
    }

    /// Set `page_size`.
    #[must_use]
    pub fn with_page_size(mut self, value: i64) -> Self {
        self.page_size = Some(value);
        self
    }

    /// Set `page_token`.
    #[must_use]
    pub fn with_page_token(mut self, value: impl Into<String>) -> Self {
        self.page_token = Some(value.into());
        self
    }
}

/// `ListDirectoryResponse`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListDirectoryResponse {
    /// Array of DirectoryEntry.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub contents: Vec<DirectoryEntry>,
    /// A token, which can be sent as `page_token` to retrieve the next page.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
}

impl ListDirectoryResponse {
    /// Set `contents`.
    #[must_use]
    pub fn with_contents(mut self, value: impl Into<Vec<DirectoryEntry>>) -> Self {
        self.contents = value.into();
        self
    }

    /// Set `next_page_token`.
    #[must_use]
    pub fn with_next_page_token(mut self, value: impl Into<String>) -> Self {
        self.next_page_token = Some(value.into());
        self
    }
}

/// `ListStatusResponse`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListStatusResponse {
    /// A list of FileInfo's that describe contents of directory or file. See
    /// example above.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub files: Vec<FileInfo>,
}

impl ListStatusResponse {
    /// Set `files`.
    #[must_use]
    pub fn with_files(mut self, value: impl Into<Vec<FileInfo>>) -> Self {
        self.files = value.into();
        self
    }
}

/// `MkDirs`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct MkDirs {
    /// The path of the new directory. The path should be the absolute DBFS path.
    #[serde(default)]
    pub path: String,
}

impl MkDirs {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(path: impl Into<String>) -> Self {
        Self {
            path: path.into(),
            ..Default::default()
        }
    }

    /// Set `path`.
    #[must_use]
    pub fn with_path(mut self, value: impl Into<String>) -> Self {
        self.path = value.into();
        self
    }
}

/// `Move`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct Move {
    /// The destination path of the file or directory. The path should be the
    /// absolute DBFS path.
    #[serde(default)]
    pub destination_path: String,
    /// The source path of the file or directory. The path should be the absolute
    /// DBFS path.
    #[serde(default)]
    pub source_path: String,
}

impl Move {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(destination_path: impl Into<String>, source_path: impl Into<String>) -> Self {
        Self {
            destination_path: destination_path.into(),
            source_path: source_path.into(),
            ..Default::default()
        }
    }

    /// Set `destination_path`.
    #[must_use]
    pub fn with_destination_path(mut self, value: impl Into<String>) -> Self {
        self.destination_path = value.into();
        self
    }

    /// Set `source_path`.
    #[must_use]
    pub fn with_source_path(mut self, value: impl Into<String>) -> Self {
        self.source_path = value.into();
        self
    }
}

/// `Put`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct Put {
    /// This parameter might be absent, and instead a posted file will be used.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contents: Option<String>,
    /// The flag that specifies whether to overwrite existing file/files.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub overwrite: Option<bool>,
    /// The path of the new file. The path should be the absolute DBFS path.
    #[serde(default)]
    pub path: String,
}

impl Put {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(path: impl Into<String>) -> Self {
        Self {
            path: path.into(),
            ..Default::default()
        }
    }

    /// Set `contents`.
    #[must_use]
    pub fn with_contents(mut self, value: impl Into<String>) -> Self {
        self.contents = Some(value.into());
        self
    }

    /// Set `overwrite`.
    #[must_use]
    pub fn with_overwrite(mut self, value: bool) -> Self {
        self.overwrite = Some(value);
        self
    }

    /// Set `path`.
    #[must_use]
    pub fn with_path(mut self, value: impl Into<String>) -> Self {
        self.path = value.into();
        self
    }
}

/// `ReadDbfsRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ReadDbfsRequest {
    /// The number of bytes to read starting from the offset. This has a limit of
    /// 1 MB, and a default value of 0.5 MB.
    #[serde(skip)]
    pub length: Option<i64>,
    /// The offset to read from in bytes.
    #[serde(skip)]
    pub offset: Option<i64>,
    /// The path of the file to read. The path should be the absolute DBFS path.
    #[serde(skip)]
    pub path: String,
}

impl ReadDbfsRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(path: impl Into<String>) -> Self {
        Self {
            path: path.into(),
            ..Default::default()
        }
    }

    /// Set `length`.
    #[must_use]
    pub fn with_length(mut self, value: i64) -> Self {
        self.length = Some(value);
        self
    }

    /// Set `offset`.
    #[must_use]
    pub fn with_offset(mut self, value: i64) -> Self {
        self.offset = Some(value);
        self
    }

    /// Set `path`.
    #[must_use]
    pub fn with_path(mut self, value: impl Into<String>) -> Self {
        self.path = value.into();
        self
    }
}

/// `ReadResponse`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ReadResponse {
    /// The number of bytes read (could be less than ``length`` if we hit end of
    /// file). This refers to number of bytes read in unencoded version (response
    /// data is base64-encoded).
    #[serde(
        deserialize_with = "::databricks_core::serde_num::opt_i64",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub bytes_read: Option<i64>,
    /// The base64-encoded contents of the file read.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<String>,
}

impl ReadResponse {
    /// Set `bytes_read`.
    #[must_use]
    pub fn with_bytes_read(mut self, value: i64) -> Self {
        self.bytes_read = Some(value);
        self
    }

    /// Set `data`.
    #[must_use]
    pub fn with_data(mut self, value: impl Into<String>) -> Self {
        self.data = Some(value.into());
        self
    }
}

/// `UploadRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct UploadRequest {
    /// `contents`
    #[serde(skip)]
    pub contents: ::serde_json::Value,
    /// The absolute path of the file.
    #[serde(skip)]
    pub file_path: String,
    /// If true or unspecified, an existing file will be overwritten. If false,
    /// an error will be returned if the path points to an existing file.
    #[serde(skip)]
    pub overwrite: Option<bool>,
}

impl UploadRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(contents: impl Into<::serde_json::Value>, file_path: impl Into<String>) -> Self {
        Self {
            contents: contents.into(),
            file_path: file_path.into(),
            ..Default::default()
        }
    }

    /// Set `contents`.
    #[must_use]
    pub fn with_contents(mut self, value: impl Into<::serde_json::Value>) -> Self {
        self.contents = value.into();
        self
    }

    /// Set `file_path`.
    #[must_use]
    pub fn with_file_path(mut self, value: impl Into<String>) -> Self {
        self.file_path = value.into();
        self
    }

    /// Set `overwrite`.
    #[must_use]
    pub fn with_overwrite(mut self, value: bool) -> Self {
        self.overwrite = Some(value);
        self
    }
}

/// DBFS API makes it simple to interact with various data sources without
/// having to include a users credentials every time to read a file.
#[derive(Debug, Clone)]
pub struct DbfsApi {
    api: ApiClient,
}

impl DbfsApi {
    /// Wrap an [`ApiClient`].
    #[must_use]
    pub fn new(api: ApiClient) -> Self {
        Self { api }
    }

    /// Appends a block of data to the stream specified by the input handle. If the
    /// handle does not exist, this call will throw an exception with
    /// ``RESOURCE_DOES_NOT_EXIST``.
    ///
    /// If the block of data exceeds 1 MB, this call will throw an exception with
    /// ``MAX_BLOCK_SIZE_EXCEEDED``.
    ///
    /// `POST /api/2.0/dbfs/add-block`
    pub async fn add_block(&self, request: AddBlock) -> ::databricks_core::Result<()> {
        let path = String::from("/api/2.0/dbfs/add-block");
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request)?;
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Closes the stream specified by the input handle. If the handle does not
    /// exist, this call throws an exception with ``RESOURCE_DOES_NOT_EXIST``.
    ///
    /// `POST /api/2.0/dbfs/close`
    pub async fn close(&self, request: Close) -> ::databricks_core::Result<()> {
        let path = String::from("/api/2.0/dbfs/close");
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request)?;
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Opens a stream to write to a file and returns a handle to this stream. There
    /// is a 10 minute idle timeout on this handle. If a file or directory already
    /// exists on the given path and __overwrite__ is set to false, this call will
    /// throw an exception with ``RESOURCE_ALREADY_EXISTS``.
    ///
    /// A typical workflow for file upload would be:
    ///
    /// 1. Issue a ``create`` call and get a handle. 2. Issue one or more
    /// ``add-block`` calls with the handle you have. 3. Issue a ``close`` call with
    /// the handle you have.
    ///
    /// `POST /api/2.0/dbfs/create`
    pub async fn create(&self, request: Create) -> ::databricks_core::Result<CreateResponse> {
        let path = String::from("/api/2.0/dbfs/create");
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request)?;
        self.api.send::<CreateResponse>(call).await
    }

    /// Delete the file or directory (optionally recursively delete all files in the
    /// directory). This call throws an exception with `IO_ERROR` if the path is a
    /// non-empty directory and `recursive` is set to `false` or on other similar
    /// errors.
    ///
    /// When you delete a large number of files, the delete operation is done in
    /// increments. The call returns a response after approximately 45 seconds with
    /// an error message (503 Service Unavailable) asking you to re-invoke the delete
    /// operation until the directory structure is fully deleted.
    ///
    /// For operations that delete more than 10K files, we discourage using the DBFS
    /// REST API, but advise you to perform such operations in the context of a
    /// cluster, using the [File system utility
    /// (dbutils.fs)](/dev-tools/databricks-utils.html#dbutils-fs). `dbutils.fs`
    /// covers the functional scope of the DBFS REST API, but from notebooks. Running
    /// such operations using notebooks provides better control and manageability,
    /// such as selective deletes, and the possibility to automate periodic delete
    /// jobs.
    ///
    /// `POST /api/2.0/dbfs/delete`
    pub async fn delete(&self, request: Delete) -> ::databricks_core::Result<()> {
        let path = String::from("/api/2.0/dbfs/delete");
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request)?;
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Gets the file information for a file or directory. If the file or directory
    /// does not exist, this call throws an exception with `RESOURCE_DOES_NOT_EXIST`.
    ///
    /// `GET /api/2.0/dbfs/get-status`
    pub async fn get_status(
        &self,
        request: GetStatusRequest,
    ) -> ::databricks_core::Result<FileInfo> {
        let path = String::from("/api/2.0/dbfs/get-status");
        let mut call = Call::new(Method::GET, path).workspace();
        call = call.query(query::field("path", &request.path)?);
        self.api.send::<FileInfo>(call).await
    }

    /// One page of [`list`](Self::list).
    ///
    /// `GET /api/2.0/dbfs/list`
    pub async fn list_page(
        &self,
        request: ListDbfsRequest,
    ) -> ::databricks_core::Result<ListStatusResponse> {
        let path = String::from("/api/2.0/dbfs/list");
        let mut call = Call::new(Method::GET, path).workspace();
        call = call.query(query::field("path", &request.path)?);
        self.api.send::<ListStatusResponse>(call).await
    }

    /// List the contents of a directory, or details of the file. If the file or
    /// directory does not exist, this call throws an exception with
    /// `RESOURCE_DOES_NOT_EXIST`.
    ///
    /// When calling list on a large directory, the list operation will time out
    /// after approximately 60 seconds. We strongly recommend using list only on
    /// directories containing less than 10K files and discourage using the DBFS REST
    /// API for operations that list more than 10K files. Instead, we recommend that
    /// you perform such operations in the context of a cluster, using the [File
    /// system utility (dbutils.fs)](/dev-tools/databricks-utils.html#dbutils-fs),
    /// which provides the same functionality without timing out.
    ///
    /// This method is generated by Databricks SDK Code Generator.
    ///
    /// `GET /api/2.0/dbfs/list`
    ///
    /// Returns a lazily paginated stream.
    #[must_use]
    pub fn list(&self, request: ListDbfsRequest) -> Paged<'static, FileInfo> {
        let this = Clone::clone(self);
        paging::paginate(
            request,
            move |req: &ListDbfsRequest| {
                let this = Clone::clone(&this);
                let req = req.clone();
                async move { this.list_page(req).await }
            },
            |_req, resp| (resp.files, false),
        )
    }

    /// Every page of [`list`](Self::list), collected.
    pub async fn list_all(
        &self,
        request: ListDbfsRequest,
    ) -> ::databricks_core::Result<Vec<FileInfo>> {
        paging::collect(self.list(request)).await
    }

    /// Creates the given directory and necessary parent directories if they do not
    /// exist. If a file (not a directory) exists at any prefix of the input path,
    /// this call throws an exception with `RESOURCE_ALREADY_EXISTS`. **Note**: If
    /// this operation fails, it might have succeeded in creating some of the
    /// necessary parent directories.
    ///
    /// `POST /api/2.0/dbfs/mkdirs`
    pub async fn mkdirs(&self, request: MkDirs) -> ::databricks_core::Result<()> {
        let path = String::from("/api/2.0/dbfs/mkdirs");
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request)?;
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Moves a file from one location to another location within DBFS. If the source
    /// file does not exist, this call throws an exception with
    /// `RESOURCE_DOES_NOT_EXIST`. If a file already exists in the destination path,
    /// this call throws an exception with `RESOURCE_ALREADY_EXISTS`. If the given
    /// source path is a directory, this call always recursively moves all files.
    ///
    /// `POST /api/2.0/dbfs/move`
    pub async fn move_(&self, request: Move) -> ::databricks_core::Result<()> {
        let path = String::from("/api/2.0/dbfs/move");
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request)?;
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Uploads a file through the use of multipart form post. It is mainly used for
    /// streaming uploads, but can also be used as a convenient single call for data
    /// upload.
    ///
    /// Alternatively you can pass contents as base64 string.
    ///
    /// The amount of data that can be passed (when not streaming) using the
    /// __contents__ parameter is limited to 1 MB. `MAX_BLOCK_SIZE_EXCEEDED` will be
    /// thrown if this limit is exceeded.
    ///
    /// If you want to upload large files, use the streaming upload. For details, see
    /// :method:dbfs/create, :method:dbfs/addBlock, :method:dbfs/close.
    ///
    /// `POST /api/2.0/dbfs/put`
    pub async fn put(&self, request: Put) -> ::databricks_core::Result<()> {
        let path = String::from("/api/2.0/dbfs/put");
        let mut call = Call::new(Method::POST, path).workspace();
        call = call.json(&request)?;
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Returns the contents of a file. If the file does not exist, this call throws
    /// an exception with `RESOURCE_DOES_NOT_EXIST`. If the path is a directory, the
    /// read length is negative, or if the offset is negative, this call throws an
    /// exception with `INVALID_PARAMETER_VALUE`. If the read length exceeds 1 MB,
    /// this call throws an exception with `MAX_READ_SIZE_EXCEEDED`.
    ///
    /// If `offset + length` exceeds the number of bytes in a file, it reads the
    /// contents until the end of file.
    ///
    /// `GET /api/2.0/dbfs/read`
    pub async fn read(&self, request: ReadDbfsRequest) -> ::databricks_core::Result<ReadResponse> {
        let path = String::from("/api/2.0/dbfs/read");
        let mut call = Call::new(Method::GET, path).workspace();
        call = call.query(query::field("length", &request.length)?);
        call = call.query(query::field("offset", &request.offset)?);
        call = call.query(query::field("path", &request.path)?);
        self.api.send::<ReadResponse>(call).await
    }
}

/// The Files API is a standard HTTP API that allows you to read, write,
/// list, and delete files and directories by referring to their URI. The API
/// makes working with file content as raw bytes easier and more efficient.
///
/// The API supports [Unity Catalog volumes], where files and directories to
/// operate on are specified using their volume URI path, which follows the
/// format
/// /Volumes/&lt;catalog_name&gt;/&lt;schema_name&gt;/&lt;volume_name&gt;/&lt;path_to_file&gt;.
///
/// The Files API has two distinct endpoints, one for working with files
/// (`/fs/files`) and another one for working with directories
/// (`/fs/directories`). Both endpoints use the standard HTTP methods GET,
/// HEAD, PUT, and DELETE to manage files and directories specified using
/// their URI path. The path is always absolute.
///
/// Use of Files API may incur Databricks data transfer charges.
///
/// [Unity Catalog volumes]: https://docs.databricks.com/en/connect/unity-catalog/volumes.html
#[derive(Debug, Clone)]
pub struct FilesApi {
    api: ApiClient,
}

impl FilesApi {
    /// Wrap an [`ApiClient`].
    #[must_use]
    pub fn new(api: ApiClient) -> Self {
        Self { api }
    }

    /// Creates an empty directory. If necessary, also creates any parent directories
    /// of the new, empty directory (like the shell command `mkdir -p`). If called on
    /// an existing directory, returns a success response; this method is idempotent
    /// (it will succeed if the directory already exists).
    ///
    /// `PUT /api/2.0/fs/directories{directory_path}`
    pub async fn create_directory(
        &self,
        request: CreateDirectoryRequest,
    ) -> ::databricks_core::Result<()> {
        let path = format!(
            "/api/2.0/fs/directories{}",
            path_param(&request.directory_path.to_string(), true)
        );
        let mut call = Call::new(Method::PUT, path).workspace();
        call = call.json(&request)?;
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Deletes a file. If the request is successful, there is no response body.
    ///
    /// `DELETE /api/2.0/fs/files{file_path}`
    pub async fn delete(&self, request: DeleteFileRequest) -> ::databricks_core::Result<()> {
        let path = format!(
            "/api/2.0/fs/files{}",
            path_param(&request.file_path.to_string(), true)
        );
        let call = Call::new(Method::DELETE, path).workspace();
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Deletes an empty directory.
    ///
    /// To delete a non-empty directory, first delete all of its contents. This can
    /// be done by listing the directory contents and deleting each file and
    /// subdirectory recursively.
    ///
    /// `DELETE /api/2.0/fs/directories{directory_path}`
    pub async fn delete_directory(
        &self,
        request: DeleteDirectoryRequest,
    ) -> ::databricks_core::Result<()> {
        let path = format!(
            "/api/2.0/fs/directories{}",
            path_param(&request.directory_path.to_string(), true)
        );
        let call = Call::new(Method::DELETE, path).workspace();
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Get the metadata of a directory. The response HTTP headers contain the
    /// metadata. There is no response body.
    ///
    /// This method is useful to check if a directory exists and the caller has
    /// access to it.
    ///
    /// If you wish to ensure the directory exists, you can instead use `PUT`, which
    /// will create the directory if it does not exist, and is idempotent (it will
    /// succeed if the directory already exists).
    ///
    /// `HEAD /api/2.0/fs/directories{directory_path}`
    pub async fn get_directory_metadata(
        &self,
        request: GetDirectoryMetadataRequest,
    ) -> ::databricks_core::Result<()> {
        let path = format!(
            "/api/2.0/fs/directories{}",
            path_param(&request.directory_path.to_string(), true)
        );
        let call = Call::new(Method::HEAD, path).workspace();
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Get the metadata of a file. The response HTTP headers contain the metadata.
    /// There is no response body.
    ///
    /// `HEAD /api/2.0/fs/files{file_path}`
    pub async fn get_metadata(
        &self,
        request: GetMetadataRequest,
    ) -> ::databricks_core::Result<GetMetadataResponse> {
        let path = format!(
            "/api/2.0/fs/files{}",
            path_param(&request.file_path.to_string(), true)
        );
        let call = Call::new(Method::HEAD, path).workspace();
        {
            let (mut resp, headers) = self
                .api
                .send_with_headers::<GetMetadataResponse>(call)
                .await?;
            resp.content_length = ::databricks_core::http::header(&headers, "content-length");
            resp.content_type = ::databricks_core::http::header(&headers, "content-type");
            resp.last_modified = ::databricks_core::http::header(&headers, "last-modified");
            Ok(resp)
        }
    }

    /// One page of [`list_directory_contents`](Self::list_directory_contents).
    ///
    /// `GET /api/2.0/fs/directories{directory_path}`
    pub async fn list_directory_contents_page(
        &self,
        request: ListDirectoryContentsRequest,
    ) -> ::databricks_core::Result<ListDirectoryResponse> {
        let path = format!(
            "/api/2.0/fs/directories{}",
            path_param(&request.directory_path.to_string(), true)
        );
        let mut call = Call::new(Method::GET, path).workspace();
        call = call.query(query::field("page_size", &request.page_size)?);
        call = call.query(query::field("page_token", &request.page_token)?);
        self.api.send::<ListDirectoryResponse>(call).await
    }

    /// Returns the contents of a directory. If there is no directory at the
    /// specified path, the API returns an HTTP 404 error.
    ///
    /// This method is generated by Databricks SDK Code Generator.
    ///
    /// `GET /api/2.0/fs/directories{directory_path}`
    ///
    /// Returns a lazily paginated stream.
    #[must_use]
    pub fn list_directory_contents(
        &self,
        request: ListDirectoryContentsRequest,
    ) -> Paged<'static, DirectoryEntry> {
        let this = Clone::clone(self);
        paging::paginate(
            request,
            move |req: &ListDirectoryContentsRequest| {
                let this = Clone::clone(&this);
                let req = req.clone();
                async move { this.list_directory_contents_page(req).await }
            },
            |req, resp| {
                let items = resp.contents;
                let more = paging::next_token(resp.next_page_token, |t| req.page_token = Some(t));
                (items, more)
            },
        )
    }

    /// Every page of [`list_directory_contents`](Self::list_directory_contents), collected.
    pub async fn list_directory_contents_all(
        &self,
        request: ListDirectoryContentsRequest,
    ) -> ::databricks_core::Result<Vec<DirectoryEntry>> {
        paging::collect(self.list_directory_contents(request)).await
    }
}
