// Code generated by `cargo xtask codegen` from databricks-sdk-go v0.182.0 (OpenAPI 4648d66fa37e7683468dc92cc043c6aa7a34f301). DO NOT EDIT.

//! Databricks `networking` API: models and services.
//!
//! Generated from databricks-sdk-go v0.182.0; use it through the
//! [`community-databricks-sdk`](https://docs.rs/community-databricks-sdk) clients
//! (`community_databricks_sdk::service::networking`).

#![allow(
    clippy::all,
    clippy::pedantic,
    rustdoc::broken_intra_doc_links,
    rustdoc::invalid_html_tags,
    rustdoc::bare_urls,
    unused_imports
)]

use community_databricks_core::http::{Call, Method, path_param};
use community_databricks_core::paging::{self, Paged};
use community_databricks_core::{ApiClient, query, wait};

/// `AwsVpcEndpointInfo`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct AwsVpcEndpointInfo {
    /// The AWS account ID in which this VPC endpoint lives.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub aws_account_id: Option<String>,
    /// The ID of the Databricks VPC endpoint service that this endpoint connects
    /// to.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub aws_endpoint_service_id: Option<String>,
    /// The ID of the underlying VPC endpoint in AWS. Provided by the customer
    /// when registering an existing AWS VPC endpoint.
    #[serde(default)]
    pub aws_vpc_endpoint_id: String,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request (in the JSON body, or the query string for GET/DELETE).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl AwsVpcEndpointInfo {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(aws_vpc_endpoint_id: impl Into<String>) -> Self {
        Self {
            aws_vpc_endpoint_id: aws_vpc_endpoint_id.into(),
            ..Default::default()
        }
    }

    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `aws_account_id`.
    #[must_use]
    pub fn with_aws_account_id(mut self, value: impl Into<String>) -> Self {
        self.aws_account_id = Some(value.into());
        self
    }

    /// Set `aws_endpoint_service_id`.
    #[must_use]
    pub fn with_aws_endpoint_service_id(mut self, value: impl Into<String>) -> Self {
        self.aws_endpoint_service_id = Some(value.into());
        self
    }

    /// Set `aws_vpc_endpoint_id`.
    #[must_use]
    pub fn with_aws_vpc_endpoint_id(mut self, value: impl Into<String>) -> Self {
        self.aws_vpc_endpoint_id = value.into();
        self
    }
}

/// `AzurePrivateEndpointInfo`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct AzurePrivateEndpointInfo {
    /// The name of the Private Endpoint in the Azure subscription.
    #[serde(default)]
    pub private_endpoint_name: String,
    /// The GUID of the Private Endpoint resource in the Azure subscription. This
    /// is assigned by Azure when the user sets up the Private Endpoint.
    #[serde(default)]
    pub private_endpoint_resource_guid: String,
    /// The full resource ID of the Private Endpoint.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub private_endpoint_resource_id: Option<String>,
    /// The resource ID of the Databricks Private Link Service that this Private
    /// Endpoint connects to.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub private_link_service_id: Option<String>,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request (in the JSON body, or the query string for GET/DELETE).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl AzurePrivateEndpointInfo {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(
        private_endpoint_name: impl Into<String>,
        private_endpoint_resource_guid: impl Into<String>,
    ) -> Self {
        Self {
            private_endpoint_name: private_endpoint_name.into(),
            private_endpoint_resource_guid: private_endpoint_resource_guid.into(),
            ..Default::default()
        }
    }

    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `private_endpoint_name`.
    #[must_use]
    pub fn with_private_endpoint_name(mut self, value: impl Into<String>) -> Self {
        self.private_endpoint_name = value.into();
        self
    }

    /// Set `private_endpoint_resource_guid`.
    #[must_use]
    pub fn with_private_endpoint_resource_guid(mut self, value: impl Into<String>) -> Self {
        self.private_endpoint_resource_guid = value.into();
        self
    }

    /// Set `private_endpoint_resource_id`.
    #[must_use]
    pub fn with_private_endpoint_resource_id(mut self, value: impl Into<String>) -> Self {
        self.private_endpoint_resource_id = Some(value.into());
        self
    }

    /// Set `private_link_service_id`.
    #[must_use]
    pub fn with_private_link_service_id(mut self, value: impl Into<String>) -> Self {
        self.private_link_service_id = Some(value.into());
        self
    }
}

/// `CreateEndpointRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct CreateEndpointRequest {
    /// `endpoint`
    #[serde(default)]
    pub endpoint: Endpoint,
    /// The parent resource name of the account under which the endpoint is
    /// created. Format: `accounts/{account_id}`.
    #[serde(skip)]
    pub parent: String,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request (in the JSON body, or the query string for GET/DELETE).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl CreateEndpointRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(endpoint: impl Into<Endpoint>, parent: impl Into<String>) -> Self {
        Self {
            endpoint: endpoint.into(),
            parent: parent.into(),
            ..Default::default()
        }
    }

    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `endpoint`.
    #[must_use]
    pub fn with_endpoint(mut self, value: impl Into<Endpoint>) -> Self {
        self.endpoint = value.into();
        self
    }

    /// Set `parent`.
    #[must_use]
    pub fn with_parent(mut self, value: impl Into<String>) -> Self {
        self.parent = value.into();
        self
    }
}

/// `DeleteEndpointRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct DeleteEndpointRequest {
    /// `name`
    #[serde(skip)]
    pub name: String,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request (in the JSON body, or the query string for GET/DELETE).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl DeleteEndpointRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// Endpoint represents a cloud networking resource in a user's cloud account and
/// binds it to the Databricks account.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct Endpoint {
    /// The Databricks Account in which the endpoint object exists.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    /// Info for an AWS VPC endpoint.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub aws_vpc_endpoint_info: Option<AwsVpcEndpointInfo>,
    /// Info for an Azure private endpoint.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub azure_private_endpoint_info: Option<AzurePrivateEndpointInfo>,
    /// The timestamp when the endpoint was created. The timestamp is in RFC 3339
    /// format in UTC timezone.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub create_time: Option<String>,
    /// The human-readable display name of this endpoint. The input should
    /// conform to RFC-1034, which restricts to letters, numbers, and hyphens,
    /// with the first character a letter, the last a letter or a number, and a
    /// 63 character maximum.
    #[serde(default)]
    pub display_name: String,
    /// The unique identifier for this endpoint under the account. This field is
    /// a UUID generated by Databricks.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub endpoint_id: Option<String>,
    /// Info for a GCP Private Service Connect endpoint.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gcp_psc_endpoint_info: Option<GcpPscEndpointInfo>,
    /// The resource name of the endpoint, which uniquely identifies the
    /// endpoint.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The cloud provider region where this endpoint is located.
    #[serde(default)]
    pub region: String,
    /// The state of the endpoint. The endpoint can only be used if the state is
    /// `APPROVED`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<EndpointState>,
    /// The use case that determines the type of network connectivity this
    /// endpoint provides. This field is automatically determined based on the
    /// endpoint configuration and cloud-specific settings.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub use_case: Option<EndpointUseCase>,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request (in the JSON body, or the query string for GET/DELETE).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl Endpoint {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(display_name: impl Into<String>, region: impl Into<String>) -> Self {
        Self {
            display_name: display_name.into(),
            region: region.into(),
            ..Default::default()
        }
    }

    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `account_id`.
    #[must_use]
    pub fn with_account_id(mut self, value: impl Into<String>) -> Self {
        self.account_id = Some(value.into());
        self
    }

    /// Set `aws_vpc_endpoint_info`.
    #[must_use]
    pub fn with_aws_vpc_endpoint_info(mut self, value: impl Into<AwsVpcEndpointInfo>) -> Self {
        self.aws_vpc_endpoint_info = Some(value.into());
        self
    }

    /// Set `azure_private_endpoint_info`.
    #[must_use]
    pub fn with_azure_private_endpoint_info(
        mut self,
        value: impl Into<AzurePrivateEndpointInfo>,
    ) -> Self {
        self.azure_private_endpoint_info = Some(value.into());
        self
    }

    /// Set `create_time`.
    #[must_use]
    pub fn with_create_time(mut self, value: impl Into<String>) -> Self {
        self.create_time = Some(value.into());
        self
    }

    /// Set `display_name`.
    #[must_use]
    pub fn with_display_name(mut self, value: impl Into<String>) -> Self {
        self.display_name = value.into();
        self
    }

    /// Set `endpoint_id`.
    #[must_use]
    pub fn with_endpoint_id(mut self, value: impl Into<String>) -> Self {
        self.endpoint_id = Some(value.into());
        self
    }

    /// Set `gcp_psc_endpoint_info`.
    #[must_use]
    pub fn with_gcp_psc_endpoint_info(mut self, value: impl Into<GcpPscEndpointInfo>) -> Self {
        self.gcp_psc_endpoint_info = Some(value.into());
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = Some(value.into());
        self
    }

    /// Set `region`.
    #[must_use]
    pub fn with_region(mut self, value: impl Into<String>) -> Self {
        self.region = value.into();
        self
    }

    /// Set `state`.
    #[must_use]
    pub fn with_state(mut self, value: impl Into<EndpointState>) -> Self {
        self.state = Some(value.into());
        self
    }

    /// Set `use_case`.
    #[must_use]
    pub fn with_use_case(mut self, value: impl Into<EndpointUseCase>) -> Self {
        self.use_case = Some(value.into());
        self
    }
}

::community_databricks_core::open_enum! {
    /// `EndpointState` values.
    pub enum EndpointState {
        /// `APPROVED`
        Approved => "APPROVED",
        /// `DISCONNECTED`
        Disconnected => "DISCONNECTED",
        /// `FAILED`
        Failed => "FAILED",
        /// `PENDING`
        Pending => "PENDING",
    }
}

::community_databricks_core::open_enum! {
    /// `EndpointUseCase` values.
    pub enum EndpointUseCase {
        /// `SERVICE_DIRECT`
        ServiceDirect => "SERVICE_DIRECT",
    }
}

/// `GcpPscEndpointInfo`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GcpPscEndpointInfo {
    /// The GCP region of the PSC connection endpoint. Provided by the customer
    /// when registering an existing PSC endpoint. GCP supports only same-region
    /// PSC, so this must match the workspace region.
    #[serde(default)]
    pub endpoint_region: String,
    /// The GCP consumer project ID in which this PSC endpoint is created.
    /// Provided by the customer when registering an existing PSC endpoint.
    #[serde(default)]
    pub project_id: String,
    /// The ID of the underlying Private Service Connect connection in the GCP
    /// consumer project, assigned by GCP when the PSC connection is created.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub psc_connection_id: Option<String>,
    /// The name of this PSC connection in the GCP consumer project. Provided by
    /// the customer when registering an existing PSC endpoint.
    #[serde(default)]
    pub psc_endpoint: String,
    /// The ID of the Databricks service attachment this PSC endpoint connects
    /// to.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_attachment_id: Option<String>,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request (in the JSON body, or the query string for GET/DELETE).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl GcpPscEndpointInfo {
    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `endpoint_region`.
    #[must_use]
    pub fn with_endpoint_region(mut self, value: impl Into<String>) -> Self {
        self.endpoint_region = value.into();
        self
    }

    /// Set `project_id`.
    #[must_use]
    pub fn with_project_id(mut self, value: impl Into<String>) -> Self {
        self.project_id = value.into();
        self
    }

    /// Set `psc_connection_id`.
    #[must_use]
    pub fn with_psc_connection_id(mut self, value: impl Into<String>) -> Self {
        self.psc_connection_id = Some(value.into());
        self
    }

    /// Set `psc_endpoint`.
    #[must_use]
    pub fn with_psc_endpoint(mut self, value: impl Into<String>) -> Self {
        self.psc_endpoint = value.into();
        self
    }

    /// Set `service_attachment_id`.
    #[must_use]
    pub fn with_service_attachment_id(mut self, value: impl Into<String>) -> Self {
        self.service_attachment_id = Some(value.into());
        self
    }
}

/// `GetEndpointRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct GetEndpointRequest {
    /// `name`
    #[serde(skip)]
    pub name: String,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request (in the JSON body, or the query string for GET/DELETE).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl GetEndpointRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `name`.
    #[must_use]
    pub fn with_name(mut self, value: impl Into<String>) -> Self {
        self.name = value.into();
        self
    }
}

/// `ListEndpointsRequest`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListEndpointsRequest {
    /// `page_size`
    #[serde(skip)]
    pub page_size: Option<i64>,
    /// `page_token`
    #[serde(skip)]
    pub page_token: Option<String>,
    /// The parent resource name of the account to list endpoints for. Format:
    /// `accounts/{account_id}`.
    #[serde(skip)]
    pub parent: String,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request (in the JSON body, or the query string for GET/DELETE).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl ListEndpointsRequest {
    /// A value with the required fields set.
    #[must_use]
    pub fn new(parent: impl Into<String>) -> Self {
        Self {
            parent: parent.into(),
            ..Default::default()
        }
    }

    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `page_size`.
    #[must_use]
    pub fn with_page_size(mut self, value: i64) -> Self {
        self.page_size = Some(value);
        self
    }

    /// Set `page_token`.
    #[must_use]
    pub fn with_page_token(mut self, value: impl Into<String>) -> Self {
        self.page_token = Some(value.into());
        self
    }

    /// Set `parent`.
    #[must_use]
    pub fn with_parent(mut self, value: impl Into<String>) -> Self {
        self.parent = value.into();
        self
    }
}

/// `ListEndpointsResponse`.
#[derive(Debug, Clone, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[non_exhaustive]
pub struct ListEndpointsResponse {
    /// `items`
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub items: Vec<Endpoint>,
    /// `next_page_token`
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    /// Fields not modelled by this SDK version. Kept when read, so a
    /// read-modify-write round trip never drops them, and sent with a
    /// request (in the JSON body, or the query string for GET/DELETE).
    #[serde(
        flatten,
        default,
        skip_serializing_if = "::std::collections::BTreeMap::is_empty"
    )]
    pub other: ::std::collections::BTreeMap<String, ::serde_json::Value>,
}

impl ListEndpointsResponse {
    /// Set a field this SDK version doesn't model (see `other`).
    #[must_use]
    pub fn with_other(
        mut self,
        name: impl Into<String>,
        value: impl Into<::serde_json::Value>,
    ) -> Self {
        self.other.insert(name.into(), value.into());
        self
    }

    /// Set `items`.
    #[must_use]
    pub fn with_items(mut self, value: impl Into<Vec<Endpoint>>) -> Self {
        self.items = value.into();
        self
    }

    /// Set `next_page_token`.
    #[must_use]
    pub fn with_next_page_token(mut self, value: impl Into<String>) -> Self {
        self.next_page_token = Some(value.into());
        self
    }
}

/// These APIs manage endpoint configurations for this account.
#[derive(Debug, Clone)]
pub struct EndpointsApi {
    api: ApiClient,
}

impl EndpointsApi {
    /// Wrap an [`ApiClient`].
    #[must_use]
    pub fn new(api: ApiClient) -> Self {
        Self { api }
    }

    /// Creates a new network connectivity endpoint that enables private connectivity
    /// between your network resources and Databricks services.
    ///
    /// After creation, the endpoint is initially in the PENDING state. The
    /// Databricks endpoint service automatically reviews and approves the endpoint
    /// within a few minutes. Use the GET method to retrieve the latest endpoint
    /// state.
    ///
    /// An endpoint can be used only after it reaches the APPROVED state.
    ///
    /// `POST /api/networking/v1/{parent}/endpoints`
    pub async fn create_endpoint(
        &self,
        request: CreateEndpointRequest,
    ) -> ::community_databricks_core::Result<Endpoint> {
        let path = format!(
            "/api/networking/v1/{}/endpoints",
            path_param(&request.parent.to_string(), true)
        );
        let mut call = Call::new(Method::POST, path);
        call = call.json(&request.endpoint)?;
        self.api.send::<Endpoint>(call).await
    }

    /// Deletes a network endpoint. This will remove the endpoint configuration from
    /// Databricks. Depending on the endpoint type and use case, you may also need to
    /// delete corresponding network resources in your cloud provider account.
    ///
    /// `DELETE /api/networking/v1/{name}`
    pub async fn delete_endpoint(
        &self,
        request: DeleteEndpointRequest,
    ) -> ::community_databricks_core::Result<()> {
        let path = format!(
            "/api/networking/v1/{}",
            path_param(&request.name.to_string(), true)
        );
        let mut call = Call::new(Method::DELETE, path);
        call = call.query(query::to_pairs(&request.other)?);
        self.api
            .send::<::serde::de::IgnoredAny>(call)
            .await
            .map(|_| ())
    }

    /// Gets details of a specific network endpoint.
    ///
    /// `GET /api/networking/v1/{name}`
    pub async fn get_endpoint(
        &self,
        request: GetEndpointRequest,
    ) -> ::community_databricks_core::Result<Endpoint> {
        let path = format!(
            "/api/networking/v1/{}",
            path_param(&request.name.to_string(), true)
        );
        let mut call = Call::new(Method::GET, path);
        call = call.query(query::to_pairs(&request.other)?);
        self.api.send::<Endpoint>(call).await
    }

    /// One page of [`list_endpoints`](Self::list_endpoints).
    ///
    /// `GET /api/networking/v1/{parent}/endpoints`
    pub async fn list_endpoints_page(
        &self,
        request: ListEndpointsRequest,
    ) -> ::community_databricks_core::Result<ListEndpointsResponse> {
        let path = format!(
            "/api/networking/v1/{}/endpoints",
            path_param(&request.parent.to_string(), true)
        );
        let mut call = Call::new(Method::GET, path);
        call = call.query(query::field("page_size", &request.page_size)?);
        call = call.query(query::field("page_token", &request.page_token)?);
        call = call.query(query::to_pairs(&request.other)?);
        self.api.send::<ListEndpointsResponse>(call).await
    }

    /// Lists all network connectivity endpoints for the account.
    ///
    /// This method is generated by Databricks SDK Code Generator.
    ///
    /// `GET /api/networking/v1/{parent}/endpoints`
    ///
    /// Returns a lazily paginated stream.
    #[must_use]
    pub fn list_endpoints(&self, request: ListEndpointsRequest) -> Paged<'static, Endpoint> {
        let this = Clone::clone(self);
        paging::paginate(
            request,
            move |req: &ListEndpointsRequest| {
                let this = Clone::clone(&this);
                let req = req.clone();
                async move { this.list_endpoints_page(req).await }
            },
            |req, resp| {
                let items = resp.items;
                let more = paging::next_token(resp.next_page_token, |t| req.page_token = Some(t));
                (items, more)
            },
        )
    }

    /// Every page of [`list_endpoints`](Self::list_endpoints), collected.
    pub async fn list_endpoints_all(
        &self,
        request: ListEndpointsRequest,
    ) -> ::community_databricks_core::Result<Vec<Endpoint>> {
        paging::collect(self.list_endpoints(request)).await
    }
}
